sphinx-contrib/confluencebuilder

- sphinxcontrib/writers/confluence.py
The following adjusts the use of Sphinx's [admonition directives](http://docutils.sourceforge.net/docs/ref/rst/directives.html#admonitions) to take advantage of Confluence's [Info, Tip, Note, and Warning Macros](https://confluence.atlassian.com/doc/info-tip-note-and-warning-macros-51872369.html).
Stock Sphinx rendering:
> ![contrib-stock](https://cloud.githubusercontent.com/assets/1834509/24338881/94bd0fd2-1276-11e7-8a2f-263b3a719c34.png)
Stock sphinxcontrib-confluencebuilder rendering:
> ![contrib-pre](https://cloud.githubusercontent.com/assets/1834509/24338883/973eb864-1276-11e7-8b41-d1777638fada.png)
New sphinxcontrib-confluencebuilder rendering:
> ![contrib-post](https://cloud.githubusercontent.com/assets/1834509/24338884/98d8b01c-1276-11e7-99d5-97d4d1428b96.png)
> use macros for admonitions

- README.rst
- sphinxcontrib/builders/confluence.py
- sphinxcontrib/confluencebuilder.py
Introduces the ability to purge a detected set of legacy pages from a configured parent page. In the event a user configures the option `confluence_purge` to "True", the builder will keep track of all known descendants of the parent page. When the builder starts publishing pages, any previously tracked descendant matching the identifier of a recently uploaded page will be removed from the legacy list. During the finalization phase, if any legacy pages still remain in the list, these legacy pages will be removed.
> provide purging support

- README.rst
- sphinxcontrib/confluencebuilder.py
- sphinxcontrib/writers/confluence.py
Introduces the ability for a user to configure a header/footer file which content can be to apply to all parsed paged. In the event a user configures the option `confluence_header_file`, the writer will attempt to read the contents of the file and inject it into each generated file before the body text. Similar with `confluence_footer_file` which will attempt to inject content after the body text.
An example case is configuring with the following header/footer configurations:
confluence_header_file='myheader.tpl'
confluence_footer_file='myfooter.tpl'
With a header file contents of:
```
{panel:borderColor=#CCCCCC|bgColor=#FCFCFC}
Page has been automatically generated.
{panel}
```
And a footer file contents of:
```
----
{expand:View History}
{change-history}
{expand}
```
The following …
> provide header/footer support

- CHANGES.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/common.py
- sphinxcontrib/confluencebuilder/writer.py
- test/test_builder.py
- test/testproj/expected/ref.conf
- test/testproj/ref.rst
- test/testproj/toctree.rst
The following commits improves/restores support for a series of reference usages in Sphinx. This change includes:
- Improves cross-referencing arbitrary locations (anchors).
- Improves cross-referencing documents (internal).
- Working external links.
This also includes unit test additions/restorations and cleanup of certain files.
> writer: improve/restore reference (link) support

- sphinxcontrib/confluencebuilder/publisher.py
This reverts commit 4f85cd030374b8e1bafd2bf49c0e49a598008de6.
Observed on Confluence Cloud that requests are case-sensitive to the
space of a name. A user must match the configured space name to the case
of the Confluence space name.
Signed-off-by: James Knight <james.d.knight@live.com>
> revert "publisher: ensure used space name is uppercase"

- sphinxcontrib/confluencebuilder/rest.py
use rsp.text instead of rsp.content for json.loads.
Prior to python3.6 json.loads only allows type str or unicode (python2).
rsp.content is of type bytes in python3 so json.loads fails (python3.* < 3.6).
rsp.text is of type str in python3, unicode in python2, it should work.
> fix python3 < 3.6 incompatibility in rest.py

- .travis.yml
- requirements_dev.txt
- tox.ini
The Travis CI environment prepares a test environment with the most recent version of pip available (v9.0.1); however, using this version results in the following error #45:
AttributeError: '_NamespacePath' object has no attribute 'sort'
Adjusting the tox requirements to forcefully update pip to the newest version for the interim. When pip v9.0.2+ is available, this commit can be reverted.
> support interim pip for ci

- CHANGES.rst
- README.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/publisher.py
In Confluence, when a page is updated, watchers will be notified of any page changes unless the edit is flagged as minor. The following provides the ability for a publisher to flag any page updates as minor edits. By setting the configuration option `confluence_disable_notifications` to `True`, any existing page edits will be flagged as a "minor edit".
For XML-RPC publishing, page updates are now handled by the "updatePage" method (over the "storePage" method). This is to allow the publisher to provide update options along side any page content edits.
> publisher: allow publish without notification

- README.rst
Adds to the README the location to a used validation set and a link to a Confluence Cloud instance which provides an end-result demonstration of this Sphinx extension.
This is not required; only a suggestion. If not desired, feel free to drop this PR.
> README: add a demonstration url

- README.rst
- doc/configuration.rst
- doc/documentation.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/config.py
- sphinxcontrib/confluencebuilder/translator/shared.py
- sphinxcontrib/confluencebuilder/translator/wiki.py
- test/publish-set/expected-wiki/toctree-doc1.conf
- test/publish-set/expected-wiki/toctree-doc2.conf
- test/publish-set/expected-wiki/toctree-doc3.conf
- test/publish-set/expected-wiki/toctree.conf
- test/publish-set/toctree-doc1.rst
- test/publish-set/toctree-doc2.rst
- test/publish-set/toctree-doc2a.rst
- test/publish-set/toctree-doc2b.rst
- test/publish-set/toctree-doc2c.rst
- test/publish-set/toctree-doc3.rst
- test/test_builder.py
- test/test_publish.py
- test/test_publisher.py
- tox.ini
_(marked as RFC; while one could merged this content in, additional changes are planned to be made)_
The following contains a series of improvements for the Confluence builder extension. Most notables includes:
- Support for maximum page depth (based off of comment/changes noted in #35).
- Fix CI testing with newer version of pylint.
- A series of minor changes to documentation/etc.
Please ensure 9d0dda592a9aabc10634019eb9842eccf705a8ae is examined to ensure these changes fit with the expected long term use of this plugin.
> rfc: slew of extension improvements - "red parachute"

- .travis.yml
- README.rst
- setup.py
- tox.ini
Python Software Foundation has published the last release of the Python 3.3 series (3.3.7). Version for this series is no longer supported as of 2017-09-29. See:
> https://www.python.org/downloads/release/python-337/
Drop references to Python 3.3.x in the README.rst file as well as remove setup/CI references.
In a related note, even Travis CI has dropped Python 3.3.x support:
```
ERROR: InterpreterNotFound: python3.3
(ex: https://travis-ci.org/tonybaloney/sphinxcontrib-confluencebuilder/jobs/315668142)
```
> python 3.3.x has been obsoleted

- sphinxcontrib/confluencebuilder/builder.py
Corrects a regression error which, by default, suppresses any helpful configuration error messages from being shown to the user. At this any, any configuration error detect simply outputs "configuration error". A suppression mechanism was added to help limit the output of a unit test when validating bad configuration states (1784761446fe0baa76cce16a0886b697abf14ba5). A builder should not suppress the configuration message by default. The argument flag in the builder's initializer is being toggled to correct this.
> builder: do not default suppress configuration error message

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/builder.py
This pull request focuses on the enhancement request made in "provide option to automatically generate a title for titleless documents" (#68). By default, documents missing titles will have a title value automatically generated. This capability can be disable by configuring the option `confluence_disable_autogen_title`. See commit be200627b628fc02e9ea0d7ad866926c71b0aeca for more specifics.
> automatically generated document titles

- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/rest.py
In the event that a REST API POST/PUT call fails due to a Confluence
API error state, dump the pushed JSON content to the exception message.
This is to assist in a series of development and user-reported scenarios
where content pushes return a basic exception with only a limited amount
of information to debug. Along with the content data being dumped, the
JSON block of data will also include other helpful information such as
the target key/title, page identifier and more.
Signed-off-by: James Knight <james.d.knight@live.com>
> rest: output post/put json on rest api err

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/std/__init__.py
- sphinxcontrib/confluencebuilder/std/confluence.py
- sphinxcontrib/confluencebuilder/std/sphinx.py
- sphinxcontrib/confluencebuilder/translator/shared.py
- sphinxcontrib/confluencebuilder/translator/wiki.py
A series of improvements related to the usage of code block languages:
- Literal block-based directives will have language values translated to Confluence-supported language values. This is to avoid macro errors with Confluence's code block macro (see also #75).
- Adds support for Sphinx's `highlight_language` configuration and `hightlight` directive. This allows custom highlighting to be applied on literal blocks (and `literalincludes`) properly.
A series of unit tests to help validate some of these changes have not been included in this commit. These have been designed outside the existing `test_builder` structure into a new test suite to provide more flexibility to invoke unit tests using various configuration and Sphinx application instances. I plan to submit these changes as part of …
> literal markup improvements

- sphinxcontrib/confluencebuilder/builder.py
Recently, support for automatic title generation for documents which
have no title has been added \[1\]. This feature introduces a false
positive warning which indicates that a page has no title, even though
the document has one. This change addresses the generated warnings to
ensure that any auto-title generation and/or warning message first
requires a missing document title.
Note: this addresses a poor logging call; older versions which include
the auto-title generation feature would still properly extract and use
document titles as expected (no matter what the logs indicated).
\[1\]: be200627b628fc02e9ea0d7ad866926c71b0aeca
> address false positive on no title warning

- README.rst
Bump the minimum support for Confluence Server to at least v5.9. At the
time of this commit, v5.8 and older have reached end of life \[1\]. While
support can be maintained for older versions, attempting to limit the
amount of versions that will officially go through validating testing.
\[1\]: https://confluence.atlassian.com/display/CONF58
This is an attempt to help limit the amount of validation support for some prospect changes I'm hoping to complete. I've been occasionally testing with older versions of Confluence servers (ex: 4.1.10, 5.6.6, etc.) but I doubt most users are using these versions.
> limit support to supported confluence server versions

- requirements_dev.txt
- tox.ini
Corrects and cleans up the tox configuration/dependency file. This should finally address primary issues experienced with Travis CI with respect to `'_NamespacePath' object has no attribute 'sort'` and other import errors.
This cleanup also reverts an older commit with relaxed CI building when missing interpreters. I believe if the intent is to support specific Python interpreters, a standard build should include them all and pass to be a valid build (and nothing stops a developer environment from manually invoking individual interprets to run).
> tox pip cleanup

- .travis.yml
Travis CI instances support Python 3.6 \[1\]; adding the additional environment type. Adding a build matrix \[2\] to explicitly define the respective Python interpreters to use for each tox environment to be tested.
\[1\]: https://docs.travis-ci.com/user/languages/python/#Specifying-Python-versions
\[2\]: https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix
> .travis.yml: add python 3.6

- sphinxcontrib/confluencebuilder/exceptions.py
- sphinxcontrib/confluencebuilder/publisher.py
- sphinxcontrib/confluencebuilder/rest.py
Improve the transport class for XML-RPC interaction when a proxy/timeout is configured. This commit provides a series of corrections and improvements:
1) Corrects a series of runtime errors when attempting to apply proxy/
timeout issues using various versions of Python (due to various
implementations of urllib/xmlrpclib (specifically, this fixes\
Python 3.4+ instances).
2) Allows system level proxy configuration (ex. http_proxy/https_proxy)
to work for XML-RPC communication (as it currently works for REST).
3) Adds support for proxy authentication.
4) Adds support for HTTPS-based targets/proxies.
This change also resolves an issue observed in #48.
> improve proxy/timeout support

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/publisher.py
Provides two changes related to purging:
- publisher: add compatibility support for descendants fetch
Corrects an issue observed in Confluence Server where purging descendants with hierarchy mode fail.
- builder: support purging from master_doc base
Supports purging from a `master_doc` instead of a space root/parent-page (primarily introduced for some upcoming validation set improvements).
> purge improvements

- sphinxcontrib/confluencebuilder/builder.py
When support was added for "max-depth" \[1\], the adjusted code never took
advantage of the ordered publish document list required to ensure pages
are assigned a proper parent in hierarchy mode. Adjusting the
prepare_writing stage to work off of 'ordered_docnames' instead of
'docnames'.
\[1\]: 9d0dda592a9aabc10634019eb9842eccf705a8ae
> builder: correct publish order for proper hierarchy support

- sphinxcontrib/confluencebuilder/translator/wiki.py
Adjusts the 'raw' directive to help support pass-through content for Confluence-prepared content. Adjusts the handle format from "text" to "confluence" (for proper format type identification) and ensure text is added to the body using internal data management.
> wiki: support raw data pass-through

- sphinxcontrib/confluencebuilder/publisher.py
- sphinxcontrib/confluencebuilder/rest.py
When using a REST client, close the session \[1\] when cleaning up the
publish request. This ensures the session is cleaned up, as well as
removes the following warning in some installations:
ResourceWarning: unclosed <socket.socket fd=..., family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('...', ...), raddr=('...', ...)>
\[1\]: http://docs.python-requests.org/en/master/api/#requests.Session.close
(see also #48)
> publisher,rest: cleanup rest session

- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/publisher.py
- sphinxcontrib/confluencebuilder/rest.py
- sphinxcontrib/confluencebuilder/std/confluence.py
- sphinxcontrib/confluencebuilder/util.py
- test/unit-tests/common/test_util.py
This extension requires a user to provide the URL path of the Confluence
instances to interact with when publishing. The configuration handling
was designed to take the "base" portion of the URL and the extension
would later attached the REST or XML-RPC bind point later.
This commit provides more flexibly in the configured URL by
automatically detecting URLs, for example, with the API bind point set.
The normalizing method will remove and cleanup the final URL before its
use. In the event that this extension normalizes the URL, a warning
message will be generated to the user (to promote a proper configuration
value).
> builder: provided flexible url handling

- sphinxcontrib/confluencebuilder/rest.py
The typical response in an error case provided a message value
containing JSON formatted data. In the case where a server returns
non-JSON data (for example, an invalid server URL), an exception will
be thrown when preparing the message to display. The following adds
exception handling and informs the user that the returned content is not
JSON-based data.
Signed-off-by: James Knight <james.d.knight@live.com>
> rest: handle non-json responses

- sphinxcontrib/confluencebuilder/publisher.py
- test/unit-tests/common/test_publisher.py
This resolves an issue such that if the RPC interface is being
used and no client_certificate was provided, an error would be
raised. This prevents this issue.
Signed-off-by: Logan Jones <loganasherjones@gmail.com>
> Fixed bug for 1-way SSL RPC calls.

- sphinxcontrib/confluencebuilder/builder.py
When populating a list of documents to purge from a space, a list of legacy pages is populated once after the first publish attempt (to easily fetch the base page identifier). In the event which the base page does not have any descendants (usually first-ever publish attempt), an empty list is generated and set into `self.legacy_pages`. When this scenario occurs, the next publish page will re-populate the known legacy pages list which could result in pages which have already been flagged as not-legacy as legacy again. To address this, an explicit check is made so that only if `self.legacy_pages` is `None` will a list of descendants be populated.
> builder: incorrectly flagged legacy page(s) on empty descendants

- sphinxcontrib/confluencebuilder/builder.py
- test/unit-tests/toctree/dataset-hierarchy/toctree-doc2a.rst
- test/unit-tests/toctree/dataset-hierarchy/toctree-doc2aa.rst
- test/unit-tests/toctree/dataset-hierarchy/toctree-doc2aaa.rst
- test/unit-tests/toctree/dataset-hierarchy/toctree.rst
- test/unit-tests/toctree/expected-hierarchy/toctree-doc2.conf
- test/unit-tests/toctree/test_toctree_hierarchy.py
When a documentation's configuration defines a forced maximum depth for pages (`confluence_max_doc_depth`), parent pages will have their maximum depth values changed so that Sphinx doesn't attempt to populate descendants beyond the configured limit. In the event where a document doesn't define a maximum depth inside its toctree, the maximum depth value is translated to a value of "-1". This by-passes the internal maximum depth check. Correcting this by just forcing the maximum depth for toctree's which do not explicitly define one.
This address issue #100.
> builder: force toctree max-depth's when squashing

- test/sphinxcontrib_confluencebuilder_util.py
not and are displayed like  '?[31;01mThis is a warning...'.
Colorama is not intercepting the control strings and converting them
into Windows color commands.
Colorama has to be initialized and the resulting sys.stderr mock
passed to Sphinx() to ensure correct colorization.
Signed-off-by: Paul D.Smith <paul_d_smith@hotmail.com>
> Warnings are supposed to be colored but on Windows they are sometimes

- .travis.yml
Perform integration tests under Python 3.7.
> .travis.yml: adding python 3.7 test

- README.rst
When rendering the build status badge on the README, only show the status from the master branch (to avoid pending merge requests from reflecting a bad build state for the repository).
> README.rst: show build status on master branch

- CONTRIBUTING.rst
Adding a new `CONTRIBUTING` document to assist developers wishing to submit new changes to this extension.
(see also #110)
> CONTRIBUTING.rst: adding document

- sphinxcontrib/confluencebuilder/publisher.py
When a REST-based publishing event checks for page descendants (when purging legacy pages), a CQL search request can be made when attempting to find descendants for a space. The provided space name is not quoted, and causes the CQL expression to break with some valid space name values (for example, personal spaces which are prefixes with a tilde (`~`) character). Enclosing the space name with quotes prevent an expression error.
> publisher: handle various space names in desc-check

- sphinxcontrib/confluencebuilder/builder.py
_(edit: this feature has been reworked based off observations from #130; see comment history for original content)_
The following attempts to improve the determined title value for a document to be published. Originally, there was "smart" checks to help try exact the leading section's title value from a document. It would only attempt to consider the first node after skipping a series of "no-content nodes" (e.x. comments, etc.). This was to prevent having a bulk of content and then using the first section which exists near the bottom of a document.
The complications from the above approach is that there needs to be a explicit list of node types to verify as "no-content" before taking the next "real" node to consider. While categories like `nodes.Invisible` was tried, not all directive …
> builder: improve document title fetching

- sphinxcontrib/confluencebuilder/publisher.py
Confluence Cloud may (rarely) fail to complete a content request with an `OptimisticLockException`/ `StaleObjectStateException` exception:
```
com.atlassian.confluence.core.persistence.confluence.StaleObjectStateException: javax.persistence.OptimisticLockException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1
```
It is suspected that this is just an instance timing/processing issue. If this is observed, wait a moment and retry the content request. If it happens again, the put request will fail as it normally would. This should assist in users when publishing large document sets (200+).
> publisher: handle confluence transaction failure

- sphinxcontrib/confluencebuilder/rest.py
When an error occurs interacting with a Confluence instance, some advanced error cannot be completely interpreted from the provided `message` content. In addition to the message, Confluence may populate more notifications inside `'data': { 'errors': [...] }`. To handle this and possibly other odd scenarios, just dump the entire response data in the event of an unknown error.
> rest: output more detailed rest failures

- sphinxcontrib/confluencebuilder/translator.py
- test/unit-tests/common/dataset-common/references.rst
- test/unit-tests/common/expected/citations.conf
- test/unit-tests/common/expected/glossary-ref.conf
- test/unit-tests/common/expected/glossary.conf
- test/unit-tests/common/expected/references-ref.conf
- test/unit-tests/common/expected/references.conf
- test/unit-tests/toctree/expected-def/contents.conf
- test/unit-tests/toctree/expected-def/doca.conf
- test/unit-tests/toctree/expected-def/docb.conf
- test/unit-tests/toctree/expected-def/docc.conf
- test/unit-tests/toctree/expected-hierarchy/toctree-doc1.conf
- test/unit-tests/toctree/expected-hierarchy/toctree-doc2.conf
- test/unit-tests/toctree/expected-hierarchy/toctree-doc3.conf
- test/unit-tests/toctree/expected-hierarchy/toctree.conf
- test/validation-sets/common/references.rst
The original reference processing pulled the reference label information from the node (or the children of the reference node) and built a link before skipping the processing of the remainder of the node. This breaks the ability to render inline content that can be wrapped around a reference node. For example, the following reStructuredText markup should allow the construction of a bolded link:
.. _a link: https://example.com/
.. |a link| replace:: **a bolded link**
|a link|_
Adjusting reference processing to not invoke pruning exception (when possible to render inline markup). Due to various reference types, it is not ideal to populate the internal `self.context` array. Instead, a new interim context array `self._reference_context` can be populated and each entry will be pop'ed when the …
> translator: allow inline markup inside references

- test/test_main.py
When testing, an original method to view a more verbose output was to use the `-v` argument. However, `--verbose` or `-V` options are more common flags to use; adjusting.
> test: improve verbose argument

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/builder.py
Introduces a new option `confluence_ask_password` to allow a user to request this extension to prompt for a password to be used for authenticating with a publish event to the configured Confluence instance.
This feature is to assist in user's who wish to invoke a publish request on a documentation set without having to manually adjust the documentation's configuration, setup external environment/files or provide a clear password in an interactive session. With this feature, user's can invoke a build with the following option to a password prompt to appear:
```
sphinx-build [options] -D confluence_ask_password=1 <srcdir> <outdir>
```
This commit explicitly leaves the `getpass` prompt value as empty and provides the prompt information using system write calls. This is to provide more …
> provide a password prompt option

- doc/configuration.rst
Correcting the configuration example from `confluence_remove_title` to `confluence_ask_password` (copy-n-paste error).
> doc: correcting ask-password configuration

- doc/markup.rst
- test/unit-tests/common/dataset-common/epigraph.rst
- test/unit-tests/common/expected/epigraph.conf
- test/validation-sets/common/other.rst
When adding support for the `epigraph` directive, the implementation also supported both the `highlights` and `pull-quote` directives. Adding a unit/validation test to confirmation and future sanity checks as well as updating the supported-markup document.
> additional quote based directives

- doc/markup.rst
- sphinxcontrib/confluencebuilder/translator.py
- test/unit-tests/common/dataset-common/parsed-literal.rst
- test/unit-tests/common/expected/parsed-literal.conf
- test/unit-tests/common/test_common.py
- test/validation-sets/common/code.rst
Adds support for the parsed literal block directive \[1\]. Unlike the regular literal block where content is thrown into a Confluence code macro for styling, users are explicitly providing custom inline markup for the body content. When a parsed literal block is detected (via the `rawsource` comparison check \[2\]), add a series of wrapping tags and let the translator properly fill the contents. The container tags will include panel-based class styles to mimic Confluence's code macro wrapping (i.e. the indentation, borders and padding).
\[1\]: http://docutils.sourceforge.net/docs/ref/rst/directives.html#parsed-literal-block
\[2\]: https://github.com/sphinx-doc/sphinx/blob/004b68f281dbad6e7598c8c2f56945bb3bc07107/sphinx/writers/html5.py#L367
> add parsed literal support

- sphinxcontrib/confluencebuilder/translator.py
Add a series of node translation hooks for Sphinx's `math` capability, This is to prevent a hard failure (`unknown_visit`) if a user's document contains math-related directives.
> translator: add interim math handling

- doc/_static/theme_overrides.css
Override the default Read the Docs theme by allowing the content viewport to not have a restricted width. This allows content to expand beyond the 800px limit (to use the full page; in a similar fashion as the Kernel's documentation does).
> doc: theme improvement for wider viewport

- sphinxcontrib/confluencebuilder/translator.py
When docutils block quotes are processed for indented paragraph blocks, child values are checked to help build consistent look-and-feel when various block levels are in play. The traverse check to detect if a node is a first-child will directly attempt to check the first element in the list; however, there is no guarantee that any children will exist (thus causing an `IndexError` exception).
Adjusting the check to ensure the next-child value actually has elements to check against.
> translator: correct next-child check for indent styling

- test/unit-tests/literal-markup/test_literal_markup.py
The code blocks test no longer passes under Sphinx 1.8. It is suspected to be a result of the removal for the deprecated `highlightlang` directive \[1\]. For the interim, skip the test until the issue can resolved.
\[1\]: https://github.com/tonybaloney/sphinxcontrib-confluencebuilder/issues/148
> test: skip code blocks test

- sphinxcontrib/confluencebuilder/std/confluence.py
Fixes #150 
Signed-off-by: James Bungard <jmbungard@gmail.com>
> Add YAML and Sass to the Pygments lexer to Confluence language map.

- sphinxcontrib/confluencebuilder/translator.py
I had the same issue as #144, this change seems to fix the issue for internal links with anchors.
> Strip anchor before trying to determine doctitle

- test/unit-tests/common/expected/contents.conf
- test/unit-tests/common/test_common.py
Since this test was pending on pending pull request #126 and said request has been since pulled into the tree, re-enabling the test.
> re-enable contents unit test

- CONTRIBUTING.rst
since this project gets a fair amount of PRs/issues nowadays, decided to add a CoC using the contributors covenant as the template. Just modified for rST.
@jdknight as a maintainer I would like your 👍 on this change
> Add Code-of-conduct to contributing.rst

- sphinxcontrib/confluencebuilder/builder.py
When a configuration flags to remove the initial title from Confluence pages, additional work is performed to remove local references from those titles so that a local table of contents does not generate a bad link to itself. This check compares the references identifiers to the matching title's reference identifier before removing; however, not all references may have identifiers (not a requirement for docutils). Adjusting to ensure we check if any identifiers exist before pulling an identifier to check against.
> builder: handle ref with no id in remove-title-check

- sphinxcontrib/confluencebuilder/__init__.py
Enables other extensions to use `sphinx.application.Sphinx#add_node` to support additional node types for confluence output.
Fixes #158
> Register `ConfluenceTranslator` with Sphinx

- sphinxcontrib/confluencebuilder/writer.py
Enables other extensions to use `sphinx.application.Sphinx#add_node`
to support additional node types for confluence output.
Complements changes related to tonybaloney/sphinxcontrib-confluencebuilder#165
Signed-off-by: Pawel Limanowka <plimanowka@gmail.com>
> Use Sphinx Builder.create_translator() to create translator in writer.

- sphinxcontrib/confluencebuilder/builder.py
When specifying individual files to build to `sphinx-build`, `ConfluenceBuilder` ignores this document subset and publishes everything.
This change makes publishing work as expected for my use case and unit tests pass, but please examine the change to see if it potentially introduces any issues. Is it correct to assume that the `docnames` argument to `ConfluenceBuilder.prepare_writing` will always contain everything that needs to be published; or could  `process_tree_structure` in some case produce a document that must be uploaded but is not present in the `docnames` argument?
> Only publish documents that Sphinx asked to prepare

- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/translator.py
Without these changes `sphinx-build` refuses to work in parallel.
In my projects, using the `-j` option with these changes did not produce any ill effects. Is there a reason it shouldn't be allowed?
> Support Sphinx's parallel mode (the `-j` option to `sphinx-build`)

- doc/configuration.rst
- doc/tips.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/config.py
If subset of document names is defined using the `confluence_doc_subset` option, only those documents are processed and uploaded.
This is especially useful for large projects with demanding plugins for building pages (like `sphinxcontrib-plantuml` for example). When starting a build from scratch or when publishing every page is not desired, it is good to be able to explicitly control what will be done.
Using this options implicitly disables `confluence_purge` as keeping it enabled would delete every document that is not in the subset.
> Explicitly define a subset of document names to publish

- sphinxcontrib/confluencebuilder/translator.py
List styling support for enumerated lists checks for a populated `enumtype` value; however, there is no guarantee that docutils will populate the node with a specific enumeration type. If a type is not provided, ignore attempting to apply a style (i.e. use Confluence's default type for ordered lists).
> translator: ignore enumerated list style if not set

- sphinxcontrib/confluencebuilder/config.py
- test/unit-tests/common/test_config.py
Adding a series of unit test assertions to validate the recently added `confluence_publish_subset` option.
Note that this test introduces the use of a `_build_app` helper application, to ensure there is no configuration conflict between individual unit tests. Ideally, other tests can be updated in the future to prevent additional conflicts.
> test: validate publish subset options

- test/unit-tests/literal-markup/test_literal_markup.py
Due to a regression in Sphinx 1.8, `linenothreshold` feature would not work as expected causing the code block test to fail \[1\]. To continue testing with older versions of Sphinx, enable the tests for pre-v1.8 environments. When the fix for `linenothreshold` has been introduced in a stable version of Sphinx, this test can be tweaks to support running on the respective newer versions.
\[1\]: https://github.com/tonybaloney/sphinxcontrib-confluencebuilder/issues/148
> test: skip code block test in sphinx 1.8+ (interim)

- test/unit-tests/common/test_manpage.py
Sphinx's `manpages_url` feature has only been made available in Sphinx v1.7+ releases. Adjusting unit testing to skip over the manpages_url's specific tests when testing under an older version of Sphinx.
> test: skip manpages_url test in pre-sphinx 1.7

- test/sphinxcontrib_confluencebuilder_util.py
- test/test_validation.py
- test/unit-tests/common/test_common.py
- test/unit-tests/common/test_config.py
- test/unit-tests/common/test_header_footer.py
- test/unit-tests/common/test_headings.py
- test/unit-tests/common/test_manpage.py
- test/unit-tests/literal-markup/test_literal_markup.py
- test/unit-tests/literal-markup/test_literal_markup_advanced.py
- test/unit-tests/toctree/test_toctree.py
- test/unit-tests/toctree/test_toctree_hierarchy.py
For the series of unit and validations tests performed with multiple Sphinx instances, it is important to wrap the use of the Sphinx application around the docutils namespace. This prevents collisions for registers directives, etc. between the various Sphinx instances.
This change corrects a series of observed test warnings generated on execution. For example:
```
WARNING: while setting up extension sphinx.domains.changeset: directive 'deprecated' is already registered, it will be overridden
WARNING: while setting up extension sphinx.domains.changeset: directive 'versionadded' is already registered, it will be overridden
WARNING: while setting up extension sphinx.domains.changeset: directive 'versionchanged' is already registered, it will be overridden
WARNING: while setting up extension …
```
> test: wrap docutils namespace for sphinx invokes

- sphinxcontrib/confluencebuilder/builder.py
A series of informative logs added to the build process undesirable adjust the nice output generated by Sphinx. For example, 'querying list of existing pages' is injected into the output stream while publishing a documentation set. Below shows undesired logging to the user:
```
pickling environment... done
checking consistency... done
>  preparing documents... scanning for assets...
>  done
>
>  done
writing output... [100%] verification-of-content
>  querying list of existing pages...tents
publishing documents... [100%] verification-of-content
publishing assets... [100%] extern_....png
build succeeded.
```
Instead, removing these extra logs for a cleaner output.
> builder: cleanup output logging

- sphinxcontrib/confluencebuilder/publisher.py
Confluence's API can accept attachment comments and the `minorEdit` argument through a set of uploaded files [1]. While in the most recent version of requests this is not an issue, requests pre-v2.19 has issues. The `minorEdit` value is provided in boolean form, which the older versions of requests does not handle well. Since this extension still attempts to support at least requests v2.14.0, a workaround is being applied. Instead of configuring the flag with a boolean value, set the value in a compatible string form.
\[1\]: https://docs.atlassian.com/atlassian-confluence/REST/6.6.0/#content/{id}/child/attachment-createAttachments
\[2\]: https://github.com/kennethreitz/requests/commit/8546a15587b2a240c1d1404d3ef99365b911bf13
> publisher: handle asset publishing with older requests

- .travis.yml
- requirements_dev.txt
- sphinxcontrib/confluencebuilder/translator.py
- tox.ini
Improving testing of this extension by including Python 3.7 and various Sphinx versions (1.6-1.8). Both the tox configuration and Travis CI configuration has been updated to test these new environments.
> extend test environment

- setup.py
The minimum supported versions of dependencies has been maintained inside the tox requirements definition (`requirements_dev.txt`). However, these versions were never explicitly set inside `setup.py`; correcting.
> setup.py: configure minimum versions in setup

- CHANGES.rst
- CONTRIBUTING.rst
- doc/documentation.rst
- doc/index.rst
- doc/install.rst
- doc/markup.rst
- doc/tips.rst
- setup.py
- test/unit-tests/literal-markup/test_literal_markup.py
- test/validation-sets/common/images.rst
With the `confluencebuilder` extension now part of the `sphinx-contrib` home, adjusting various references in the repository to use new URLs.
> cleanup: updating references to new home

- .travis.yml
Makes the following changes to this extension's Travis CI configuration:
- Only build `master` branch when a branch is changed (note: pull requests will still build).
- Disable Email notifications on build events.
Edit:
- Enabling caching.
> travis ci tweaks

- test/sandbox/.gitignore
- test/sandbox/README
- test/sphinxcontrib_confluencebuilder_util.py
- test/test_sandbox.py
- tox.ini
Adds an empty test sandbox environment where a developer/testing can quickly dump a custom Sphinx configuration, documentation and a tox requirements file for rapid development. A tox custom environment `sandbox` can be invoked to use content in this folder:
tox -e sandbox
> test: introduce test sandbox

- CHANGES.rst
- sphinxcontrib/confluencebuilder/translator.py
After adding `sphinx.ext.todo` to a project confluence build started failing because of an unsupported node.
As this is an official extension commonly used, it should be supported — especially as this addition is fairly trivial.
> Todo support

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/config.py
- sphinxcontrib/confluencebuilder/nodes.py
- sphinxcontrib/confluencebuilder/translator.py
- test/unit-tests/common/dataset-prevnext/final.rst
- test/unit-tests/common/dataset-prevnext/index.rst
- test/unit-tests/common/dataset-prevnext/middle.rst
- test/unit-tests/common/test_prev_next.py
Provides initial support to have previous/next navigational links at various locations of a document based on a user's configuration. The option `confluence_prev_next_buttons_location` (default disabled with `None`) can be configured with the following to respectively render previous/next buttons for a detected ordered list of documents: bottom, both, top, None.
> support previous/next navigation

- sphinxcontrib/confluencebuilder/translator.py
- test/unit-tests/common/dataset-common/admonitions.rst
- test/unit-tests/common/expected/admonitions.conf
- test/validation-sets/common/admonitions.rst
Re-introduce the visit/depart calls for the admonition type which were removed during the re-work to support Confluence's storage format. This allows the admonition directive to be used in documents (which explicitly provide a title).
> translator: support base admonition translation

- sphinxcontrib/confluencebuilder/translator.py
- test/unit-tests/toctree/expected-hierarchy/toctree-doc2.conf
This extension follows the pattern seen in builders like `html` which joins lines together since content viewers not specifically fixed. Originally, this build would just pass-through newline characters into wrapped tagged storage format documents since Confluence did not care about newline characters inside. With Confluence 7, this appears to have changed (at least Confluence Cloud 1000.0.0-bc698fa60ab and Confluence Server 7.1.0-beta1 (build 11038)). To help handle this, always* strip out newline characters from the documents (* with the exception of literal blocks).
> translator: consistent line joining in confluence 7

- sphinxcontrib/confluencebuilder/translator.py
- test/unit-tests/common/expected-center/figure.conf
- test/unit-tests/common/expected/figure.conf
Documents using the figure directive will result in a "container" to help visually group the image, caption and description together. In the event where a figure has an alignment type and is very large, the image will undesirably float outside the container area. Correcting this by explicitly clearing floating elements when closing up a figure's container.
> translator: force clear on figure containers

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/exceptions.py
The configured Confluence space name is case-sensitive, which is not always emphasized to users. This may cause some confusion for initial environments where a user believed their configured environment is right but still gets a bad space error. Adding a note inside the bad-space exception to reflect this in the user's failed output (if observed) as well as put a strong emphasis in the documentation's configuration section.
> promote case-sensitive space name design

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/config.py
- sphinxcontrib/confluencebuilder/rest.py
Allow usage of a cookie for authentication to the confluence API. This
might be useful if the confluence instance is hidden behind some single-
sign-on services.
Signed-off-by: Michael Kunzmann <michael.kunzmann@gmx.net>
> Allow cookie for authentications

- sphinxcontrib/confluencebuilder/translator.py
Sphinx v2.2+ shows the following warning on every build:
`RemovedInSphinx30Warning: Translator for <class 'sphinxcontrib.confluencebuilder.translator.ConfluenceTranslator'> does not support math_block node'. Please update your extension.`
It does not seem like a problem because [the code that generates this warning](https://github.com/sphinx-doc/sphinx/blob/v2.2.0/sphinx/transforms/post_transforms/compat.py#L50) does not actually check if `math_block` is supported.
However when one does have a document that includes math, the build fails with the following error:
```
Exception occurred:
File "/usr/local/lib/python3.7/site-packages/sphinxcontrib/confluencebuilder/translator.py", line 132, in unknown_visit
raise NotImplementedError('unknown node: ' + node.__class__.__name__) …
```
> Do not fail with NotImplementedError on math_block

- doc/configuration.rst
- setup.py
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/builder.py
This option acts similarly to `confluence_ask_password` but applies to `confluence_server_user`. 
Users might want to avoid writing their username in files tracked by version control. 
This is less important than not writing passwords but still useful.
> added configuration option confluence_ask_user

- doc/configuration.rst
- setup.py
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/builder.py
This is additional changes stacked onto the #230 pull request.
Tweaks include:
- Allow a pre-configured username to act as a default username.
- Limit output when using both ask-user and ask-pass.
> completion of ask-user feature

- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/translator.py
Introduces an advanced option `confluence_adv_ignore_nodes` to allow a builder to ignore one or more specific node types. The existing `NotImplementedError` purposely exists to help notify that the running translator cannot properly process a given documentation's source; however, there may be select times where a user may not care about specific node types (i.e. nodes not specific relevant to Confluence or developing/testing support with other extension types). For these scenarios, a builder can define one or more node types inside an ignore-nodes list:
```
confluence_adv_ignore_nodes = ['nodea', 'nodeb', ...]
```
> translator: allow ignoring unknown nodes

- sphinxcontrib/confluencebuilder/config.py
- test/unit-tests/common/test_config.py
The `confluence_publish_subset` option includes a configuration check to ensure the type is of a non-string sequence type which contains string entries; however, the implementation would verify a string type by checking if the type is of `str`. This causes issues in Python 2.x since Unicode strings are not of the `str` type. Adjusting the string check to verify against a `basestring` type (with an appropriate fallback for Python 2.x interpreters).
> properly check for string type in subset configuration

- sphinxcontrib/confluencebuilder/rest.py
- test/test_validation.py
If the Confluence server to publish to returns non-JSON response (e.g. a 404 page), the build fails with an uncaught error:
```
File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
This PR changes the code handle `ValueError` (superclass of `JSONDecodeError`) to output a proper error message:
```
sphinxcontrib.confluencebuilder error:
---
An issue has been detected when trying to communicate with Confluence server.
Ensure the server is running or your Confluence server URL is valid:
https://example.com/
(details: <ProtocolError for example.com/rpc/xmlrpc: 404 Not Found>) …
```
> Output useful error message when server does not return JSON

- sphinxcontrib/confluencebuilder/translator.py
- test/unit-tests/common/dataset-common/markup.rst
- test/unit-tests/common/expected/markup.conf
- test/validation-sets/common/markup.rst
Includes support for accelerators.
Sphinx documentation: http://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-guilabel
> Add support for :guilabel: role

- sphinxcontrib/confluencebuilder/translator.py
- test/unit-tests/common/dataset-common/option-lists.rst
- test/unit-tests/common/expected/option-lists.conf
This PR wraps the first table cell of option lists (used to document arguments for CLI programs) in `<code>` so that they are displayed as monospaced text.
Arguments are wrapped in `<em>`. This is in line with how the sphinx_rtd_theme HTML theme does it, but different from stock docutils, which just uses monospace for everything.
> Wrap arguments in option list in <code>

- .travis.yml
CI builds have always been Linux-only based; however, this extension is expected to work on other operating systems. Adding a minimal set of tests for OSX and Windows environments to assist in verification.
> .travis.yml: perform various os checks

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/exceptions.py
- sphinxcontrib/confluencebuilder/rest.py
Users may require more complex authentication handlers for their respective Confluence instances. For these cases, allow a user to directly pass in an authentication handler directly to the Request's call.
This prevents the need for this extension to keep expanding on various authentication methods; leaving only the maintenance of simple authentication in this implementation.
> introduce requests auth passthrough

- sphinxcontrib/confluencebuilder/publisher.py
It has been observed by at least one user that a publishing event may result in a new-page request to provide a successful response (i.e. http code 200), but not include an identifier in the JSON-based response. To help provide more helpful information to a user for this case (instead of generating a `KeyError`).
> publisher: generate api error if new-page response has no id

- doc/markup.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/translator.py
- test/test_sandbox.py
- test/test_validation.py
- test/validation-sets/common/index.rst
- test/validation-sets/common/math.rst
This pull request provides the initial implementation to help processing math directives for Confluence publication. This extension handles this by converting math directives into images, which can be published to a Confluence instance for rendering. These changes follow closely to how `sphinx.ext.imgmath` operates.
Note that for a user to take advantage of math directives, they will need to install LaTeX and either dvipng or dvisvgm to properly generate images; otherwise math directives will be ignored.
> introduce math support

- AUTHORS
- sphinxcontrib/confluencebuilder/builder.py
- test/unit-tests/common/dataset-image-star/index.rst
- test/unit-tests/common/expected-image-star/index.conf
- test/unit-tests/common/test_image_star.py
**Some context:**
I was trying to include plots generated by matplotlib.sphinext when using the confluence builder. Then I learned that plots were properly generated and the only problem was the matplotlib.sphinext extension was not considering confluence as a possible builder.
Therefore, I created this PR (https://github.com/matplotlib/matplotlib/pull/14681) there, to ask them to include it. Eventually, this was addressed in other PR (https://github.com/matplotlib/matplotlib/pull/14683) which enhance the same but in a more general way. Now, builders which want to include plots from matplotlibs should handle images ending with star. 
And handling image with star is the goal of this PR. I have added the parameter **supported_image_types** to the builder like here:  [sphinx builders …
> Add image files ending with star (*) instead of specifying the format

- test/sphinxcontrib_confluencebuilder_util.py
When under a test environment, there is not a gracefully way to enable Sphinx's verbosity flag -- primarily since we explicitly prepare Sphinx instances ourselves in tests and do not set the verbosity flag. Typically, a verbose Sphinx engine is not really required except for advanced cases. To test development/testers to easily enable this option (when using this repository's test options), allow them to enable verbosity by setting the `SPHINX_VERBOSITY` option. For example:
$ SPHINX_VERBOSITY=2 tox -e sandbox
> test: enable verbosity environment variable

- .travis.yml
Adjust OSX builds to use specific images to ensure which Python revision is available to test against.
> .travis.yml: use specific osx images for specific python versions

- .travis.yml
- sphinxcontrib/confluencebuilder/__init__.py
- tox.ini
Adding testing for Sphinx v2.3.x series.
Since this extension aims to provides support for five Sphinx major releases, Sphinx v1.7 is now marked as deprecated for the next stable release.
> handle new sphinx major

- sphinxcontrib/confluencebuilder/translator.py
- test/unit-tests/common/dataset-domains/c.rst
- test/unit-tests/common/dataset-domains/cpp.rst
- test/unit-tests/common/dataset-domains/js.rst
- test/unit-tests/common/dataset-domains/py.rst
- test/unit-tests/common/dataset-domains/rst.rst
- test/unit-tests/common/expected-domains/c.conf
- test/unit-tests/common/expected-domains/cpp.conf
- test/unit-tests/common/expected-domains/js.conf
- test/unit-tests/common/expected-domains/py.conf
- test/unit-tests/common/expected-domains/rst.conf
- test/unit-tests/common/test_domains.py
- test/unit-tests/toctree/dataset-hidden/index.rst
- test/unit-tests/toctree/dataset-hidden/page.rst
- test/unit-tests/toctree/expected-hidden/index.conf
- test/unit-tests/toctree/test_toctree.py
_(this pull request is based off of key changes from #219)_
This pull request is starts off with a cherry-pick of @jjcaballero's implementation for `visit_toctree` and `visit_desc_signature_line`-related calls. The goal is to introduce these key fixes in the upcoming stable release but it was decided that these changes were pulled from #219 as that pull request contains some additional examples/checks which need more consideration before migrating into `master` (see the pull request for more information).
There is one notable tweak to the description signature processing which prevents nested `dt` tags from being generated in multiline signature events.
This change introduced a more minimized set of unit testing for the hidden toctree and domains-related implementation. Note that the …
> adding missing hidden toctree and desc calls

- sphinxcontrib/confluencebuilder/translator.py
- test/unit-tests/common/test_domains.py
Adjust anchor generation for descriptions to build off signature entries instead of relying on a description's name node. For descriptions with one or more signature lines, any assigned identifier on a signature will be placed in the leading portion of the first term entry.
This should address concerns outlined in #146.
> translator: build anchors on desc sigs

- CHANGES.rst
- doc/conf.py
- doc/configuration.rst
- doc/markup.rst
- sphinxcontrib/confluencebuilder/__init__.py
Performing a series of maintenance changes in preparation for an upcoming release:
- doc: cleanup configuration document
- doc: recatagorize configuration options
- \_\_init\_\_: recategorize configuration options
- doc: remove toctree numbered option from pending
- doc: bumping copyright year
> maintenance -- 2020-01-01

- sphinxcontrib/confluencebuilder/translator.py
- test/validation-sets/auto-ext/index.rst
For target nodes which have non-reference identifiers, generate an anchor macro (if supported) to help internally referenced and externally referenced identifiers.
This changes helps ensure references generated from autosummary directive have a proper target to jump to.
> generate anchors for targets

- sphinxcontrib/confluencebuilder/rest.py
If a `None` value password (typically, a representation of no password needed) into an empty string. This is to help prepare for future Requests versions which desire a string/bytes value. This removes the following warning on newer versions of Requests (for non-password user scenarios):
DeprecationWarning: Non-string passwords will no longer be supported in Requests 3.0.0. Please convert the object you've passed in (None) to a string or bytes object in the near future to avoid problems.
> rest: convert none-password value to an empty string

- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/translator.py
A node handler allows an advanced user to provide implementation to process a node not supported by this extension. This is to assist in providing a quick alternative to supporting another third party extension in this translator (without having to take the time in building a third extension).
> translator: allow users to override unknown nodes

- sphinxcontrib/confluencebuilder/builder.py
A series of `input` calls were introduced (to support ask-user/password features); however, the use of `input` does not work under Python 2.7. Adjusting imports to help use `raw_input` instead.
> builder: ensure input calls support python 2.7

- sphinxcontrib/confluencebuilder/std/confluence.py
- sphinxcontrib/confluencebuilder/translator.py
By default, an unspecified coding language will default to python (based off of Sphinx's choice of default language). In the event where an unsupported language for Confluence is provided to this extension (since Confluence will not be able to render it), this extension would fallback on a default language. This is unexpected since something like `shell-session` would translate to `python`. Instead, all unknown language types will be translated to `none`.
> translator: default unknown code language to none

- sphinxcontrib/confluencebuilder/translator.py
- test/unit-tests/common/dataset-common/contents-ref.rst
- test/unit-tests/common/dataset-common/contents.rst
- test/unit-tests/common/expected/contents.conf
- test/unit-tests/common/test_common.py
Reference management assumed that nested references were not possible; however, it has been observed in select scenarios (such as a toctree referencing a header which also is a reference to another page) that this is not always the case. Instead of asserting on such a scenario, ignore a nested reference instead -- this extension will prioritize the initial reference.
Note that this is a slight variation to what Sphinx (v2.2.0, at time of testing) does for a documentation set applied to the HTML builder. It has been observed that a `:local`: table of contents will generate a reference directly to the content instead of the subsection of the current document. It is assumed that this is not expected, thus this extension will follow reStructuredText's wording which the local table of contents …
> translator: ignore nested references

- sphinxcontrib/confluencebuilder/builder.py
If a configuration is not configured to publish content, do not attempt to ask a user for either a username or password to publish with (if the respective features are enabled).
> builder: do not prompt for username/password when not publishing

- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/translator.py
- sphinxcontrib/confluencebuilder/util.py
When using the most recent Docutils, the following message is generated:
```
FutureWarning:
The iterable returned by Node.traverse()
will become an iterator instead of a list in Docutils > 0.16.
```
Adjusting a series of index-fetched "first" element calls to use a new `first` utility method to deal with various iterable types.
> prepare for docutils iterable-returned traverse

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/config.py
- sphinxcontrib/confluencebuilder/translator.py
- test/unit-tests/common/dataset-alignment/index.rst
- test/unit-tests/common/dataset-common/figure.rst
- test/unit-tests/common/expected-center/figure.conf
- test/unit-tests/common/expected/alignment-center.conf
- test/unit-tests/common/expected/alignment-left.conf
- test/unit-tests/common/expected/alignment-right.conf
- test/unit-tests/common/expected/figure.conf
- test/unit-tests/common/test_alignment.py
First, this pull request corrects an issue with a figure's legend alignment. When a figure is assigned an alignment type, it is expected that the caption and legend contents also follows the same alignment type (based off observed Sphinx stock builders). This commit adjusts the built legend to be a div element with the respective text alignment value assigned to a parent figure (if any is set).
Second, introducing a new configuration option `confluence_default_alignment` to allow users to override the default alignment value applied. If a user wishes to use legacy alignment style, the following may be used:
```
confluence_default_alignment = 'left'
```
Note that the default alignment value will only be used when a `default` alignment hint is provided in Sphinx, which only exists in Sphinx …
> alignment improvements for figures

- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/translator.py
Performs two changes with respect to previous-next navigation buttons.
First, the original navigation implementation would compile a list of previous and next documents for the determined order of documents; however, the references compiled did not properly take into account the relative URL between the respective documents. Adjusting the caching to use the builder's `get_relative_uri` call when forming this information.
Second, tweaks the "Previous" and "Next" buttons on pages to have better visualization. Links are now styled through a Confluence-defined button class (`aui-button`). Buttons are also pushed to left and right sides (respectively) in a similar design approach seen in stock builders.
> previous-next improvements

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/publisher.py
When this extension takes advantage of creating new documents or editing existing documents through the publishing feature, pages will be automatically watched by the publishing user. This is not typically ideal for documentation sets which may be published automatically (e.g. pages purged and edited using multiple users can generate multiple Emails in a publish event).
This commit adjusts the default watch state for pages to unwatched. Publishers can override this by setting `confluence_watch` to a value of `True` to always watch the state of published documents.
> publisher: ability to control watch state

- doc/configuration.rst
- doc/tips.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/publisher.py
When publishing, a user may be curious to observe what this extension maybe modified on a target Confluence instance. With the dry run feature (e.g. adding a command line option
`-Dconfluence_dryrun=1`), this extension will log where pages will be published and other changes without actually performing the actions.
> publisher: allow a user to dry run a publish event

- doc/configuration.rst
- doc/tips.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/config.py
This extension will pull the content for the first detected title element as the title value to use for a Confluence page. This detection may not always be the ideal choice for select documentation sets. In a scenario where a user cannot or does not watch to explicitly adjust a document for a title entry, they may opt to use an override option to explicitly configure the builder to use a title value for a given document. For example, if a user wishes to override the title value for the `index` page, the following configuration can be used:
```
confluence_title_overrides = {
'index': 'Index Override',
}
```
> builder: allow title overrides

- sphinxcontrib/confluencebuilder/std/confluence.py
Adding a series of Pygments-listed language types not added for supported Confluence (legacy) code macros.
> std: extend mapped languages

- sphinxcontrib/confluencebuilder/translator.py
When a document defines an `include` directive \[1\] with the `literal` option set, the extension would process it in a similar manner as a Sphinx `literalinclude`; which is incorrect. Adjusting the literal block check to treat literal-marked includes as code-like blocks (wrapped with CDATA) with no language type.
\[1\]: https://docutils.sourceforge.io/docs/ref/rst/directives.html#including-an-external-document-fragment
> translator: support literal-marked include

- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/state.py
Original title management would compile title entries and warn the publishing user of any title conflicts, but this extension did not do anything more than that. This can become an annoyance for large documentation sets where titles may be conflicting but a publisher is not that picky on the generated title values. Also, this may cause confusion on publication when select publish events may fail when publishing a child/nested page with a parent holding the original ownership of the title (API error when mapping a page identifier with itself as an ancestor).
Instead, along with warning a user of a title conflict between documents, this extension will append an incrementing numerical value to titles to allow a publishing event to progress without issue.
Note that for users who may publish …
> state: automatic unique title names

- sphinxcontrib/confluencebuilder/translator.py
- test/unit-tests/common/dataset-common/image.rst
- test/unit-tests/common/expected/image.conf
- test/validation-sets/common/images.rst
This PR adds support for the `:scale:` parameter for images. It is similar to what Sphinx 2.4+ does (https://github.com/sphinx-doc/sphinx/pull/6985) and similarly needs imagesize 1.2.0+ to support scaling SVG.
> Support :scale: parameter for images

- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/translator.py
- test/unit-tests/single-page/dataset-numbered/index.rst
- test/unit-tests/single-page/dataset-numbered/page-a.rst
- test/unit-tests/single-page/dataset-numbered/page-b.rst
- test/unit-tests/single-page/expected-numbered/index.conf
- test/unit-tests/single-page/test_singlepage.py
Numbering of sections (with `:numbered:` toctree) does not work in singleconfluence builder because the internal ids are renamed during toctree inlining to prevent collisions.
This PR adds code to `add_secnumber` for singleconfluence builder to correctly handle the renamed section numbers, in the same way that singlehtml builder does.
> Fix section numbering in singleconfluence builder

- sphinxcontrib/confluencebuilder/rest.py
Define a user agent string for all request calls generated by this extension. This is solely to help prevent issues observed in CONFCLOUD-69720 \[1\] (while should already be resolved on Confluence Cloud).
\[1\]: https://jira.atlassian.com/browse/CONFCLOUD-69720
> rest: define user agent for request calls

- sphinxcontrib/confluencebuilder/__init__.py
For the standard builder in this extension, the `doctree-resolved` event is observed to help populate images which may be generated when a doctree has been resolved. When the single builder was introduced in this extension, the builder attribute (`app.builder`) no longer appears to be always initialized. Before type-checking the builder being used, hook on the `builder-inited` event to ensure the builder has been initialized.
> correct hook with multiple builders

- sphinxcontrib/confluencebuilder/assets.py
- sphinxcontrib/confluencebuilder/builder.py
Asset-based nodes processed by this extension will either provide a URI to a relative or absolute path. Part of the asset manager's process will attempt to determine the absolute path of a resource for future work. In the case for a relative path, a relative path is assumed to be located alongside the source content; however, this is not always the case for extensions which generate assets into the build output directory but only provide a relative path to the asset. To help deal with this case, when a relative path based off a documentation's source directory cannot be found, the process will fallback to a path based off the user-defined output directory.
> assets: provided fallback for asset paths

- .travis.yml
- test/unit-tests/common/expected-domains-legacy/c.conf
- test/unit-tests/common/expected-domains/c.conf
- test/unit-tests/common/test_domains.py
- tox.ini
Adjusting the tox/Travis CI configuration to test for the more recent releases of Sphinx. Since this extension aims to support a least five latest releases of Sphinx, dropping tests for some older versions. 
Note that Sphinx v1.8.x series will still be tested against since it is the only version still supported on Python 2, which will continue to have support for at least a couple of more months.
> test additional sphinx versions

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/publisher.py
Adding a new feature which allows users to configure this extension to restrict changing existing content on a Confluence space. When `confluence_publish_onlynew` is set to `True`, only new pages/attachments can be added to a target space.
> publisher: introduce the only-new feature

- sphinxcontrib/confluencebuilder/translator/storage.py
- test/unit-tests/common/expected-center/figure.conf
- test/unit-tests/common/expected/figure.conf
- test/unit-tests/common/expected/image.conf
It has been observed that (in at least) Confluence Cloud that when a newline is injected in the `ri:attachment` tag, typically only when `ri:content-title` is used, that Confluence will report a 500 error when publishing. This commit removes the suffix injection (from an explicit newline to an implicit empty/none) and publish events appear to work as expected.
See also #317.
> storage: do not inject newline inside attachment tag

- doc/markup.rst
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/singlebuilder.py
Provide support for an internal Sphinx extension `inheritance_diagram` by pre-processing diagrams and replaced with respective images. Typically, node support from `sphinx.ext.inheritance_diagram` would be added to the builder; however, this extension renders graphs during the translation phase (which is not ideal for how assets are managed in this extension).
Instead, this implementation just traverses for inheritance diagrams, generates renderings and replaces the nodes with image nodes (which in turn will be handled by the existing image-based implementation).
This pull request also refactors some shared implementation between the standard builder and the single builder. These calls are responsible for manipulating a prepared doctree instance before processing -- such as replacing math …
> builder: handle sphinx.ext.inheritance_diagram nodes

- sphinxcontrib/confluencebuilder/translator/storage.py
When processing each text node's contents, newlines are stripped to ensure horizontal view is taken advantage of. This does not apply to parsed literals which expect a matching format. The split of translator implementation introduces an issue where it would set an internal "is-parser-literal" flag when the processing nodes were not actually a parsed literal type; correcting.
> storage: correct literal parsing newlines

- setup.cfg
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/config.py
- tox.ini
Moving all existing flake8 ignore entries from the `tox.ini` configuration into `setup.cfg`. This allows an easier way to maintain a set of ignore entries (line per ignore versus a full line) as well as allows users to invoke `flake8` with project-configuration settings without having to rely on invoking tox (if desired).
> moving flake8 ignores into setup.cfg

- README.rst
Just updating the link to the tests.
> 📚 Fix typo in README.

- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/translator/storage.py
- tests/unit-tests/common/expected/index.conf
When using restructuredText's table of contents directive (`contents`), the reference to the leading section page was always removed when the first section (the "title") was removed (by default) from a document. This was to prevent generating an entry point in the TOC which would not have a proper link target to reference. This causes two issues:
1) This extension would modify a possible expected output to have an anchor link to the top of a document.
2) If a table of contents had multiple child entries to display, the output would generate a nested list category for a "removed" root which would produce an empty/undesired bullet point.
Instead, this commit introduces support for the reference missing the target by detecting that a reference is now a "#top" reference in the builder. This …
> support leading title link support from toc directive

- sphinxcontrib/confluencebuilder/translator/__init__.py
- sphinxcontrib/confluencebuilder/translator/storage.py
- tests/unit-tests/common/dataset-common/raw.rst
- tests/validation-sets/common/download.rst
- tests/validation-sets/common/images.rst
- tests/validation-sets/common/references-ref.rst
- tests/validation-sets/common/references.rst
Adjusting the storage format translate to use the `confluence_storage` format identifier over the `confluence` format type. This is to help prepare for ADF support which we want a more explicit identification between a Confluence storage-format-specific format over other possible supported formats.
> storage: support new raw format

- tests/test_sandbox.py
A developer may have multiple sandbox environments being tested, which requiring renaming a sandbox container when toggling between multiple. Instead, provide the flexibility for a developer to pass in a specific sandbox environment they want from the command line.
> test: support custom sandbox locations

- doc/configuration.rst
Requests documentation is now found under the "requests.readthedocs.io" domain (instead of under a "*.python-requests.org" domain). Adjusting to the new domains and point to the stable variant of the respective documentation sections.
> Documentation: update requests-related documentation links

- tests/lib/__init__.py
Various testing uses a `prepareDirectories` call to provide an interim "doc_dir" and "doctree_dir" locations for Sphinx processing. When this and other utility calls were moving into a lib namespace, directory building broke since its assumption of the base folder ("tests") was the same location as the helper call.
This commit corrects the utility call by taking into consideration of the recently added `lib` directory.
> test: correct output container

- tests/validation-sets/auto-ext/autodocs.rst
- tests/validation-sets/base/index.rst
**validation: prevent duplicate objects in autodocs example**
When processing the autodocs example, an undesired duplicate object description for the `Hello` class and method examples is set. This results in a warning message as follows:
```
sphinx.errors.SphinxWarning: ./tests/validation-sets/auto-ext/autodocs.rst:22:duplicate object description of Hello.Hello.foo, other instance in autodocs, use :noindex: for one of them
```
To remove this warning, adding the `:noindex:` option to calls which re-use the `Hello` module more than once in a document.
**validation: switch raw type identifier**
Switching from the deprecated `confluence` raw format type to the newly added `confluence_storage` type.
> cleanup validation warnings

- sphinxcontrib/confluencebuilder/builder.py
After publishing a documentation set, provide a helper link to the main document on the Confluence instance.
> builder: print publish point after publishing

- sphinxcontrib/confluencebuilder/translator/storage.py
In select cases, it has been observed that a reference node may contain a `refuri` definition which contains an anchor to the active document being processed. The existing implementation would only be able to handle this case if the reference was also not marked as internal; however, it has been observed that in select cases (such as using the `sphinx.ext.todo` extension) that local anchor entries can also be on references which have an internal flag set.
This commit re-works the process `refuri` process flow by:
1) Always checking for an local anchor reference to forward to to the internal identifier-based reference implementation (the fix).
2) If not internal, continue to forward it to the external reference     implementation.
3) Otherwise, process it as an internal URI.
> storage: handle anchor-specific targets flagged as internal

- tests/lib/__init__.py
- tests/test_sandbox.py
In select development cases, there is a desire to pass in custom defines on the command line when invoking a specific sandbox test. This commit adds a `-D` argument (to match Sphinx's `-D` argument) which can be used to extend a local sandbox's existing configuration file.
> test: allow passing defines in a sandbox environment

- tox.ini
A previous commit made some changes to the flake8 usage \[1\] to ensure the linter was invoked correctly. With this change, the tox environment name was changed from `lint` to `flake8`; however, the default environment list was not updated as well. This commit corrects this.
\[1\]: 1a73ce8223c25a5816e1a153c7dfbba17a96bfdc
> tox: ensure flake8 runs by default

- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/singlebuilder.py
- sphinxcontrib/confluencebuilder/translator/storage.py
- tests/unit-tests/single-page/dataset-contents-numbered/index.rst
- tests/unit-tests/single-page/dataset-contents-numbered/sub.rst
- tests/unit-tests/single-page/dataset-contents/index.rst
- tests/unit-tests/single-page/dataset-contents/sub.rst
- tests/unit-tests/single-page/expected-numbered/index.conf
- tests/unit-tests/single-page/test_singlepage.py
- tests/unit-tests/toctree/dataset-contents/index.rst
- tests/unit-tests/toctree/dataset-contents/sub.rst
- tests/unit-tests/toctree/expected-numbered-default/index.conf
- tests/unit-tests/toctree/expected-numbered-depth/index.conf
- tests/unit-tests/toctree/expected-numbered-suffix/index.conf
- tests/unit-tests/toctree/test_toctree.py
The following provides a more complete for section numbering support when used with this extension. This extension's builders never built proper targets for sections to reference against. Section names identifiers are internally managed by the Confluence instance and the target mappings never took into consideration of a section with a prefixed section number. Cached target entries will now handle when a section number is added to a section text.
In addition, the `singleconfluence` builder required implementing its own title cache list, as the section targets need to be compiled after assembling the section numbers, but before the primary doctree is built. This is a result of pre-merged doctree's which will point to page-specific targets (e.g. `sub/#target`) but the original …
> improve support for section/figure numbering

- sphinxcontrib/confluencebuilder/__init__.py
This extension would attempt to register compatible autosummary nodes when the `sphinx.ext.autosummary` extension was loaded. This would allow a user to take advantage of the autosummary capabilities with this extension.
The problem with the check on `app.config.extensions` is that that configuration file only indicates extensions the user wishes to explicitly load, and not what extensions have been actually loaded into the Sphinx engine.
The injection process has been changed to better handle autosummary support:
1) Explicitly check against the `app.extensions` loaded extensions to determine if the nodes should be injected.
2) Only attempt to inject after the `builder-inited` event to ensure that modules loaded after the Confluence builder extension which may load …
> inject autosummary nodes after a proper extension check

- doc/markup.rst
- sphinxcontrib/confluencebuilder/builder.py
This commit introduces the initial support for graphviz graphs. The implementation mimics the same implementation used to support inheritance diagrams \[1\], where graphviz nodes are converted into image nodes before being processed by a translator.
With the example documentation:
```
.. graphviz::
digraph foo {
"bar" -> "baz";
}
.. graph:: foo
"bar" -- "baz";
.. digraph:: foo
"bar" -> "baz" -> "quux";
```
A final output renders as follows:
> ![image](https://user-images.githubusercontent.com/1834509/100682863-02f06100-3345-11eb-8761-991290f0e50d.png)
\[1\]: 01f97a67b98d598a6f5a542869f8542d08fd931b
> initial support for graphviz graphs

- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/state.py
- sphinxcontrib/confluencebuilder/translator/storage.py
This extension includes a requirement that in order for a document to be published to a Confluence instance, a title value must be determined for a given document in order to know where to publish a document's contents. While there have been changes in this extension over time to auto-generated a title or provide a user's option to configure title mappings, there are configuration states which can still result in a processed document to not have a title value (and will be ignored during the publishing phase).
A problem that exists with the initial implementation is that if a document is detected to not being able to be published, it would stop pre-processing these documents immediately. While this can be valid for some pre-processor actions, skipping all the pre-processor actions can …
> improve handling of titleless documents

- sphinxcontrib/confluencebuilder/exceptions.py
- sphinxcontrib/confluencebuilder/publisher.py
This commit introduces a new exception type `ConfluenceUnreconciledPageError` to help provide users a more detailed description when they experience publishing a page which Confluence reports is unreconciled.
This is a result of a Confluence issue observed between a 7.0 release and a 7.3.2 release where a Confluence upgrade can result in unreconciled pages (unknown if recent micro version of 7.0.x, 7.1.x or 7.2.x have ported a hotfix for this). More details can be found in CONFSERVER-59196 \[1\] (thanks Nicholas Bollweg for reporting this; see #314).
A workaround to this issue is to have a user refresh an unreconciled page, which is not* possible from this extension (*since we limit configurations to use API credentials and the request needs to happen outside the API endpoint). This …
> warn about unreconciled pages

- sphinxcontrib/confluencebuilder/builder.py
This extension originally supported the use of inheritance diagrams via the `sphinx.ext.inheritance_diagram` extension, and later on supported more graph capabilities via the `sphinx.ext.graphviz` extension. Both extensions are handled in the builder which the respective nodes are converted into images to be included on a Confluence page. When introducing support for graphviz, inheritance_diagram support broke; this is a result of the replacement of `graphviz` nodes inside `inheritance_diagram` nodes.
To correct this issue, `inheritance_diagram` nodes will be always replaced before attempting to replace `graphviz` nodes. With this change, the use of either extension in a documentation set will work as expected.
> build: support both graphviz and inheritance-diagram

- sphinxcontrib/confluencebuilder/translator/storage.py
While this extension attempts to support todo entries provided by the `sphinx.ext.todo` extension, these entries should not be rendered in a document unless the configuration `todo_include_todos` is configured to `True`. However, the initial implementation for todo support would always render these entries. This commit corrects this by explicitly checking the option before processing a todo node.
> storage: only render todo when configured

- sphinxcontrib/confluencebuilder/translator/storage.py
When a table is created, no width hints are provided to the markup. This allows Confluence to attempt to manage these tables in a flexible manner. However, reStructuredText does provide a `widths` option for tables which a user may wish to take advantage of. Since Confluence does allow width style events to be applied in storage format, attempt to take advantage of this to help better space columns based off the hints provided in a documentation's source.
> storage: support width options in tables

- sphinxcontrib/confluencebuilder/builder.py
Initial support for `sphinx.ext.graphviz` extension capabilities would force use a `png` format for all generated images. Users may wish to use an alternative output type through the `graphviz_output_format` configuration option; enabling support for this.
> build: support user configuring graphviz output type

- sphinxcontrib/confluencebuilder/translator/__init__.py
- sphinxcontrib/confluencebuilder/translator/storage.py
While `centered` is a deprecated directive, there may be a chance that a legacy documentation set is still using it. To help be more flexible for these documentation sets, emulate the expected output for when using this directive.
> storage: introduce support for the centered directive

- sphinxcontrib/confluencebuilder/translator/__init__.py
- sphinxcontrib/confluencebuilder/translator/storage.py
The hlist was never initially supported since it was assumed that the rendering/style requirements would not be possible on a Confluence instance. After addition investigation, it turns out that is not true (and support is not that complex).
> storage: introduce support for hlist

- sphinxcontrib/confluencebuilder/translator/storage.py
Confluence's storage format supports the `title` attribute in `a` tags. Take advantage of this by adding the attribute when a reference node has `reftitle` defined.
> support link titles

- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/intersphinx.py
The following adds initial support for generating an inventory file to be used by the `sphinx.ext.intersphinx` extension. This initial release will build document and various references (e.g. titles) inside an inventory file.
This file is only built when publishing occurs, as it is the only time it will know the specific page identifiers to build links for targets.
> initial intersphinx support

- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/intersphinx.py
- tests/lib/__init__.py
- tox.ini
This is a generic maintenance effort to help cleanup a series of issues observed and other desired cleanup actions before attempting to do release testing. This request includes the following changes (where individual commit messages provide more details):
- builder: do not fold various info lines
- builder: generate a proper publish point
- builder: simplify info logging
- intersphinx: generate proper uri based off cloud/server instance
- intersphinx: support python 2.7
- test: only force index root document for older versions
- tox: cleanup tox configuration
- tox: explicit interpreter invoke
- tox: provide additional interpreter env for validation testing
> maintenance 2020-12-09

- tox.ini
With changes \[1\] to tox's environment list to support specific Python interpreters in a validation test, the previous change now prevents the flexibility of a developer wanting to do a validation test without caring which interpreter is being used:
tox -e validation
This commit restores the ability to run the above command.
\[1\]: 74095765382851975d3a06a5467b919752db2e65
> tox: allow generic validation environment

- .github/workflows/build.yml
When porting over to GitHub actions, the linter checks were accidentally excluded from the original set of configurations to run; correcting.
> workflows: ensure linters are run

- sphinxcontrib/confluencebuilder/translator/storage.py
While the `:download:` role helps users link to a non-reST documents, it can sometimes be used to build a link to a target (observed in the `html` builder). The original implementation for `visit_download_reference` built the link, but never properly closed the tags (the node was skipped instead of processing inwards and eventually departing); this commit corrects.
In addition, when a user uses a `:download:` role in the `html` builder to build a reference link, the link is strong’ed. Mimic the same display style when building the same type of reference.
> storage: properly build reftarget download roles

- sphinxcontrib/confluencebuilder/publisher.py
A previous commit \[1\] introduced a user error message to help deal with a Confluence reported unreconciled page scenario. However, the conditional check added did not properly check the return value; correcting.
\[1\]: 86fd30ec12c7a15158df0a1b2e79ae8bd675eb48
> publisher: correct unreconciled check

- sphinxcontrib/confluencebuilder/translator/storage.py
When a definition inside a definition includes a term, the implementation will flag the detection of a term to ensure required closing flags are populated (as it attempts to process one or more terms). However, in the event that a following definition entry does not have a term defined, it will improperly try to pop a non-existent `dt` tag. Correct this by unmarking the has-term flag after closing the previously open term tag.
> storage: only inject trailing dt tag for last term

- sphinxcontrib/confluencebuilder/translator/storage.py
Typically, when a reference for a document is found pointing to another document in the same project, an `internal` flag is set. This is used in the reference processing to build a macro link to another page in Confluence. It has recently been observed that some extensions also build internal document references with a `refdocname` value specified. This commit tweaks the reference building operation by accepting either the `internal` flag or `refdocname` attribute as an indication that the reference is an internal link, and build accordingly.
> handle internal document references with refdocname set

- sphinxcontrib/confluencebuilder/assets.py
- sphinxcontrib/confluencebuilder/translator/storage.py
While many checks exist to help determine a resource's path, there can be times where a resource may be unavailable. For example, if an extension prepares image nodes with paths that do not immediately exist (e.g. if it assumes that something else will provide them, or the external extension is experiencing an issue), the node will still need to be processed by this extension. If the event that a post-build reftarget/uri points to an unknown asset, generate a warning message and skip the node (instead of hard failing).
> handle missing images

- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/directives.py
- sphinxcontrib/confluencebuilder/nodes.py
- sphinxcontrib/confluencebuilder/translator/storage.py
Introduces support for Confluence's "Expand" macro \[1\].
\[1\]: https://confluence.atlassian.com/doc/expand-macro-223222352.html
> support expand macro

- sphinxcontrib/__init__.py
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/__main__.py
- sphinxcontrib/confluencebuilder/assets.py
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/compat.py
- sphinxcontrib/confluencebuilder/config.py
- sphinxcontrib/confluencebuilder/directives.py
- sphinxcontrib/confluencebuilder/exceptions.py
- sphinxcontrib/confluencebuilder/logger.py
- sphinxcontrib/confluencebuilder/publisher.py
- sphinxcontrib/confluencebuilder/rest.py
- sphinxcontrib/confluencebuilder/singlebuilder.py
- sphinxcontrib/confluencebuilder/state.py
- sphinxcontrib/confluencebuilder/std/__init__.py
- sphinxcontrib/confluencebuilder/std/confluence.py
- sphinxcontrib/confluencebuilder/std/sphinx.py
- sphinxcontrib/confluencebuilder/util.py
- sphinxcontrib/confluencebuilder/writer.py
Adjust all relative based imports into absolute imports to use a consistent importing style across all implementation files. This change also tweaks the respective copyright statements to be consistent as well.
> cleanup imports/copyright statements for consistency

- .gitignore
- sandbox/.gitignore
- sandbox/README.rst
- tests/.gitignore
- tests/lib/__init__.py
- tests/test_sandbox.py
Builds and tox generated output is typically stored inside a developer's root repository directory. Some testing output (e.g. Sphinx generated output in unit testing) is stored in temporary folders found inside the `tests` folder. It may be ideal to have a consistent location for intermediate folders/files, in the base directory, to:
- Avoid the need to navigate into the tests folder when constantly inspecting output.
- When manually inspecting the repository, knowing that only intermediate files will be found in the root.
> consistent intermediate files base folder

- .gitignore
- sphinxcontrib/confluencebuilder/builder.py
- tests/test_sandbox.py
This is a generic maintenance effort to help cleanup a series of issues observed and other desired cleanup actions before attempting to do release testing. This request includes the following changes (where individual commit messages provide more details):
- .gitignore: ignore _build folder
- builder: set a more specific format
- tests: different output directories for unique sandbox builders
> maintenance 2020-12-13

- .github/workflows/validate.yml
- tests/test_validation.py
Adding a series of options to the validator action, which include the target space name, the root page's name and the description value used on the root page.
> validator: add more target options for validator

- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/config.py
- sphinxcontrib/confluencebuilder/util.py
- tests/unit-tests/common/assets/sample-invalid-publish-list
- tests/unit-tests/common/assets/sample-valid-publish-list
- tests/unit-tests/common/test_config.py
This commit introduces the ability for a user to create a list of documents to not publish. This is to compliment the existing `confluence_publish_subset` configuration, where users may wish to define a list of documents not to publish, over documents to publish.
This commit also reworks the original `confluence_publish_subset` configuration to be renamed to `confluence_publish_allowlist`. The older configuration name is still supported for an interim.
For both configurations, aside from a collection of documents to register for an option, these options now also support accepting a filename (string instead of a list), which may hold a list of documents to apply to the configuration.
> introduce publish denylist

- CHANGES.rst
- CONTRIBUTING.rst
- LICENSE
- MAINTAINERS.rst
A series of documents found in the root of the document have been reviewed/updated in preparation for a planned upcoming release (#362). This includes the following changes, with more details outlined in the individual commit messages:
- CONTRIBUTING.rst: cleanup document
- LICENSE: update most recent license state
- MAINTAINERS.rst: cleanup document
> pre-release document maintenance

- sphinxcontrib/confluencebuilder/builder.py
In the event where a document entry only contains a title reference and is removed via the `confluence_remove_title` option, the resulting page will be empty. While this should be fine, the existing builder implementation would not generate an output document which was empty. This would leave to an error such as the following:
WARNING: error reading file<filename>.conf: [Errno 2] No such file or directory: ...
If a documentation set has an empty page, this extension should still be creating/publishing it. Correcting this in the builder to write content if even an empty string is set.
> builder: write empty pages

- sphinxcontrib/confluencebuilder/translator/storage.py
- tests/unit-tests/common/dataset-common/list-table.rst
- tests/unit-tests/common/expected/list-table.conf
- tests/validation-sets/standard/lists.rst
implements #341 (accidentally closed); pasting some of original issue summary for clarity:
- implemented support for `:stub-columns:` option in `.. list-table::` directives
- updated tests
- currently using in production instance running confuence 7.6.0
feedback implemented:
- removed experimental flag (https://github.com/sphinx-contrib/confluencebuilder/pull/341#discussion_r531221837)
- removed comments; added link to ref implementation to commit msg (https://github.com/sphinx-contrib/confluencebuilder/pull/341#discussion_r531226811)
- moved `node.parent.column += 1` outside of `if` block (https://github.com/sphinx-contrib/confluencebuilder/pull/341#discussion_r531227401)
@jdknight please take a look; thank you!
> implements stub columns (re-do of #341)

- sphinxcontrib/confluencebuilder/config/checks.py
- sphinxcontrib/confluencebuilder/config/defaults.py
- sphinxcontrib/confluencebuilder/config/validation.py
- sphinxcontrib/confluencebuilder/util.py
- tests/unit-tests/test_config_checks.py
Provides the ability to check and be flexible with boolean/integer configuration values for this extension. This pull request includes:
- config: sanity check boolean options
- config: permit string values for booleans/integers (for command line)
- config: handle empty strings as unset cases
> improve configuration check for booleans/integers

- sphinxcontrib/confluencebuilder/translator/__init__.py
When a document defines a reStructuredText's `meta` directive, ignore the node type to prevent a translation failure.
> translator: ignore meta nodes

- sphinxcontrib/confluencebuilder/translator/__init__.py
Handle when a documentation uses a `:numref:` role to generate a numerical reference. This, by default, which will forward the responsibility to the existing reference implementation (a pattern observed in the HTML builder).
> translator: support number references

- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/translator/storage.py
This pull request improves how it handles various math nodes. Specifically, this includes two changes:
1. Properly handles wrapping for displaymath nodes where equations with more than one line would result in a LaTeX error.
2. Support adding label entries for nodes (which assign a label and are referenced via `:math:numref:`).
> math improvements

- doc/tips.rst
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/singlebuilder.py
- sphinxcontrib/confluencebuilder/translator/storage.py
- tests/test_validation.py
- tests/validation-sets/standard/math.rst
When a configuration sets `imgmath_use_preview`, the math rendering request will provide a depth offset which can be used to apply around math images for improved visual alignment. When a depth is generated from `render_math`, track this depth into the newly created image node.
For storage format, when an image is assigned with a math-depth value, include a span wrapper with a vertical alignment offset set.
When building both references to equations and equation labels, an invoke with a `singleconfluence` builder can result in the builder failing. This is a combination of the following:
- This extension pre-populates TOC figure/section numbers to help build a desired list of '<docname>/<id>' mappings for various nodes. However, by doing this stage early, references targeting equations …
> additional math support for depth/numfigs

- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/builder.py
Sphinx defines the translators to be used for builders via a `default_translator_class` class attribute. Instead of using `add_translator` on the Sphinx registry, use the class attribute instead.
> define builder type via class attribute

- sphinxcontrib/confluencebuilder/intersphinx.py
For Python 2.7, attempting to pass a raw anchor value for quoting into requests can result in an encoding exception. To prevent an encoding failure when attempting to quote the desired anchor value, ensure it is UTF-8 encoded first.
> intersphinx: encode anchor value before attempting to quote

- doc/tips.rst
- sphinxcontrib/confluencebuilder/cmd/report.py
- sphinxcontrib/confluencebuilder/exceptions.py
- sphinxcontrib/confluencebuilder/publisher.py
Provide users more feedback for scenarios where an anonymous configuration is (unexpectedly) set:
- provide userspace/password feedback on bad-space error
- report: indicate if a sensitive configuration is a set empty value
- doc: add note about virtual environments for ci env passing
> anonymous publish feedback

- sphinxcontrib/confluencebuilder/assets.py
- sphinxcontrib/confluencebuilder/translator/storage.py
When processing runtime generated image nodes, the asset management will attempt to track newly created assets when preparing a node's translation. This requires determining the document which the image will be attached on, which uses the `document` attribute populated through a Sphinx run. When assembling documents using the `singleconfluence` builder, this attribute is not provided and injected image nodes will be ignored. To avoid this, when `singleconfluence` is being invoked, explicitly pass in the docname to be used to ensure an asset entry can be fetched.
> force docname on singlebuilder asset fetching

- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/logger.py
Status logging on an iterator will not generate newlines to a better user experience for log message; however, when an instance is configured for a more verbose logging state, these status messages may be stacked with verbose messages that may be printed. To avoid this, always set to fold lines when a verbose mode is set.
For all verbose messages generated by this extension, add a `[confluence]` prefix to help easily distinguish builder-generated log messages over other verbose messages that may be generated.
> improve verbose logging

- sphinxcontrib/confluencebuilder/publisher.py
When purging is enabled, this extension will populate a list of descendant pages to delete and filter out pages that will get populated for the new publish set. With the final obsolete list of pages, they will be marked for deletion. It has been observed in some cases where Confluence reports descendant page identifiers for pages which no longer exist (assumed to be cache related). When this extension attempts to delete the non-existent page, it will generate an API error and stop the process. Instead of stopping, if a deletion event is reported to not exist on the Confluence instance, just ignore the error state.
> publisher: suppress a failed page delete on missing page id

- sphinxcontrib/confluencebuilder/translator/storage.py
As of Sphinx v3.5.4, changes have been made to the application where a `:caption:` hint on a toctree node will create a `nodes.title` instance instead of an `nodes.caption` instance. This modification was introduced to support styling changes introduced in docutils-0.17 \[1\].
This commit adjusts the `visit_title` to detect if the title entry is being built from a toctree node -- if so, forward the node processing back to the existing caption implementation.
\[1\]: sphinx-doc/sphinx#9053
> handle toctree caption changing from nodes.caption to nodes.title

- sphinxcontrib/confluencebuilder/translator/__init__.py
- sphinxcontrib/confluencebuilder/writer.py
This extension's base translator (`ConfluenceBaseTranslator`) is based off of docutil's `NodeVisitor` implementation. When a document finally departs, it would populate a `document` attribute which the writer implementation could fetch before writing content to a file. However, `NodeVisitor` already uses a `document` attribute for other purposes, and overriding the attribute causes issues for Sphinx/docutils calls which reference this attribute. Instead, renaming this attribute to `body_final`.
> do not override docutils node-visitor's document attrib

- sphinxcontrib/confluencebuilder/config/__init__.py
- sphinxcontrib/confluencebuilder/util.py
- tests/lib/__init__.py
If `getpass` is invoked in an msystem-environment (MSYS, MinGW) with a Windows console Python interpreter, password input cannot be captured on the console and the interpreter needs to be manually closed with a CTRL-BREAK call. While users can avoid this scenario by wrapping their invoke of Sphinx with a `winpty` call, it is not obvious to new users and an annoyance to users who may forget to add the command in an invoke.
This commit attempts to alleviate this undesired user experience by attempting to detect the situation where this may occur, and provide an alternative means to acquire a password value. This initial implementation will check for three key hints:
This issue can only occur in a Windows environment. This check helps exclude all other OS-types. Note that this can also …
> provide msystem-environment getpass override

- sphinxcontrib/confluencebuilder/translator/storage.py
- tests/validation-sets/standard/tables.rst
The `widths` attribute used in various table directives will be integer values hinting at percentages \[1\] (when integer values are provided). The initial implementation to support a `widths` attribute incorrectly set values to pixel lengths; correcting.
\[1\]: https://docutils.sourceforge.io/docs/ref/rst/directives.html#table
> storage: correct table width hint type

- doc/configuration.rst
- doc/tips.rst
- doc/tutorial.rst
Adjusting the documentation to promote the `confluence_ask_password` option over `confluence_server_pass`. User feedback has mentioned multiple times that the documentation appears to be promoting the storing of secret in shared repositories. To help alleviate these concerns (in part with changes \[1\] to `confluence_ask_password` to better support MSYS/MinGW environments), areas of the documentation which hint to specify a password value will be replaced with the ask/prompt option. Users who want to explicitly set password options will find the options when browsing the documentation and observe the cautions associated with the configurations (which may help reduce users from storing secrets in a shared repository).
This merge request also introduces changes to the configuration section …
> promote ask password

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/cmd/report.py
- sphinxcontrib/confluencebuilder/config/checks.py
- sphinxcontrib/confluencebuilder/config/defaults.py
- sphinxcontrib/confluencebuilder/exceptions.py
- sphinxcontrib/confluencebuilder/publisher.py
- sphinxcontrib/confluencebuilder/rest.py
- tests/unit-tests/test_config_checks.py
Provides the ability for a user to publish documentation into a target root page on a Confluence instance. Where `confluence_parent_page` provides the ability to publish under a target page, the newly added `confluence_publish_root` option will instead replace the target root document with the root document's content of the documentation set being published.
> support publishing to root page

- sphinxcontrib/confluencebuilder/translator/storage.py
- tox.ini
For releases of Sphinx pre-v4.x, signature descriptors could contain identifier entries wrapped in an emphasis node. In the most recent version of Sphinx (observed in 4.0.0b2), identifiers may not be wrapped in an emphasis node. Instead of relying on an emphasis node, use the class hint which identifiers an identifiers type \[1\] to build an `em` container.
Sphinx has been refactoring \[2\]\[3\] its implementation to adjust the use of the `default` alignment back to `None`, to follow with docutils. Adjusting a series of lines which rely on the `default` assignment as a hint for default alignment, where now an unset alignment applies the default alignment as well.
---
\[1\]: https://github.com/sphinx-doc/sphinx/blob/v3.5.4/sphinx/addnodes.py#L224-L226
\[2\]: …
> maintenance for sphinx 4.x

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/cmd/report.py
- sphinxcontrib/confluencebuilder/config/checks.py
- sphinxcontrib/confluencebuilder/rest.py
- tests/unit-tests/test_config_checks.py
Introduces a configuration option `confluence_publish_headers` which allows a user to inject custom headers to be used when interacting with a Confluence instance. This help deal with unique environments which may require header options to exist (e.g. for authentication/etc.) for API requests to succeed.
> support publish header modifications

- doc/_themes/sphinx13b/static/sphinx13b.css
Documentation will style `pre` class `span` entries with a border/color/etc. to help promote/identify the literals through the documentation set. It has been noticed that `confval` entries in newer Sphinx builds will be assigned the same style, which is not desired to be added to these configuration title entries.
Adjusting the styling to only apply the style modifications if the pre-span type is contained inside a literal marked code element.
> doc: only border/color literal-marked pre-span

- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/config/checks.py
- sphinxcontrib/confluencebuilder/config/defaults.py
- sphinxcontrib/confluencebuilder/translator/storage.py
This commit provides an advanced option to allow raw html injection in the output of a storage-format generated document. This is to help users wanting to somewhat support raw HTML content generated from Markdown sources.
This is not always guaranteed to work; the raw html content may not be compatible with Atlassian's storage format. Results may fail to publish or contents may be suppressed on the Confluence instance.
> support raw html injection

- sphinxcontrib/confluencebuilder/translator/storage.py
- tests/unit-tests/datasets/common/image.rst
- tests/unit-tests/test_rst_image.py
With a previous change helping manage new alignment hints in Sphinx \[1\], these changes would apply default alignment hints to nodes which should not be using them. For example, table of contents captions and raw images (outside of figures) would apply a default alignment of `center`, where no implicit alignment is applied when using the `html` builder.
To correct this, only attempt to apply alignments to captions, legends and images if their parent is a figure node.
\[1\]: 50fd9ca636c54ab8fb272fe489154a3dcdf0ca73
> storage: only apply default alignment on figure entities

- sphinxcontrib/confluencebuilder/translator/__init__.py
- sphinxcontrib/confluencebuilder/translator/storage.py
Renaming the escape method calls to a more proper name (encode text), to better reflect its purpose.
This change also exposes `encode` on this extension's translator instance, to better serve third-party extensions which may wish to encode text to be used for a configured translator.
> translator: rename escape text to encode text

- tests/test_validation.py
Validation executions are expected to be all or nothing. When invoking a validation run, hint that the tests should fail-fast when an error occurs (to stop any other validation tests from running).
> tests: fail-fast when running the validator

- sphinxcontrib/confluencebuilder/assets.py
- sphinxcontrib/confluencebuilder/translator/storage.py
Typically, `uri` attributes processed by this extension have typically seen the values be only `str` types. However, it has been observed that some extensions (e.g. `sphinxcontrib.drawio`) that the type for `uri` attributes on images can be `pathlib` types. To be flexible on whatever type is set, always cast these entries to `str` to ensure consistent processing.
> force str cast on uri attribute values

- sphinxcontrib/confluencebuilder/translator/storage.py
It has been observed that some extensions (e.g. MyST-Parser) will inject alignment hints for cells into a node's `classes` attribute. This would allow a styling to define a, for example, `text-align:center` class which can include a center alignment hint for formatting on a document.
In the event that a text-align style has been detected inside a class list on a node, directly inject it into the style attribute of the paragraph holding the cell data.
> support cell alignment hints injected in the classes attribute

- sphinxcontrib/confluencebuilder/rest.py
- sphinxcontrib/confluencebuilder/std/confluence.py
Based off some newer documentation and implementation checks, it appears that no-check value to be set for the `X-Atlassian-Token` header should be a value of `no-check` instead of `nocheck`; adjusting.
This commit also adds an undocumented `CONFLUENCEBUILDER_LEGACY_NOCHECK` environment option to use the legacy header value for users who may experience issues in their environments.
Confluence versions to be tested against:
> adjust attachment no-check header to most recent value

- MAINTAINERS.rst
- doc/configuration.rst
Adding `versionadded` to newly added configurations from the v1.5 release.
In addition, adding notes on the `MAINTAINERS` document to ensure they are not missed during a release.
> doc: add versionadded for recently added configurations

- sphinxcontrib/confluencebuilder/translator/storage.py
Rubric nodes were always processed as matching header entries on the active level for a document. However, when using builders like `html`, these nodes are just paragraph elements styled in a weighted fashion. Adjusting the node processing to mimic the same way.
This resolves some autodocs cases where generated rubric nodes in a document would result in headers being injected in odd places of a document.
> rubrics should be titled paragraphs

- sphinxcontrib/confluencebuilder/__init__.py
This extension would automatically inject the `sphinx.ext.imgmath` extension into the Sphinx application if the extension was not detected as configured by a user. This was to help users easily use the only supported math-handling extension for math directives when publishing to Confluence targets.
An issue with this approach is that this would also inject the extension for a Sphinx invoke, even when not using a Confluence builder (e.g. if a user is building an `html` builder). This would override any other math extension (e.g. `sphinx.ext.jsmath`) that may be registered. To prevent this, only lazily inject `sphinx.ext.imgmath` when using a Confluence-based builder.
> only inject sphinx.ext.imgmath if confluence building

- .github/workflows/build.yml
- tests/unit-tests/test_sphinx_domains.py
- tox.ini
Sphinx provides a stable v4.1.x series; adjusting the tox configuration and workflows to support the newer revision. Following maintenance guidelines, this allows a series of legacy Sphinx revisions to be dropped as well.
> test with sphinx 4.1.x

- .github/workflows/build.yml
- tox.ini
Sphinx provides a stable v4.2.x series; adjusting the tox configuration and workflows to support the newer revision. Following maintenance guidelines, this allows a series of legacy Sphinx revisions to be dropped as well.
> test with sphinx 4.2.x

- tests/lib/__init__.py
Injecting the `sphinx.ext.imgmath` extension into the validation testing as the configuration preloading will generate a warning (which will fail the validation test) since imgmath is now loaded at a later stage \[1\].
\[1\]: 32af6a9c6b206878a64c65a80829b9fec7c1deca
> tests: always include sphinx.ext.imgmath extension for tests

- sphinxcontrib/confluencebuilder/translator/storage.py
When Sphinx provides line nodes through a translator, there is most likely a desire to ensure that each line node help represent text on their own individual lines. The previous translator would only group line block entries into paragraphs -- which work for the most part, but not for all documentation cases. When multiple line nodes are detected, inject a newline (`<br />`).
> inject newlines for non-wrapped content

- sphinxcontrib/confluencebuilder/translator/__init__.py
- sphinxcontrib/confluencebuilder/translator/storage.py
When prepare text to be published to a Confluence instance, always remove any non-space control characters. This prevents publishing errors such as the following:
An unsupported Confluence API call has been made.
REQ: PUT
RSP: 400
URL: .../rest/api
API: content
DATA: {
"statusCode": 400,
"data": {
"authorized": false,
"valid": true,
"errors": [],
"successful": false
},
"message": "com.atlassian.confluence.api.service.exceptions.BadRequestException: Error parsing xhtml: Illegal character ((...))\n at [row,col {unknown-source}]: ...,...]"
}
> remove non-space control characters

- sphinxcontrib/confluencebuilder/translator/storage.py
If an `image` node type is provided to a translator which does not have a valid `uri` attribute value, ignore it. This is to gracefully deal with extensions which may produce an incomplete image node in for a non-fatal condition.
> skip image nodes without a uri

- sphinxcontrib/confluencebuilder/publisher.py
The Sphinx Confluence Builder still only supports the legacy display with storage format content generated from the storage format translator. Recent changes show that even when publishing with a representation request of `storage`, the content will be accepted but a newer editor may be used. This is undesired at this time (until an ADF translator is introduced).
To ensure we use the legacy editor, inject the metadata for new pages to explicitly indicate that a `v1` editor must be used. This appears to work with Confluence Cloud and (at least) the oldest supported Confluence Server revision. Note that the metadata is not applied on updated pages as the forced conversion is not supported by an update request.
> publisher: force v1 editor

- sphinxcontrib/confluencebuilder/config/notifications.py
- tests/unit-tests/test_config_checks.py
- tests/unit-tests/test_config_hierarchy.py
The `confluence_max_doc_depth` has been flagged as deprecated, with the intent of users to move to using the `singleconfluence` builder instead. Adding a warning message for users who may be still using this feature.
> flag max-doc-depth config as deprecated

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/assets.py
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/config/__init__.py
- sphinxcontrib/confluencebuilder/config/checks.py
- sphinxcontrib/confluencebuilder/config/defaults.py
- sphinxcontrib/confluencebuilder/config/notifications.py
- sphinxcontrib/confluencebuilder/singlebuilder.py
- sphinxcontrib/confluencebuilder/state.py
- tests/lib/__init__.py
- tests/test_validation.py
- tests/unit-tests/test_config_titlefix.py
- tests/unit-tests/test_rst_references.py
- tests/unit-tests/test_sphinx_glossary.py
- tests/unit-tests/test_usecase_nested_ref.py
Sphinx v4.x+ uses the `root_doc` configuration over the deprecated `master_doc` configuration. Adjusting this extension's implementation to following this renaming. Renaming configuration entries referring to a `master` document to use `root` document instead. This includes adjusting:
- `confluence_master_homepage` to `confluence_root_homepage`
- `confluence_purge_from_master` to `confluence_purge_from_root`
To ensure support with legacy revisions of Sphinx, the builder's configuration check (when initialized) will ensure `root_doc` is populated with a `master_doc` value if `root_doc` does not exist. Users using the older configuration names will be presented with a deprecated warning.
> switch towards root_doc

- sphinxcontrib/confluencebuilder/config/__init__.py
- sphinxcontrib/confluencebuilder/config/notifications.py
- tests/test_validation.py
A recent set of new legacy mappings \[1\] were incorrectly defined (mapping new to old); correcting. Also, deprecation checks were added for `confluence_max_doc_depth`; however, the warning message did not properly reference the configuration key value (it instead used the last cycled key from the cycled deprecated configuration keys. Adjusting these warnings messages to use the proper key value.
\[1\]: 273769c1c8d37d48fe2a27bf326e1d33377022ba
> config: correct deprecation legacy mappings and warning messages

- doc/_templates/index.html
- doc/_templates/indexsidebar.html
- doc/contents.rst
Make a series of corrections to correct documentation processing when using the `dirhtml` builder. This includes:
- doc: permit dirhtml builder for indices/table references
- use pathto for various template href targets
> improve doc dirhtml builder

- doc/_templates/indexsidebar.html
Build the sidebar's link to the install document outside of the translation tags or the build process will fail. This corrects the following error:
Theme error:
An error happened in rendering the page index.
Reason: TemplateSyntaxError("expected token 'end of print statement', got '('")
> doc: correct sidebar install path building

- tests/test_validation.py
- tox.ini
Older versions of Sphinx do not support the recent docutils v0.18 release. Explicitly configuring the test environment to enforce this for the older versions being tested.
Note that in Sphinx v4+, the supported docutils version is listed in its setup definition (i.e. does not need to be managed here).
Error handling was adjusted for a "bad space" detection which now raises a `ConfluenceBadServerUrlError` exception [1]. Adjusting the validation test to account for this.
[1]: d23dc9a1fdbb5845f9e08c32efe9c080ceefcaf5
> improve testing state (explicit docutils; validation check correction)

- sphinxcontrib/confluencebuilder/translator/storage.py
Adjust line-block entries to be `div` entries with margin values to render desired indentations. This provides a similar look-and-feel to other common (HTML) builders.
> storage: support indented line-blocks

- sphinxcontrib/confluencebuilder/publisher.py
Confluence will accept the upload of an SVG without an XML declaration; however, it will render the macro as corrupted image. To properly render SVG images on Confluence, the declaration is required. This commit adjusts the publishing process to inject an XML declaration in an SVG file before attaching it to a page.
> inject xml declaration if an svg attachment does not have one

- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/translator/storage.py
- sphinxcontrib/confluencebuilder/transmute.py
Adding support for some third-party extensions.
Still debating if this is the right move -- in terms of maintenance/complexity to this extension. Although if it makes users of this extension experience easier, it may be worth it.
Adding support for:
- [sphinx-toolbox](https://sphinx-toolbox.readthedocs.io/en/latest/)
-  [sphinxcontrib-mermaid](https://github.com/mgaitan/sphinxcontrib-mermaid)
> provide some third-party extension support

- sphinxcontrib/confluencebuilder/builder.py
Adjusting purge event processing to render a dot for each asset being removed. This should provide better feedback that purging is progressing when a lot of pages/attachments are being removed.
> provide more purging feedback

- sphinxcontrib/confluencebuilder/assets.py
- sphinxcontrib/confluencebuilder/translator/storage.py
- sphinxcontrib/confluencebuilder/transmute.py
Provide support for processing sphinx-gallery nodes when using the Confluence builder.
This pull request includes a change to asset processing ("assets: flexible os.sep-prefix path finding") to support gallery-provided images starting with `/`. Also, with changes to better size detection for gallery thumbnail-like images, improvements have been made to use a better path detection whenever an image's size needs to be calculated.
> add support for sphinx-gallery

- sphinxcontrib/confluencebuilder/publisher.py
A previous commit \[1\] added support to inject XML declarations for SVGs which may be missing them. When the change was prepared, a switch in the development version from a `<svg` check to an `<?xml` check did not properly update the condition -- which now leads to injecting XML declaration on SVGs which already have them; correcting this.
\[1\]: dcc7f027f00e0909851586c9c473e6c30fd7f114
> correct xml-declaration injection for svgs

- sphinxcontrib/confluencebuilder/transmute.py
This extension does attempt to provide some support for various third-party implementations, this could cause issues if a specific third-party extension wishes to provide their own support for integrating with supported Confluence builders/translators. Adding a series of restriction checks to opt-out of node processing for these extensions.
> support restriction third-party extension handling

- sphinxcontrib/confluencebuilder/publisher.py
When assets are published, the comment field is assigned a key-hash value which can be queried for later to avoid re-uploading assets on multiple publishing events. This generated value is a single long string, which can cause display issues in the attachment area (text overflowing specific asset actions). Attempt to minimize this by chunking the hash value into parts.
> chunk a generated hash-comment for assets

- README.rst
- doc/_templates/index.html
- doc/_themes/sphinx13b/static/sphinx13b.css
- doc/_themes/sphinx13b/theme.conf
- doc/configuration.rst
- doc/features.rst
- setup.cfg
- setup.py
- sphinxcontrib/confluencebuilder/transmute.py
- tests/__main__.py
Perform a series of improvements to this extension:
Enforce that when install on a Python 2.7 interpreter that docutils is explicitly configured to an older version. This is to help enforce a docutils version which Sphinx 1.8.x series supports (which is the only supported version with Python 2.7)
When packaging sources (sdist), use a root owner/group to ensure consistent source package building no matter what user triggers a build.
Dropping the usage of the `tests_require` option. Aside from the option being deprecated and ignoring that the package listed in this field is already installed via `install_requires`, any test dependencies in this project are managed through a tox requirement file.
Disables short descriptions for unit tests (populated via any configured docstring on the test) …
> maintenance (2021-11-06)

- sphinxcontrib/confluencebuilder/builder.py
Adjusting both legacy page processing and legacy asset processing to use a status iterator (for percentage progress) over a simple dot-per-entity progress.
Some `note` calls inject an unneeded newline entry in their output, which the `note` call already handled; removing.
> improve builder progress status

- sphinxcontrib/confluencebuilder/storage/translator.py
For generated footnote tables, avoid styling them as tables by disabling any border hints on the default table styles.
> translator-storage: removing borders on footnote tables

- sphinxcontrib/confluencebuilder/storage/translator.py
If a line-block entry has no leading siblings in its "container", there is no need to indent the line-block entry. Check for this case and skip any indent/margin adjustments.
> translator-storage: only indent line-block with previous siblings

- tox.ini
Adding a new environment called `develop` to help sanity check tests against the main development branch of Sphinx.
> tox.ini: add develop environment

- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/assets.py
- sphinxcontrib/confluencebuilder/publisher.py
- sphinxcontrib/confluencebuilder/std/confluence.py
- sphinxcontrib/confluencebuilder/storage/translator.py
- sphinxcontrib/confluencebuilder/svg.py
- sphinxcontrib/confluencebuilder/transmute.py
- sphinxcontrib/confluencebuilder/util.py
- tests/unit-tests/datasets/common/image.rst
- tests/unit-tests/datasets/svg/index.rst
- tests/unit-tests/datasets/svg/svg-doctype.svg
- tests/unit-tests/datasets/svg/svg-none.svg
- tests/unit-tests/datasets/svg/svg-viewbox.svg
- tests/unit-tests/datasets/svg/svg.svg
- tests/unit-tests/test_rst_image.py
- tests/unit-tests/test_svg.py
- tests/unit-tests/test_util_convert_px_length.py
- tests/unit-tests/test_util_extract_length.py
Improves the handling of various image-set unit sizes and usage of the scaling option. Confluence supports only a pixel-define height/width values for images -- and this extension's original implementation will just forward whatever width/height value was set to Confluence while also generating a warning for non-pixel-detected size values.
This results in:
1) Users needing to update various images/figures to use pixels, even when not desired (when mixing with other builder types).
2) Cause images uploaded to Confluence to show a "broken" icon, since Confluence could not handle unique height/width values.
Also, the scale value was only ever applied when a width entry was not set -- where it should have been applied no matter the situation (i.e. scaling the provided height/width values, as …
> Improve image length option management and svg support

- sphinxcontrib/confluencebuilder/publisher.py
When breaking a hash-key for an attachment into chunks \[1\], do so including the prefix. This should provide a better visual experience in the attachment page.
\[1\]: 4d8cfa16591f1aefde9f80f8f5a8c9405f75df0a
> include hash-key prefix in chunking

- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/storage/translator.py
- tests/unit-tests/test_singlepage_assets.py
Perform a series of corrections/improvements for users of the `singleconfluence` builder.
- do not enable special page generation for singleconfluence builder
- restore singlebuilder initialization
- autoload autosummary for singleconfluence builder
- skip pre-processing assets for singleconfluence builder
- translator: ensure proper asset document name
> -improve single builder support

- sphinxcontrib/confluencebuilder/storage/translator.py
When processing the fallback condition for image/file nodes (for standalone assets), a change was added \[1\] which removed passing the active document into the asset manager (so it knows the proper document to attach an asset to). The removal of these, while valid (or irrelevant) for a `singleconfluence` builder is still needed for the standard `confluence` builder; restoring.
\[1\]: 44b6cd19b60c5cb07218ad025e1ea8340a330d4a
> translator: restore standalone fallback docname for assets

- sphinxcontrib/confluencebuilder/svg.py
- tests/unit-tests/datasets/svg/index.rst
- tests/unit-tests/test_svg.py
SVGs which only have a `viewbox` attribute may not properly render on Confluence (e.g. an SVG may visually load for a moment and the hide itself). By specifying an explicit width/height value inside SVGs provides a more consistent user experience -- adjusting SVG processing so that when a viewbox-only SVG is detected, use these values as the target width/height options to apply (which should set the attributes on the final SVG image).
> apply lengths for svgs with only a viewbox

- sphinxcontrib/confluencebuilder/builder.py
A previous change \[1\] to use a `status_iterator` did not properly provide feedback for attachment removals. Adjusting the status processing to reflect each removed attached by name.
\[1\]: b78fbf59282ff17923201a2ddc26aeeec6174f39
> improve status feedback for purged attachments

- sphinxcontrib/confluencebuilder/builder.py
- tests/unit-tests/datasets/toctree-numbered/doc.rst
- tests/unit-tests/datasets/use-cases/nested-ref-contents.rst
- tests/unit-tests/datasets/use-cases/nested-ref-external.rst
- tests/unit-tests/test_singlepage_toctree.py
- tests/unit-tests/test_sphinx_toctree.py
- tests/unit-tests/test_usecase_nested_ref.py
Section numbers populated into the environment's `toc_secnumbers` dictionary is based off the section identifier value -- not the text content of a section (used for mapping to Confluence's "target"). When attempting to determine which section number value to apply for a target, use the proper identifier instead.
> use proper identifier for section number mapping

- tox.ini
Python 3.11 has an alpha revision available. Adding an environment to help test this specific interpreter.
> tox: add support for python 3.11.x series

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/compat.py
- sphinxcontrib/confluencebuilder/config/defaults.py
- sphinxcontrib/confluencebuilder/singlebuilder.py
Sphinx's inlining toctree utility call will replace each toctree entry with the contents found for each document. In some cases, users may wish to keep the (resolved) toctree nodes since Confluence does not provide a customizable sidebar feature found in some HTML-based themes. With this commit, users can set `singleconfluence_toctree` to `True` to keep resolved toctree sections in a generated single documented.
> singleconfluence: support keeping toctree sections

- sphinxcontrib/confluencebuilder/__init__.py
Most configuration options do not properly set a `rebuild` flag. Adjusting several options to ensure a rebuild is triggered if a value changes, as well as opting to using the empty string over a boolean (since it seems to be the promoted choice in the Sphinx documentation).
> improve configuration rebuild flags

- sphinxcontrib/confluencebuilder/__main__.py
- sphinxcontrib/confluencebuilder/cmd/build.py
- sphinxcontrib/confluencebuilder/cmd/report.py
- sphinxcontrib/confluencebuilder/cmd/wipe.py
Provide a series of changes to cleanup mainline calls:
- improve/correct color processing
- report: wrap report cut data with markdown ticks
- wipe: improve spacing/i8n/coloring output
- wipe: capture sphinx errors
- report: add traceback into report cut
- wipe: add missing parent argument
> cleanup command line calls

- sphinxcontrib/confluencebuilder/translator.py
Instead of throwing a `NotImplementedError` exception for an unknown node, log the unhandled node type as a warning. This should provide some additional flexibility when using a Sphinx-based Confluence builder for users attempting to use third-party extensions.
> translator: relax unsupported node error

- sphinxcontrib/confluencebuilder/exceptions.py
- sphinxcontrib/confluencebuilder/publisher.py
When issuing a page update via a put request, explicitly set the `status` option to `current`. While `current` should be the default value for this option, there have been reports \[1\] that explicitly settings this option can help deal with unreconciled page states.
\[1\]: https://jira.atlassian.com/browse/CONFCLOUD-72349
In addition to retrying on a lock failure, also retry on unreconciled pages as Confluence will report "Retry in a few moments".
This commit also bumps the retry count from one second to three seconds.
With reports that an unreconciled API error may occur on Confluence instances greater than v7.3.2, adjusting the exception to be more generic.
---
See also: #528
> improve unreconciled page handling

- MAINTAINERS.rst
- MANIFEST.in
- babel.cfg
- doc/configuration.rst
- setup.cfg
- setup.py
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/config/checks.py
- sphinxcontrib/confluencebuilder/config/defaults.py
- sphinxcontrib/confluencebuilder/locale/__init__.py
- sphinxcontrib/confluencebuilder/locale/sphinxcontrib.confluencebuilder.pot
- sphinxcontrib/confluencebuilder/nodes.py
- sphinxcontrib/confluencebuilder/singlebuilder.py
- sphinxcontrib/confluencebuilder/storage/index.py
- sphinxcontrib/confluencebuilder/storage/search.py
- sphinxcontrib/confluencebuilder/storage/templates/domainindex.html
- sphinxcontrib/confluencebuilder/storage/templates/genindex.html
- sphinxcontrib/confluencebuilder/storage/templates/search.html
- sphinxcontrib/confluencebuilder/storage/translator.py
The following pull request brings support for a new option `confluence_page_generation_notice` which allows a user to add a "this page has been generated" message at the top of each document.
In order to make this feature work, adjustments/improvements have been made to this extension to improve additional languages and future support for manipulating document's header/footer content.
Adjusting the original navigation node implementation to use a more generic Confluence header/footer nodes. This allows this extension to easily inject more than just next/previous page content at the start of pages, specifically in this case, adding a page generation notice. This is also being done for future considerations towards adding a "show/edit source" links (see #339).
The majority of messages used …
> support page generation notice

- sphinxcontrib/confluencebuilder/rest.py
Explicitly cleans up the ``Rest`` class's session on deletion. This prevents warnings such as "ResourceWarning: unclosed SSLSocket" when the session is cleaned up automatically.
> rest: cleanup session on destruction

- sphinxcontrib/confluencebuilder/storage/translator.py
- tests/unit-tests/test_rst_citations.py
- tests/unit-tests/test_rst_footnotes.py
Styling footnote entries to have their identifiers wrapped with brackets.
> translator-storage: add brackets for footnotes

- sphinxcontrib/confluencebuilder/exceptions.py
- sphinxcontrib/confluencebuilder/publisher.py
Adding a check to help detect if a request has been made to publish a page as a child of itself. This issue should only ever happen if a configuration sets `confluence_parent_page` with the same value of the title page for the documentation's `root_doc`. On Confluence Cloud, a publish attempt for this case provides a descriptive message "Cannot add an existing ancestor as a child!"; although on Confluence self-hosted solutions, it can report a non-descriptive 500 error.
Adding this message should provide a more helpful description of the issue, and also avoid invoking an invalid request to a Confluence instance.
See also: #517
> add a publishing pre-check for self-referenced ancestor request

- tests/lib/__init__.py
- tests/test_sandbox.py
When reading a raw file for a sandbox "raw" request, do so using the `io` module with an explicit `utf-8` encoding. This should prevent any Unicode error messages when testing with non-ASCII characters in some environments.
Explicitly disables attempts to colorize the terminal for MinGW environments, as the nature of this environment will almost always result in detection that the output streams should be be colored (even though they can support it).
> test maintenance (2021-11-16)

- doc/_themes/sphinx13b/static/sphinx13b.css
- doc/_themes/sphinx13b/theme.conf
- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/config/checks.py
- sphinxcontrib/confluencebuilder/config/defaults.py
- sphinxcontrib/confluencebuilder/nodes.py
- sphinxcontrib/confluencebuilder/storage/translator.py
- tests/unit-tests/test_config_checks.py
- tests/unit-tests/test_config_sourcelink.py
Introduces support for a new configuration `confluence_sourcelink`, which allows links to original source (e.g. "Edit on GitHub") for each generated page.
> support source link option

- sphinxcontrib/confluencebuilder/storage/templates/domainindex.html
- sphinxcontrib/confluencebuilder/storage/templates/genindex.html
- sphinxcontrib/confluencebuilder/storage/translator.py
Including some corrections from the initial page-generation-notice support:
- translator: dropping unused depart for page-generation-notice node
- translator-storage: remove undesired spacing on index pages
> page generation notice adjustments

- sphinxcontrib/confluencebuilder/publisher.py
- sphinxcontrib/confluencebuilder/rest.py
- tests/lib/__init__.py
- tests/test_validation.py
- tests/unit-tests/test_publisher.py
Adjusting the checks to verify expected JSON data on a first connection. This can better help debug/inform new connections which may be misconfigured, presenting more useful error messages instead of possible stacktraces.
The timeout option was moved into the Requests session instance, when session support was added into this extension; however, Requests does not support a timeout option being used in the session. Adjusting the timeout options to be applied to the various request calls.
Introducing a series of publisher-related tests -- to help verify space fetching, verify timeout options and expected error handling.
> improve publisher

- sphinxcontrib/confluencebuilder/config/checks.py
- sphinxcontrib/confluencebuilder/config/validation.py
- tests/unit-tests/test_sphinx_toctree.py
The configuration checks related to "empty permitted" string have not been applicable for sometime. Originally, strict checking was added to help prevent strings from being set and empty; however, this causes complications for users trying to override/clean options from a command line (passing in empty defines which result in an empty string).
Removing this implementation.
Also, adding a unit test to validate a user defining an empty `confluence_secnumber_suffix` option.
> config: remove permits-empty logic for string checks

- sphinxcontrib/confluencebuilder/config/defaults.py
Users should be permitted to omit a file suffix for generated documents (i.e. no extensions); adjusting.
> config: allow empty file suffix

- sphinxcontrib/confluencebuilder/cmd/report.py
Not all configuration options provided by this extension are prefixed with `confluence_`; adjusting to also include the recently added support for singleconfluence builder options.
> cmd-report: include singleconfluece prefix options

- sphinxcontrib/confluencebuilder/__init__.py
autosummary nodes are automatically registered into Sphinx if the `sphinx.ext.autosummary` extension is explicitly registered in the extension list; however, if this extension is unavailable for some reason, this can cause the setup process to fail. Add an additional sanity check for injecting autosummary nodes.
> validate autosummary support for attempting to inject nodes

- sphinxcontrib/confluencebuilder/exceptions.py
Cleanup the exception messages generated by this extension to be a bit more clear/consistent, and also adjusting their formatting a bit to avoid the need to break up messages under various string entries.
> improve exception messages

- sphinxcontrib/confluencebuilder/builder.py
If a configuration explicitly configures the `confluence_asset_override` option to a value of `False`, asset publishing will result in an exception; correcting.
> builder: handle explicit false-asset override

- sphinxcontrib/confluencebuilder/storage/translator.py
It is "common" (with HTML builder environments) for inline text assigned with a `strike` role to be an indication that the text should have a strikethrough style applied. Since Confluence provides support through strikethrough content, using this role hint to create `s` tags for any marked text.
> support strikethrough through strike role

- doc/directives.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/directives.py
- sphinxcontrib/confluencebuilder/nodes.py
- sphinxcontrib/confluencebuilder/storage/translator.py
Adding a convenience directive to help users inject a newline into a Confluence page. This is to provide an alternative to generating a raw node entry to manually injecting a `br` tag.
> introduce confluence newline directive

- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/exceptions.py
- sphinxcontrib/confluencebuilder/publisher.py
Adding a pre-check to generate a detailed exception when a page is being updated as a child of itself. When a root page is first upload, ancestors of the page will be fetched and marked as "reserved". If a future page update request attempts to move a root page's ancestor under the root page's tree, the `ConfluencePublishAncestorError` exception will be raised.
See also: #348, #559 and #517
> add ancestor check

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/config/checks.py
- sphinxcontrib/confluencebuilder/rest.py
Provides a configuration `confluence_request_session_override` which enables a user to override specific options on a Requests session object. This is to provide flexibility in managing various Requests options which may not be supported through other Confluence builder configuration options.
> rest: provide request session override

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/config/checks.py
Providing an advanced navigational document list override to allow users to override the document list used when considering navigation's "Next" and "Previous" targets. This provides the ability to remove pages, reorder documents or even inject external documents into the navigation set.
> provide navdocs document list override

- sphinxcontrib/confluencebuilder/publisher.py
The existing storage format translator only supports capabilities from the v1 editor. While new pages are always created with the v1 flag, if an existing page was converted or previous made with a new editor, updates with this extension will publish and render poorly using the newer editor. Adjusting every update page event to always use v1.
> publisher: always force v1 editor

- sphinxcontrib/confluencebuilder/publisher.py
If Confluence reports that a publishing event fails due to a transaction rollback, queue the publish event for a retry. This error has been rarely observed when pushing page updates to Confluence Cloud.
> publisher: retry on transaction rollback

- tox.ini
Adjusting the tox environment list to perform linter checks first. This is to help development environments output linter errors sooner than later, where styling/etc. errors can be corrected while other functional tests are being performed.
> tox: reorder linter environments to be run first

- tests/test_validation.py
With the introduction of publisher unit-test checks, there is no need to perform publisher-related checks during the validation phase. Dropping the `test_nonjsonresponse` test method.
> tests-validation: remove unneeded bad url check

- sphinxcontrib/confluencebuilder/state.py
- tests/test_validation.py
Configure the validation page generation to build navigational links between each validation page's documentation set.
> tests-validation: span navigation across all validation pages

- requirements_validation.txt
- tests/test_validation.py
- tests/validation-sets/markdown/code.md
- tests/validation-sets/markdown/index.md
- tests/validation-sets/markdown/table.md
Adding a validation set specific to the verification of Markdown support (using the MyST-Parser extension).
> tests-validation: adding markdown check with validation

- .github/workflows/build.yml
Only trigger build validation when dealing with the implementation or related files (e.g. excluding documentation, README.rst, etc.).
> .github: only perform build validation for required paths

- .github/workflows/docs.yml
- doc/Makefile
- doc/make.bat
When using build helper scripts for documentation, treat any warnings as errors. This should help produce a cleaner documentation state when updating and ensure issues are not missed.
Adding a GitHub action to validate the successful build of desired documentation outputs.
> build checks for documentation

- .github/workflows/validate.yml
- CHANGES.rst
- MAINTAINERS.rst
- README.rst
- doc/conf.py
- setup.cfg
- sphinxcontrib/confluencebuilder/locale/sphinxcontrib.confluencebuilder.pot
- tests/test_validation.py
- tests/validation-sets/base/index.rst
A series of maintenance changes to the repository:
- validation: add link to homepage in base validation document
- validation: only permit root homepage on base document
- validation: correct navlink on the standard document set
- README.rst: sync eol confluence versions
- doc: sync eol confluence versions
- README.rst: adjust supported sphinx versions
- doc: adjust supported sphinx versions
- .github: add test version in validation workflow
- i8n: omit headers on all catalog calls
- i8n: updating message list
- MAINTAINERS.rst: mention config version overrides
> maintenance (2021-11-21)

- CHANGES.rst
- sphinxcontrib/confluencebuilder/publisher.py
- tests/lib/__init__.py
- tests/unit-tests/test_publisher_connect.py
- tests/unit-tests/test_publisher_page.py
When a page is fetched by an identifier, it will cache the name directly on the returned page JSON structure. Unfortunately, the initial implementation of root page publishing feature introduced a get-page-by-id call with invalid implementation. The title value should be fetched from the page instance; correcting.
This pull request also adds some additional publisher unit tests, to help validate some of the original issued implementation.
> publisher: fixed page title caching for explicit page id fetches

- .github/workflows/build.yml
- tests/unit-tests/datasets/expand/index.rst
- tests/unit-tests/datasets/newline/index.rst
- tests/unit-tests/test_confluence_expand.py
- tests/unit-tests/test_confluence_newline.py
- tox.ini
Adding a unit test to sanity check support for the `confluence_newline` directive.
Adding a unit test to sanity check support for the `confluence_expand` directive.
Sphinx provides a stable v4.4.x series; adjusting the tox configuration to support the new revision. Following maintenance guidelines, this allows a series of legacy Sphinx revisions to be dropped as well.
> test additional custom directives (expand; newline)

- sphinxcontrib/confluencebuilder/storage/translator.py
- tests/unit-tests/test_rst_figure.py
The original implementation added to support figures would wrap the contents inside an informational macro. This was a styling preference at the time (to produce a shaded background); however, it is not consistent with how figures are generated with other builds (like HTML). Adjusting the figure implementation to do what is common -- a simple paragraph grouping on the figure structure.
> storage-translator: remove information macro from figure structure

- .github/workflows/build.yml
- CHANGES.rst
- README.rst
- doc/conf.py
- tox.ini
Performing a series of maintenance changes:
- Updating supported Python versions (dropped EOL v3.6).
- Updating supported Confluence versions (dropped EOL versions).
- Updating supported for Sphinx versions.
- Updating CHANGELOG.
- Copyright bump on the documentation.
> maintenance (2022-01-29)

- sphinxcontrib/confluencebuilder/publisher.py
- tests/unit-tests/test_publisher_connect.py
- tests/unit-tests/test_publisher_page.py
When a user configures `confluence_root_homepage` to adjust the homepage for a personal space on Confluence Cloud, the instance will implicitly attempt to adjust the space type to `global` instead of its original `personal` type. Confluence will automatically fail the REST attempt with the message:
Cannot change space type from personal to global or vice versa
To prevent this, explicitly configure the space's type field to the original once detected when querying the space information during initialization.
> publisher: forward explicit space type when updating homepage

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/config/checks.py
- sphinxcontrib/confluencebuilder/config/validation.py
- sphinxcontrib/confluencebuilder/exceptions.py
- sphinxcontrib/confluencebuilder/publisher.py
- sphinxcontrib/confluencebuilder/rest.py
- sphinxcontrib/confluencebuilder/std/confluence.py
- tests/unit-tests/test_config_checks.py
Provides an initial implementation to help limit API requests invoked to a Confluence instance is the instance reports that requests are being rate limited \[1\].
\[1\]: https://developer.atlassian.com/cloud/confluence/rate-limiting/
Introduces a new configuration option `confluence_publish_delay` to allow a user to force delays between API requests. This can help specific user environments which have either large data sets or want to limit a rapid series of API requests to a configured instance.
> support rate limiting

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/config/defaults.py
- sphinxcontrib/confluencebuilder/publisher.py
Provides a configuration option for users to print out requests made to a Confluence instance (GET's, PUT's, etc.). This is to help provide additional information to users attempting to debug their connections, without having them have to manually configure more complex debug logging in their Sphinx configuration.
> add publish debugging option

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/cmd/report.py
- sphinxcontrib/confluencebuilder/config/checks.py
- sphinxcontrib/confluencebuilder/exceptions.py
- sphinxcontrib/confluencebuilder/publisher.py
- sphinxcontrib/confluencebuilder/rest.py
- tests/unit-tests/test_config_checks.py
- tests/unit-tests/test_publisher_connect.py
Provides a configuration option for users to easily user personal access tokens (PATs) for authentication. This avoids the need for a user to configure `confluence_publish_headers` and manually configure the `Authorization` header entry.
> support personal access tokens

- doc/configuration.rst
- doc/contents.rst
- doc/directives.rst
- doc/guide-math.rst
- doc/guides.rst
- doc/roles.rst
- doc/tips.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/config/checks.py
- sphinxcontrib/confluencebuilder/config/defaults.py
- sphinxcontrib/confluencebuilder/directives.py
- sphinxcontrib/confluencebuilder/nodes.py
- sphinxcontrib/confluencebuilder/roles.py
- sphinxcontrib/confluencebuilder/storage/translator.py
- sphinxcontrib/confluencebuilder/transmute/__init__.py
- tests/unit-tests/test_config_checks.py
Adds the ability for users to tailor their documentation generation to use a Confluence-provided LaTeX macro. Confluence does not support LaTeX by default; however, a Confluence instance may support LaTeX if a marketplace add-on provides a macro supporting this.
This commit processing math blocks in a similar fashion as before -- math content is defined in a document, the content is converted into LaTeX and this extension will use the imgmath extension to generate images. This change adds some conditions to stop the conversion from LaTex to images if a user specifies a `confluence_latex_macro` option. When set, a macro will be generated instead (using the value of this option as the name of the macro).
Adding support for users to inject LaTeX content into Confluence. LaTeX content will by …
> improved math/latex support

- tests/lib/__init__.py
- tests/unit-tests/test_publisher_connect.py
- tests/unit-tests/test_publisher_page.py
The initial implementation of the publisher tests had a high chance in timing out if the mocked HTTP server failed to process requests in a timely fashion (e.g. connection error 54). The main issue was that the HTTP server could only handle a single request at a time and an fixed timeout of one second is enforced on these tests. This would lead to cases where a unit test would issue some requests, the request were being handled with a response pushed back, and a trailing request could automatically kick in before the mocked instance formally closed the request. If the unit testing (client) did not get the request served right away in the first second, it would timeout.
Improvements have been added to the test -- we relax the timeout a bit (to ensure the GitHub action instances have a bit …
> adjust publisher tests to prevent connection reset states

- doc/_templates/indexsidebar.html
- doc/_themes/sphinx13b/layout.html
- doc/_themes/sphinx13b/static/sphinx13b.css
- doc/_themes/sphinx13b/theme.conf
- doc/configuration.rst
- doc/contents.rst
- doc/directives.rst
- doc/guide-ci.rst
- doc/guides.rst
- doc/roles.rst
- doc/tips.rst
Cleanup the location of "see also" content for Jira directive/roles. In addition, add some "see also" entries in the `confluence_jira_servers` configuration option's section.
Provide a series of toctree tweaks to mix which document's will include a depth larger than one -- with the intent to better reflect more important sub-sections to users browsing the main content page.
Moves the CI publishing information into its own guide document. In addition, improve this guide by providing examples on how a user would deal with authentication from using either API tokens to PATs.
Expand the conditions where the gold background color is applied for link targets. This should help provide the desired target effect for reference jumps which target anchored entries.
Adjusting the breadcrumb separator …
> documentation cleanup (2022-02-20)

- sphinxcontrib/confluencebuilder/exceptions.py
- sphinxcontrib/confluencebuilder/publisher.py
- sphinxcontrib/confluencebuilder/rest.py
The following reworks the rate-limit handling this extension performs when interacting with a Confluence instance. The initial implementation would wait for a 429 error before attempting to limit calls, instead of proactively delaying API calls which Confluence hints the client to perform. The new implementation will now check for the retry-after header option after each API request made, and apply this delay on a subsequent API call.
This commit reworks the Rest and related implementation a bit. Instead of using a `RestRateLimited` class to capture failed API requests, the implementation has been switched to using decorators. This cleans up the implementation a bit and helps manage rate limiting data all in the `Rest` class.
In addition, a `requests_exception_wrappers` decorator was …
> improve rate limiting handling

- sphinxcontrib/confluencebuilder/storage/translator.py
- tests/unit-tests/datasets/common/targets.rst
- tests/unit-tests/test_rst_targets.py
When targets are processed by the storage translator, the original implementation would only focus on building anchors (when needed) to support features like citations/footnotes; however, inline internal targets are never properly formed. While anchors are created, the text for these targets are skipped over.
This commit corrects these types of targets by ensuring the target's text is added into the body after creating the anchors associated to the text.
> ensure inline internal targets have text

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/config/checks.py
- sphinxcontrib/confluencebuilder/publisher.py
- tests/unit-tests/test_config_checks.py
PR for #629
Allows using `confluence_version_comment` to add a comment to a version in the Confluence version history.
> Support content version.message / page history comment field

- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/config/checks.py
- sphinxcontrib/confluencebuilder/config/validation.py
- sphinxcontrib/confluencebuilder/storage/__init__.py
- tests/lib/__init__.py
- tox.ini
Add a series of pylint suppressions for Python 2.7.x compatibility import tests.
Tweaking the `mock_getpass`/`mock_input` calls to only re-apply the original modules if the original module could be fetched.
pylint v2.7.3 has a regression issue (to be fixed in v2.7.4) causing the tox builds to fail. For the interim, restricting to an older version.
> Pylint updates

- sphinxcontrib/confluencebuilder/storage/translator.py
Injecting div's for compound nodes to help space out compound entries which may be generated from autodoc processing. docutils injects div blocks as well for these node types \[1\], so it is expected to cause no other issues with other capabilities. This can correct some visualization observed when processing documentation provided by Breathe -- specifically, having new lines between each include entry for C++/C sources.
\[1\]: https://repo.or.cz/docutils.git/blob/d169015ee0f412cffd69b33654d8a119d99bc0f3:/docutils/writers/html4css1/__init__.py#l285
> translator-storage: add div blocks for compound nodes

- sphinxcontrib/confluencebuilder/storage/translator.py
Previous testing/support of Markdown with MyST provides table alignment hints through `text-align:<value>` class identifiers. Recent testing shows that explicitly alignment classes are now used (for example, `text-right`). Tweaking the implementation a bit to support both types of alignment hints.
> translator-storage: handle additional myst table alignment hints

- CHANGES.rst
- sphinxcontrib/confluencebuilder/storage/translator.py
- tests/unit-tests/datasets/common/image.rst
- tests/unit-tests/test_rst_image.py
When preparing external URI image macros, the `ri:url` values need to be encoded. Updating each `ri:url` entry to ensure their values have been encoded.
> translator: encode uris

- sphinxcontrib/confluencebuilder/publisher.py
If a page is flagged for deletion fails due to the Confluence instance rolling back a failed (transaction) request, attempt to retry the request as the instance may recover and be able to perform the request (over stopping the user's publication request).
> publisher: retry on a rolled back deletion request

- sphinxcontrib/confluencebuilder/publisher.py
- sphinxcontrib/confluencebuilder/storage/__init__.py
- sphinxcontrib/confluencebuilder/storage/index.py
- sphinxcontrib/confluencebuilder/storage/translator.py
- tests/lib/__init__.py
- tests/test_validation.py
Restricting subset of macros is an undocumented feature. It was added to help deal with scenarios with a Confluence instance may have some macros disabled by an administrator; providing a way for users to still generate/publish documentation if a specific macro was disabled.
Newer Confluence instances do not support disabling core macros with standard installs anymore ~ this includes all Confluence instances that are supported by this extension (LTS versions). Since the likelihood that these core macros are never disabled and that this feature was undocumented, removing support for it. This should reduce some implementation to minimize maintenance and validation time.
> drop macro restriction support

- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/config/checks.py
- sphinxcontrib/confluencebuilder/config/defaults.py
- sphinxcontrib/confluencebuilder/config/notifications.py
- sphinxcontrib/confluencebuilder/storage/translator.py
- tests/unit-tests/test_sphinx_toctree.py
The `confluence_adv_hierarchy_child_macro` (undocumented) feature has been deprecated for a couple of releases. Any user wishing to utilize child-macros in their documentation are better served by using raw directives. Removing the configuration and its capabilities from this extension, to help reduce maintenance work.
> drop undocumented child macro injection

- sphinxcontrib/confluencebuilder/storage/translator.py
- tests/lib/__init__.py
- tests/unit-tests/datasets/code-block/code-block-caption.rst
- tests/unit-tests/test_sphinx_codeblock.py
When tracking a caption value to apply to a code block, a check exists to exclude processing this for a parsed literal (since this is not supported). An issue with the initial implementation is that this sanity check used the caption node to sanity check if a node was a parsed literal block, instead of the sibling code block.
This commit corrects the implementation by checking for a parsed literal block type on the sibling.
---
This pull request includes a series of corrections to testing, where the quoted-value caption and encoding issues in unit tests.
> translator: correct code-block's caption check

- tests/lib/__init__.py
Asynchronous tweaks were attempted to be added into unit testing \[1\]. However, the `ThreadingMixIn` implementation was added to the request handler instead of the server instance; correcting.
\[1\]: c9c1ff3fa3d65192d74c66c359ed2d152f192959
> tests: register threading-mix-in on server implementation

- tests/lib/__init__.py
- tests/unit-tests/test_publisher_connect.py
- tests/unit-tests/test_publisher_page.py
The following cleans up a series of publisher-related tests. The main goal is to address the random socket failures observed from CI tests (e.g. [build 6557547345](https://github.com/sphinx-contrib/confluencebuilder/runs/6557547345)).
> cleanup publisher tests

- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/publisher.py
When configured for a dry-run state and a restrict ancestors check is performed, if the root page did not already exist (to be updated), no root page will exist to compiler a list of ancestors on. This causes the extension to issue an invalid API request with a `None` page ID call. Tweaking the restrict ancestors check to be skipped if no root page is detected.
> builder: skip restrict ancestors check on dry-run without existing root

- doc/directives.rst
- doc/roles.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/nodes.py
- sphinxcontrib/confluencebuilder/roles.py
- sphinxcontrib/confluencebuilder/storage/translator.py
- tests/unit-tests/datasets/status/index.rst
- tests/unit-tests/test_confluence_status.py
Providing initial support for user's to add Confluence status macros in their documentation.
> support confluence status macro

- doc/directives.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/directives.py
- sphinxcontrib/confluencebuilder/nodes.py
- sphinxcontrib/confluencebuilder/storage/translator.py
- tests/unit-tests/datasets/confluence-toc/index.rst
- tests/unit-tests/test_confluence_toc.py
Providing initial support for user's to add Confluence table of contents macros in their documentation.
> support confluence toc macro

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/rest.py
- tests/unit-tests/test_publisher_api_bind_path.py
In some corporate environments, a Confluence instance's API endpoint may target a URL which does not include the `rest/api` path. This extension always injected these parts in the path to support common installations; however, this would always break these unique endpoints. This commit introduces a `confluence_publish_disable_api_prefix` option to disable adding the `rest/api` parts in the publish URL.
> support a confluence instance using a non-standard url endpoint

- sphinxcontrib/confluencebuilder/state.py
- tests/unit-tests/test_titles.py
Increasing trimming length over CONFLUENCE_MAX_TITLE_LEN results in failed publishing attempt. Instead, trimming using tail length so that the title won't go over the limit. Signed-off-by: Anton Mihalkov <box4android@gmail.com>
> Fix for going over CONFLUENCE_MAX_TITLE_LEN while handling title conflict

- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/publisher.py
- tests/unit-tests/test_config_checks.py
Initial label support for new pages would include metadata in a "Create content" request. However, only Confluence Cloud's REST API supports providing metadata information in this request type. To support initial label creation on non-Cloud instances, labels will be created for new pages uses a `content/{id}/label` request.
> support labels on new pages on confluence server

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/cmd/wipe.py
- sphinxcontrib/confluencebuilder/config/checks.py
- sphinxcontrib/confluencebuilder/config/defaults.py
- sphinxcontrib/confluencebuilder/config/notifications.py
- sphinxcontrib/confluencebuilder/publisher.py
- tests/unit-tests/test_config_checks.py
- tests/unit-tests/test_publisher_base_id.py
This commit tweaks the `confluence_parent_page` option to accept both a page's title value (original) or a page identifier (added).
> allow parent page to accept page identifiers

- sphinxcontrib/confluencebuilder/rest.py
This extension primarily relies on the Requests module to manage requests to a Confluence instance, which includes secure pipes. Requests relies on embedded certificate information, which may not be ideal for environments which have more updated certificates.
The following applies the internally managed SSL context to always be registered; and if no configuration-provided client certificate is set, certificates will be loaded from default locations for the running platform (via `load_default_certs` \[1\]).
\[1\]: https://docs.python.org/3/library/ssl.html#ssl.SSLContext.load_default_certs
> support loading default local certification authority information

- .github/workflows/build.yml
- tox.ini
Sphinx provides a stable v5.0.x series; adjusting the tox configuration to support the new revision. Following maintenance guidelines, this allows a series of legacy Sphinx revisions to be dropped as well.
See CONTRIBUTING.rst for additional information.
The tox configuration has been adjusted with a new version of Sphinx versions to test against. Adjusting the automated building to invoke these accordingly.
> adjust for new sphinx versions (v5.0.x)

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/config/defaults.py
- sphinxcontrib/confluencebuilder/config/env.py
- sphinxcontrib/confluencebuilder/config/manager.py
- tests/unit-tests/test_config_env.py
Provides a series of changed to help support accepting configuration options from the environment.
A subset of options to be used as a boolean or integer type can be accepted as a string (typically, from command line) and converted after post-processing configuration options. The original implementation defined a list of, for example, boolean configuration options and cycled through these keys to ensured all string-assigned values are converted to boolean types.
A maintenance issue observed is that as boolean options are defined for the extension, development may miss adding these new options into the respective type conversion lists in the "defaults" implementation. To prevent this from happening, rework this extension's configuration processing to help easily track the expected types …
> support providing configuration options from environment

- .github/workflows/docs.yml
- doc/configuration.rst
Recent header/footer configuration documentation entries did not include substitutions for the respective configuration keys; correcting.
> cleanup configuration document

- doc/configuration.rst
Requests supports netrc authentication, but a user may not know exactly how to utilize it with various authentication options for this extension. Add an indication that `confluence_server_user` can be omitted, which would allow Requests to fallback to netrc (if other advanced authentication options are not set).
> doc: provide information about netrc support

- doc/roles.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/nodes.py
- sphinxcontrib/confluencebuilder/roles.py
- sphinxcontrib/confluencebuilder/storage/translator.py
- tests/unit-tests/datasets/emoticon/index.rst
- tests/unit-tests/test_confluence_emoticon.py
Providing initial support for user's to add Confluence emoticons in their documentation.
For example:
```
:confluence_emoticon:`tick`: This is done.
:confluence_emoticon:`cross`: This is incomplete.
```
> support emoticon macro

- doc/configuration.rst
- doc/directives.rst
- doc/guide-math.rst
- doc/install.rst
- doc/roles.rst
- doc/tips.rst
Maintenance work on the documentation:
- Cleanup some grammar.
- Corrects an invalid math-related index entry and add/improve a series of other index entries for the documentation.
> documentation cleanup

- sphinxcontrib/confluencebuilder/cmd/report.py
Adjust the report helper to take into consideration environment-based configuration options.
Since this extension will track explicit configuration options registered by this extension, the report implementation does not need to filter based off a prefix string value. Instead, check if a configuration key exists in the configuration manager before filtering.
> report command improvements

- doc/configuration.rst
- doc/features.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/assets.py
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/config/defaults.py
- sphinxcontrib/confluencebuilder/intersphinx.py
When intersphinx support was added, domains were restricted to only the `std` domain. This extension only has performed limiting testing of its intersphinx capabilities, and the limit was used to help prevent possible issues from trying to processing unknown domain types. In theory though, all domain types would like to be supported, and adding a restriction makes it one extra step to deal with before trying to correct/improve possible issues for intersphinx domains that may not work. Removing the restriction to give users the capability of building an inventory with all domain types. From there, if a user experiences issues linking against a specific domain/reference, that example can be later used as a test case to be addressed in a future version.
When an inventory can be created for …
> extend intersphinx capabilities

- .github/workflows/build.yml
- sphinxcontrib/confluencebuilder/builder.py
- tests/unit-tests/test_config_checks.py
- tox.ini
- tox: adjust for new sphinx versions (v5.1.x)
- workflows: adjust for new sphinx versions (v5.1.x)
> test against Sphinx 5.1.x

- .github/workflows/sphinx-dev-check.yml
- tox.ini
When running the `develop` environment in tox, the following change will allow developers to override the target revision of Sphinx desired by providing a new revision using the `SPHINX_VER` variable.
Providing a new manual job when can enable developers to run a tox run against a specific version of Sphinx. This is to help easily check this extensions capabilities against a specific version of Sphinx without having to locally setup a working environment.
> Provide Sphinx Development Check GitHub manual action

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/assets.py
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/config/__init__.py
- sphinxcontrib/confluencebuilder/config/checks.py
- sphinxcontrib/confluencebuilder/config/notifications.py
- sphinxcontrib/confluencebuilder/publisher.py
- sphinxcontrib/confluencebuilder/rest.py
- tests/test_validation.py
The following attempts to support Confluence Cloud's experiment API of archiving pages. With these changes, users could flag legacy pages to be archived, instead of removed (purged). The new configuration option would be as follows:
```
confluence_cleanup_archive = True
```
This pull request also renames the configuration options as follows (but still supports legacy options for now):
- `confluence_purge` -> `confluence_cleanup_purge`
- `confluence_purge_from_root` -> `confluence_cleanup_from_root`
> support archiving pages

- .github/workflows/build.yml
- .github/workflows/docs.yml
- .github/workflows/validate.yml
- MAINTAINERS.rst
- README.rst
- doc/configuration.rst
- .github: switch workflows to use main branch
- doc: update confluencebuilder branch sourcelink example
- MAINTAINERS.rst: updating contributing link
- README.rst: updating build badge to new branch
> switch to main branch

- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/rest.py
Embedded root certificates provided by requests can cause users more issues when interacting with https-based sites. It should be more common for users environments to have the needed trusted CAs configured in their respective environments. Therefore, we will rely on the SSL module to properly load these stores. Users can still utilize the `confluence_ca_cert` option for explicitly trusting certificates.
In the rare case where users may need to rely on requests-provided certificates, the `confluence_adv_embedded_certs` fallback option can be used to prevent disabling requests certificates (ideally, this should never need to be used).
> rest: default disable embedded certificates from requests

- pyproject.toml
- setup.cfg
Moving dependencies for the project (originally hosted in `setup.py`) from `pyproject.toml` into `setup.cfg`. This is to ensure legacy interpreters can properly install dependencies in their environment when `pyproject.toml` processing is not supported.
Splitting the single line description over multiple lines is not actually used in a built package (the METAFILE will have a '\' description). To support a description to be packaged that does not span the column length too long in the file, we will just minimize the description value.
> correct package management changes

- sphinxcontrib/confluencebuilder/assets.py
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/compat.py
- sphinxcontrib/confluencebuilder/singlebuilder.py
- sphinxcontrib/confluencebuilder/storage/translator.py
- sphinxcontrib/confluencebuilder/transmute/__init__.py
- sphinxcontrib/confluencebuilder/transmute/ext_sphinx_diagrams.py
- sphinxcontrib/confluencebuilder/transmute/ext_sphinx_gallery.py
- sphinxcontrib/confluencebuilder/transmute/ext_sphinx_toolbox.py
- sphinxcontrib/confluencebuilder/transmute/ext_sphinxcontrib_mermaid.py
As of docutils v0.18.1, a node now has a `findall` method (iterator) over a now obsolete `traverse` method (list). This causes users using the more recent docutils to have several deprecated warnings. To help deal with users on newer and older versions, provide a helper call to call `findall` if it is available.
> use docutils node's findall call when available

- sphinxcontrib/confluencebuilder/publisher.py
For environments which enable warnings-as-errors, if a publisher event detects it needs to retry a request, the warning notification will stop the publishing process. These warnings are not helpful to stop on, so instead we will suppress an error trigger if a user has the feature enabled.
> publisher: do not trigger a warning-error for publish retries

- AUTHORS
- MAINTAINERS.rst
- doc/_templates/index.html
- doc/advanced.rst
- doc/install-virtualenv.rst
- AUTHORS: adding new authors
- doc: remove optional hint in home description
- doc: indicate deletion permissions are for purging only
- doc: cleanup links
- MAINTAINERS.rst: cleanup to better reflect new build command
> maintenance (pre-release cleanup 02)

- sphinxcontrib/confluencebuilder/storage/translator.py
When using the Confluence v2 editor, having newlines after anchors may cause unexpected formatting issues. Suppress any newline injection for these macro types in preparation for v2 editor support.
> remove newlines after anchors

- sphinxcontrib/confluencebuilder/cmd/report.py
When generating a report blurb for a GitHub issue, also include the version of docutils being used.
> report: add docutils version to report

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/config/defaults.py
The use of hierarchy mode is a more common configuration (utilizing Sphinx's toctree definition to group/nest documents). It has been discussed for some time that the hierarchy mode should be default enabled -- and with the active development branch planning to a v2.0 release on a next release, the mode is being default enabled.
> default enable hierarchy mode

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/config/checks.py
- sphinxcontrib/confluencebuilder/config/notifications.py
- tests/unit-tests/test_config_checks.py
- tests/unit-tests/test_config_hierarchy.py
The `confluence_max_doc_depth` option has been deprecated for some time. With the development branch planned to be used for a next v2.0 release, this feature is now being removed (as mentioned in previous noticed over the past several releases).
> dropping max-doc-depth

- sphinxcontrib/confluencebuilder/storage/translator.py
An inconsistency has been reported when comparing indentations/offsets between the original (v1) editor and new editor. First, when using a v2 editor, line block types stacked against a paragraph would not have the same spacing compared to the older editor. The use of the div tag does not gracefully work in a v2 editor, and will be switched to a p tag. This should help ensure expected spacing.
Next, for line blocks, the Confluence output should be indented these configured blocks if detected that this are new line blocks inside, for example, a paragraph. While this logic was applied on the v1 editor, the same logic was not used on the v2 editor. We now apply a line-block indentation if the condition is detected.
> improve paragraph indentation/offsets with v2 editor

- sphinxcontrib/confluencebuilder/util.py
The character sanitizer's primary goal is to strip out control characters to prevent issues where Confluence will reject a page update for unsupported characters. The implementation ignored all Unicode characters which had a category leading with `C`. However, this includes format characters which certain users/documents need to properly format text (for example, the Zero-width non-joiner \[1\]).
Adjusting the utility method to only sanitize out control characters found in the `Cc` group.
\[1\]: https://en.wikipedia.org/wiki/Zero-width_non-joiner
> sanitize only non-space unicode control characters

- sphinxcontrib/confluencebuilder/storage/translator.py
- sphinxcontrib/confluencebuilder/transmute/__init__.py
- sphinxcontrib/confluencebuilder/transmute/ext_jupyter_sphinx.py
- sphinxcontrib/confluencebuilder/transmute/ext_nbsphinx.py
The following pull request brings initial support for various nbsphinx/jupyter capabilities.
There was an initial request (#198) to support Jupyter Notebooks which did not fit into the desired maintenance work for the Confluence builder extension. Since late 2021, the Confluence builder extension started to add support for some third-party extensions. With the recent request to support the [Jupyter Sphinx Extension](https://jupyter-sphinx.readthedocs.io/) (#733) and text-support in the nbsphinx last year, the ability to support Jupyter Notebook has improved.
This pull request takes into consideration some implementation suggestion from the work @planetmarshall has [performed](https://github.com/planetmarshall/sphinx-confluence-nbsphinx-test) (e.g. placing prompt values in code block …
> third-party nbsphinx/jupyter support

- doc/features.rst
- sphinxcontrib/confluencebuilder/storage/translator.py
- tests/unit-tests/datasets/code-block-params/code-block-collapse.rst
- tests/unit-tests/test_confluence_code_params.py
- tests/validation-sets/sphinx/code.rst
If a processing literal block builds a code macro, adding support to flag the `collapse` parameter option if the `collapse` class is specified.
---
fyi @senges, best to create new issue entries for new enhancements than update a closed issue when possible. The features/changes you proposed look good, and have been included in this pull request. This should be available next release. Please feel free to comment if there is anything missing.
> support collapse hints for literal blocks

- sphinxcontrib/confluencebuilder/publisher.py
When a configuration specifies a root to publish under (i.e. the `confluence_publish_root` option), ensure any orphan pages that are generated are placed under this group (instead of the root of the configured space).
> place orphan pages under configured publish root

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/config/checks.py
- sphinxcontrib/confluencebuilder/util.py
- tests/unit-tests/datasets/publish-list/folder/page-b.rst
- tests/unit-tests/datasets/publish-list/index.rst
- tests/unit-tests/datasets/publish-list/page-a.rst
- tests/unit-tests/datasets/publish-list/publish-list-default
- tests/unit-tests/test_config_checks.py
- tests/unit-tests/test_config_publish_list.py
Users taking advantage of `confluence_publish_allowlist` may be using this feature to detect which documents have changed to decide what documents are to be published. In such systems, if an allow-list is generated which is empty, the resulting state would be that all documents will be published. This can be counter-intuitive for users of this feature. This commit tweaks the allow list setup where users can configure an empty allow list to indicate no pages will be published.
The default state, `confluence_publish_allowlist` is set to `None` to not use this feature (i.e. all pages can be published). If an empty list is assigned to this value:
confluence_publish_allowlist = []
No documents will be published. This also applies to when using a file:
confluence_publish_allowlist = …
> restrict publishing with empty allow list

- .github/workflows/build.yml
- CHANGES.rst
- README.rst
- doc/conf.py
- pyproject.toml
- tox.ini
Perform a series of maintenance work in preparation for an upcoming release. This includes updated supported Sphinx/Confluence versions, bumping copyright year, expanding project classifiers and updating the changelog.
> maintenance work (early January 2023)

- CHANGES.rst
- sphinxcontrib/confluencebuilder/storage/translator.py
While the `numfig` option hints to supporting number tables if captioned, the translator never attempted to add a number for captioned tables. This commit addresses this by injection a number for table captions.
While the `numfig` option hints to supporting code blocks if captioned, the translator never attempted to add a number for captioned code blocks if the caption is injected into the macro title value. Tweaking the implementation to allow building a numbered caption for these title parameters.
> support numfig for tables and codeblocks

- .readthedocs.yaml
Explicitly indicate to use the most recent Ubuntu image and Python version available. This should allow the most recent version of Sphinx to be installed.
This is based off this error and the RTD logs seems to still default to Python 3.7:
```
ERROR: Ignored the following versions that require a different python version: 6.0.0 Requires-Python >=3.8; 6.0.0b1 Requires-Python >=3.8; 6.0.0b2 Requires-Python >=3.8
```
> .readthedocs.yaml: use newer os/python version

- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/compat.py
- sphinxcontrib/confluencebuilder/singlebuilder.py
As of Sphinx v6.1.x, a series of utility calls have been moved into new locations. Specifically, `progress_message` and `status_iterator` have been moved into a `util.display` module. Tweaking the implementation to use the new imports for Sphinx v6.1.x.
> handle deprecated sphinx 6.1 imports

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/config/checks.py
- sphinxcontrib/confluencebuilder/config/defaults.py
- sphinxcontrib/confluencebuilder/publisher.py
- tests/unit-tests/datasets/orphan/index.rst
- tests/unit-tests/datasets/orphan/pagea.rst
- tests/unit-tests/datasets/orphan/pageb.rst
- tests/unit-tests/test_config_checks.py
- tests/unit-tests/test_config_orphan.py
Provides support for allowing users ways to deal with orphan pages. This includes:
- Allowing users to opt to not publish orphan pages.
- Allowing users to customize where orphan pages will be published.
Orphan pages (published by default) can be disabled by using the option:
```
confluence_publish_orphan = False
```
If users want to configure a page to store orphan pages under, a container option can be set:
```
confluence_publish_orphan_container = 123456
```
As of this extension v2.0, orphan pages respect the configure parent page/root configurations to hold orphan pages. Users who wish to emulate the previous behavior can specifying a container configuration such as:
```
confluence_publish_orphan_container = 0
```
> support orphan page controls

- .github/workflows/build.yml
- sphinxcontrib/confluencebuilder/builder.py
- tox.ini
The following pull request will track effort to support Sphinx v6.1.x+ series.
With the introduction of https://github.com/sphinx-doc/sphinx/issues/11090, the confluencebuilder extension has trouble manipulating the toctree. Specifically, it looks to be a result of the commit https://github.com/sphinx-doc/sphinx/commit/463a69664c2b7f51562eb9d15597987e6e6784cd. The issue is most likely how the confluencebuilder manipulates/caches doctree's on its own (in a not-so-perfect way). We'll have a find an alternative way to address this.
Users who rely on confluencebuilder are recommended to pin to Sphinx v6.0.x series for the interim.
> Support Sphinx 6.1.x

- tox.ini
Python 3.12 has an alpha revision available. Adding an environment to help test this specific interpreter.
> tox: add support for python 3.12.x series

- sphinxcontrib/confluencebuilder/builder.py
For users building with Windows and using `dvisvgm` from MiKTeX, the process may fail when dealing with temporary file locations that do not share a common partition as the output directory.
> ERROR: Windows API error 87: The parameter is incorrect.
The imgmath extension allows a builder to override where temporary files are build -- use this to hint to using a temporary directory on the same partition the output directory to help prevent issues.
> builder: provide tempdir for ext-imgmath

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/publisher.py
When a user configures `confluence_version_comment`, the value used will only show in a page's history for page updates. This is due to the original implementation only populate the version message for page updates. This commit adjusts the implementation to always populate a `version` entry for a page with a configured message value.
Note that new page comments only appear to work on Confluence Cloud. Tests with Confluence server (v7.19.x) does not appear to accept a message value (ignored?).
> publisher: ensure new pages include a configured version comment

- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/storage/translator.py
For `sphinx.ext.linkcode` extension, prospect changes \[1\] will provide support for other Sphinx extensions to take advantage of linkcode-generated references. Updating this extension to hint that it
will support `sphinx.ext.linkcode`. This should help ensure a future release the Confluence Builder extension will automatically be ready to utilize the Sphinx-managed extension (if Sphinx does update to include linkcode support for custom builders).
If Sphinx changes the way of integrating with linkcode or opts to not support such an extension, the introduced line in this commit can be modified or dropped at a later time.
\[1\]: https://github.com/sphinx-doc/sphinx/pull/10585
> enable preliminary linkcode support

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/std/confluence.py
- sphinxcontrib/confluencebuilder/storage/translator.py
- tests/unit-tests/datasets/code-block-fallback/index.rst
- tests/unit-tests/test_sphinx_codeblock_highlight.py
While `confluence_lang_transform` can be used by users to handle or override specific language types, a user may still want to rely on "regular" language types to be processed. Tweaking the use of a configured transform to fallback to the regular language mapping calls if a transform results an empty or `None` value.
Provides an extended map to help provide fallback language types where an "unsupported code language" warning is still desired but an alternative language type is better than a default/"plain" language type. For example, Confluence does not support interactive Python code blocks. A warning should be generated to inform users that their documentation cannot render them (specifically, the interactive part); however, it will be still nice to render the content as Python code …
> code language improvements

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/logger.py
- sphinxcontrib/confluencebuilder/storage/translator.py
- tests/unit-tests/test_sphinx_codeblock_highlight.py
Classify warning messages with a `confluence` hint to allow projects to suppress any extension-generated warnings using `suppress_warnings` \[1\].
In addition, this change includes a `unsupported_code_lang` subtype to allow users to ignore the specific unsupported code language warning.
\[1\[: https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-suppress_warnings
> support warning suppression

- tox.ini
Provides testers a way to test against Sphinx development versions using specific Python interpreter.
Provides an environment to help test "release" builds of the implementation, instead of using the default development mode building.
> introduce new tox interpreter test environments

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/cmd/wipe.py
- sphinxcontrib/confluencebuilder/config/__init__.py
- sphinxcontrib/confluencebuilder/config/checks.py
- sphinxcontrib/confluencebuilder/config/defaults.py
- sphinxcontrib/confluencebuilder/config/notifications.py
- sphinxcontrib/confluencebuilder/publisher.py
- tests/unit-tests/test_config_checks.py
Provides the ability for a user to configure how to search for legacy pages when a cleanup option is configured. When a project is configured to cleanup old documents, this extension will search for any legacy pages found on the Confluence instance. As it uploads new documents (and attachments), it will update the internal list of tracked documents to indicate which ones are active. At the end of the process, the remaining set of documents/attachments are considered legacy and will be cleaned up.
A problem observed is that sometimes Confluence does not always report expected page dependencies through the API. Originally, this implementation would query specific pages descendants; however, after initial testing, not all descendants would always appear. The implementation was switched to …
> configurable cleanup search modes

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/storage/translator.py
- sphinxcontrib/confluencebuilder/translator.py
- tests/unit-tests/test_config_full_width.py
Confluence's v1 editor ignores a full-width page style on publication (most likely since the concept of page width was developed for v2 and newer). To emulate a non-full-width state with a v1 editor, apply a layout around the page contents.
See also #602.
> support "full width" option for v1 editor

- doc/roles.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/roles.py
- tests/unit-tests/datasets/strikethrough/index.rst
- tests/unit-tests/test_confluence_strikethough.py
Providing a role which allows documents to explicitly use Confluence's strikethrough text capability. This is more so for documentation sets which may solely focus on Confluence and a user wants to quickly present content in a strikethrough format. For mixed documentation sets, generic role-based strikethroughs are still recommended.
> provide strikethrough role

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/config/defaults.py
When introducing the ability for users to configure the cleanup search mode \[1\], the default mode was switch from `search` to `direct`, with the assumption that `direct` being the best candidate based on the API's description. However, it has been observed through release testing that Confluence Server/DC versions (e.g. v8.2.1), the API may fail with an "unimplemented" error.
To prevent users from observing this issue with a stock load, restoring the default back to a `search` mode.
\[1\]: 2b6bc487218f6555c74eb1ad61659daeb48707d6
See also: [!758](https://github.com/sphinx-contrib/confluencebuilder/issues/758)
> config: change cleanup search mode back to default

- CHANGES.rst
- README.rst
- doc/conf.py
- tests/validation-sets/sphinx/code.rst
- README.rst: sync eol confluence versions
- doc: sync eol confluence versions
- tests: comment about confluence v8.x issues with cdata code blocks
> maintenance (2023-04-16)

- doc/directives.rst
- doc/features.rst
- doc/guide-collapse.rst
- doc/guides.rst
- sphinxcontrib/confluencebuilder/storage/translator.py
- tests/unit-tests/datasets/collapse/index.rst
- tests/unit-tests/test_confluence_collapse.py
When a document defines a container directive with a `collapse` style, use this as an indication that the content should be wrapped in an expand macro.
Provide a guide on information uses the capabilities when wanting to collapse various content.
> Collapse improvements

- .github/workflows/build.yml
- tox.ini
With the release of Sphinx 6.2.0, updating tox and CI to test against this version.
- tox: adjust for new sphinx versions (v6.2.x)
- workflows: adjust for new sphinx versions (v6.2.x)
> Support Sphinx 6.2.x

- .github/workflows/build.yml
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/directives.py
- tox.ini
A series of maintenance chances:
- builder: add linter exception
- directives: removing unneeded final_argument_whitespace flags
- tox: adjust for new sphinx versions (v7.x)
- workflows: adjust for new sphinx versions (v7.x)
> maintenance (2023-05-07)

- doc/directives.rst
- doc/roles.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/directives.py
- sphinxcontrib/confluencebuilder/nodes.py
- sphinxcontrib/confluencebuilder/roles.py
- sphinxcontrib/confluencebuilder/storage/translator.py
- tests/sample-sets/confluence-card/conf.py
- tests/sample-sets/confluence-card/index.rst
- tests/sample-sets/confluence-card/second.rst
- tests/sample-sets/confluence-card/tox.ini
- tests/unit-tests/datasets/confluence-doc-invalid-doc/index.rst
- tests/unit-tests/datasets/confluence-doc-invalid-layout/index.rst
- tests/unit-tests/datasets/confluence-doc-invalid-width/index.rst
- tests/unit-tests/datasets/confluence-doc/index.rst
- tests/unit-tests/datasets/confluence-doc/second.rst
- tests/unit-tests/datasets/confluence-doc/third.rst
- tests/unit-tests/datasets/confluence-link-invalid-layout/index.rst
- tests/unit-tests/datasets/confluence-link-invalid-width/index.rst
- tests/unit-tests/datasets/confluence-link/index.rst
- tests/unit-tests/test_confluence_doc.py
- tests/unit-tests/test_confluence_link.py
My initial idea on how we could start handling Confluence Smart Links. My intention is to start a discussion around this and maybe collaborate with you (=
It's just a small start since it is not supporting all the possibilities...
One one side, I've thought about having one role for each `data-card-appearance` and deal with the text similar to what Ref does.
Also there's  the possibility to actually use `<ac:link>` tags for the Links still in the editor v2.... I'd imagine we could expand it with that somehow...
Last but not least, I'm not sure this works for editor v1.
Thanks a lot o/
closes #790
> Initial idea to handle Confluence Links

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/publisher.py
- sphinxcontrib/confluencebuilder/util.py
The following attempts to bring support for publishing pages which only need to be updated. Pages are now published with a properly value of the hash value of a page's contents used by this extension. When a future publish event occurs, this hash is used to compare against newer pages. If the hashes match, no new publish attempt will be made for the page.
---
Originally, attempts were made to try to compare the raw contents of pages to determine if a publish event should occur. Investigation showed a series of issues preventing this from gracefully working:
- Confluence may optimize/tweak the storage format provided (e.g. removing or adding closing tags).
- Confluence would inject attributes in macros ('ri:version-at-save'; which can be filtered out, but there may be other attributes to …
> support publishing only pages needing updates

- sphinxcontrib/confluencebuilder/storage/translator.py
Non-inlined cards do not have any node text, which creates a link body that is empty. While Confluence will ignore/remove the empty body on publication, there is no need to add this into prepared pages; cleaning up.
> translator: skip creating link body for non-inlined cards

- sphinxcontrib/confluencebuilder/__init__.py
The `confluence_publish_force` configuration option is a boolean type; however, the option was added using `add_conf` instead of `add_conf_bool`. Correcting.
> config: correct config type for publish-force option

- sphinxcontrib/confluencebuilder/storage/translator.py
Internally, the storage translator uses a `_v2_header_added` flag to track header usage. An issue with this implementation is that if no Confluence header is used, no page generation and no source links; the flag value may not be defined when it may be used in some link checks. To correct this, ensure the flag is initialized in the translation's constructor.
> translator: ensure v2 header flag is defined

- pyproject.toml
The most recent release (v2.1) generated a source distribution package that did not include a license file (reported by @maresb). This was a result of an incomplete switch from setuptools to flit. Correcting this by listing `LICENSE` as a file to include in the source distribution (as well as other desired files).
Also, the use of a desired SPDX license definition does not appear to be the proper usage of the license text field (PEP-621). It also looks that the use of this key as a table is to be deprecated (PEP-639). To remove a possible incorrect license entry and not update the value to a soon-to-be deprecated value, dropping its usage.
See also #805.
> pyproject.toml: add missing files in sdist

- sphinxcontrib/confluencebuilder/publisher.py
Previously, if the 'confluence_editor' was set to v2 and 'confluence_full_width' was set, the v2 setting would not be respected since the dictionary containing it in the metadata field was overwritten. Now both settings will be respected in all permutations.
> 🐛 respect both confluence_editor and confluence_full_width

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/publisher.py
As of v2.1, this extension no longer publishes pages when the content of a page has not changed. This causes some undesired publications when other configuration options change not related to content. To help improve a users experience, we will allow force publishing for a page on the following events:
- If the parent page to publish has changed.
- If there are new global labels missing from the existing page.
- If the configured full-width option has changed.
- If the editor type has changed.
> publisher: force publish on parent/config changes

- sphinxcontrib/confluencebuilder/std/confluence.py
- sphinxcontrib/confluencebuilder/storage/translator.py
- tests/unit-tests/test_config_full_width.py
When adding support for `confluence_full_width` with a v1 editor, the styling used only worked gracefully on Confluence Cloud. For Confluence Server/DC versions, the applied layout does not enforce any maximum width on the contained content.
To improve this feature on Confluence Server/DC, we will use an alternative formatting for page content. Instead, we will opt to using a single div with a maximum width style applied. The maximum width chosen is based on the observed default max-width for macros when using the WYSIWYG editor.
> translator: support v1 limited-page-width on server/dc

- doc/configuration.rst
- doc/directives.rst
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/directives.py
- sphinxcontrib/confluencebuilder/publisher.py
- sphinxcontrib/confluencebuilder/storage/translator.py
- tests/unit-tests/datasets/metadata/index.rst
- tests/unit-tests/test_confluence_metadata.py
- tests/unit-tests/test_publisher_page.py
The following introduces support for a documentation set to provide hints if a specific page should use a specific Confluence editor version as well as whether to override the configured full-width option.
> support page-specific editor/full-width overrides

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/config/checks.py
- sphinxcontrib/confluencebuilder/config/defaults.py
- sphinxcontrib/confluencebuilder/config/notifications.py
- sphinxcontrib/confluencebuilder/storage/translator.py
- tests/sample-sets/raw-html/conf.py
- tests/sample-sets/raw-html/index.rst
- tests/sample-sets/raw-html/second.md
- tests/sample-sets/raw-html/tox.ini
The following introduces the option `confluence_permit_raw_html` to allow users to force-publish documents with raw HTML content in them. While the use of this option will be unofficially supported, it is being added solely since users keep requesting such a capability.
We unofficially supported some level of this using an undocumented configuration option `confluence_adv_permit_raw_html`, but instead we have renamed the option to `confluence_permit_raw_html` and have added it into the configuration documentation (for users to easily find).
In addition, we have also tweaked the capability to also accept the name of an HTML macro definition. This can allow users to place raw HTML in a supported HTML macro (if enabled on their Confluence instance). While this option is also still considered …
> introduce permit-raw-html option

- doc/_themes/sphinx13b/static/sphinx13b.css
- doc/configuration.rst
- doc/guide-class-hints.rst
- doc/guides.rst
- sphinxcontrib/confluencebuilder/config/notifications.py
- sphinxcontrib/confluencebuilder/std/confluence.py
- sphinxcontrib/confluencebuilder/storage/translator.py
- tests/unit-tests/datasets/code-block-theme/index.rst
- tests/unit-tests/test_sphinx_codeblock.py
Provides support for individual code blocks to be configured with a custom Confluence theme. The translator will now process class hints on literal blocks for a `confluence-theme-<theme>` pattern. For example:
```
.. code-block:: python
:class: confluence-theme-FadeToGrey
def main():
print 'Hello, world!'
if __name__ == '__main__':
main()
```
> Support code theme on individual directives

- sphinxcontrib/confluencebuilder/storage/translator.py
Provides partial support when using the sphinxnotes-strike extension. This adds node support to ensure content can be striked; however, there is no immediate way to enable the generation of these nodes in sphinxnotes-strike for the Confluence builder.
> support sphinxnotes-strike extension

- CHANGES.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/exceptions.py
- sphinxcontrib/confluencebuilder/publisher.py
- sphinxcontrib/confluencebuilder/storage/translator.py
In some Confluence instances, there was a window where pages could not be uploaded since Confluence would refuse the EOF sequence for CDATA blocks. This workaround can help a user get their content published at the unfortunate tweak of changing any trailing EOF CDATA blocks to have a space character included.
> cdata workaround for confluence 8.0.x to 8.2.x

- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/config/checks.py
- sphinxcontrib/confluencebuilder/util.py
- tests/unit-tests/test_config_publish_list.py
When a relative path publish list is provided in a configuration, look for the file from within the source directory (which is the expected location when this feature was introduced). This should prevent issues when invoking a Sphinx build from outside a project's source directory.
> Support relative publish list

- sphinxcontrib/confluencebuilder/config/checks.py
- sphinxcontrib/confluencebuilder/config/defaults.py
- sphinxcontrib/confluencebuilder/config/validation.py
When this extension performs a configuration check for a CA certificate, the check will pass if either the absolute path exists or that a relative path based on the project's source directory exists. However, after checking if the file exists, it passes the raw file into Requests which may not be able to resolve a relative path. To prevent issues, always determine the absolute path of the CA file/directory before providing it to Requests.
> Resolve relative CA file for requests

- sphinxcontrib/confluencebuilder/nodes.py
- sphinxcontrib/confluencebuilder/storage/translator.py
When accessing Confluence-extension's tracked parameters on custom nodes, always fetch this information by accessing the `attributes` attribute and using the Confluence parameter key. This is required since a helper `params` attribute may not be guaranteed to be copied by Sphinx when in the translation stage \[1\].
\[1\]: https://github.com/sphinx-doc/sphinx/blob/76658c49a931745da45fa4d5c8d482b7c6facd4f/sphinx/util/nodes.py#L633
> explicit confluence-parameters fetch for confluence nodes

- CHANGES.rst
- doc/_themes/sphinx13b/theme.conf
- tox.ini
- tox: adjust for new sphinx versions (v7.1.x; v7.2.x)
> Maintenance (2023-08-19)

- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/config/env.py
- sphinxcontrib/confluencebuilder/env.py
- tests/lib/__init__.py
- tests/unit-tests/test_cache.py
- tests/unit-tests/test_legacy_pages.py
The following provides a series of corrections and improvements towards this extension tracking outdated pages and managing/tracking publication information to help manage cleanup processes when only subset of pages are updated.
Part of the problem with this extension's original implementation is that lack of consideration for Sphinx's documentation cache. In most use cases, the `-E` argument was used/promoted to start with a clean environment to ensure all documents are processed and published. For uses who did not force a clean environment would see unexpected results, mainly when cleanup options were enabled. Specifically, after publishing documentation, a re-publish of new documentation with a subset of changes could make some valid-but-not-updated pages be removed.
This commit should …
> Rework build caching

- sphinxcontrib/confluencebuilder/builder.py
When determining legacy pages when purging, the base identifier used is either the parent container or a configured root page. When configured to purge from root and the root page does not yet exist, this can give a misrepresentation of what legacy pages are detected when a parent page is also configured.
This commit changes this by force using the detected root page as the cleanup root. And if the cleanup root does not exist, a `None` root will result in an empty legacy pages set (which is expected).
> allow empty legacy pages set for new root content

- sphinxcontrib/confluencebuilder/exceptions.py
While this extension tries to provide a descriptive error statement to help users understand a failed scenario, it may be good to relay the exact HTTP code for select events to provide users more feedback on the state of things. This can be useful for advanced users who only want to see the associated code with the instance they are interacting with.
> add http codes to error messages

- sphinxcontrib/confluencebuilder/config/validation.py
- sphinxcontrib/confluencebuilder/util.py
- tests/unit-tests/test_util_str2bool.py
For a boolean configuration entry, accept an integer representation of 0/1 to be used to represent a false/true state. This extension already accepted these values as string value, and allowing their integer variant should make things more flexible for users (if they desire).
> config: flexible boolean processing from int value

- sphinxcontrib/confluencebuilder/storage/translator.py
- tests/lib/testcase.py
- tests/unit-tests/datasets/rst/figure-caption/index.rst
- tests/unit-tests/test_rst_figure.py
> Issue #854 Fix image (uml) captions with emphasis

- .github/workflows/build.yml
Updating the build workflow to ensure each supported Sphinx version under Python 3.12 is tested.
In addition, this commit drops the the OSX/Windows tests on Python 3.11 since (ideally) the Python 3.12 tests should be enough; and bumping the linting tests to run on the most recent version of Python.
> workflows: expand/tweak test jobs

- sphinxcontrib/confluencebuilder/std/confluence.py
- sphinxcontrib/confluencebuilder/storage/translator.py
- tests/validation-sets/restructuredtext/csv-table.rst
When using CSV tables with width hints, the v2 editor looks to ignore the percentages applied on the column tags. However, if we provide an explicit data width value on the table, percentages are taken into consideration.
This commit tweaks the tables in v2 editor so that if column widths are detected, we apply the default width typically given to a table in the v2 editor to help allow column hints to work.
> support csv width hints in v2 editor

- doc/configuration.rst
It appears on Confluence Cloud, trying to convert a v2 editor page to a v1 editor page may not always work. Provide a notice to a user of this situation, and the workaround to delete the page if they are looking to downgrade.
> doc: provide hint on editor change needing a page delete

- sphinxcontrib/confluencebuilder/publisher.py
- tests/test_sandbox.py
If a user is running a sandbox session without interactive support to trigger new raw-upload attempts, an EOF error will be triggered on the `input()` request. Handle this error gracefully by shutting down the sandbox raw-upload session.
When publishing a page, relax the requirement to defining some keys for a page (e.g. if a page has an explicit `full-width` value). This is to help certain developer builders (e.g. sandbox mode) which may not explicitly configure these values for a page, and do not care what defaults are applied.
> Sandbox raw upload tweaks

- tests/validation-sets/sphinx/production-list.rst
It appears that Confluence's use of `pre` tags no longer injects code lines for the content. This means rendered production lists no longer have the undesired code lines. Removing this limitation notice.
> validation: remove comment on production lists and code lines

- tests/test_validation.py
- tests/validation-sets/base/index.rst
Adjust the widths for validation pages to be collapsed width by default. This makes all v1 pages render in the smaller-width environment, providing a similar look to the v2 pages.
Although, we place an exception for the leading page based on how we present the editor choice and custom widths for images used.
When rendering images on the base page for both editors, users will typically click on the images to jump to an editor selection, instead of the header link. This causes the images to expand ~ where users then unexpand then click on the header links.
While ideally users can click on these images to jump to the respective editor document pages, Sphinx/docutils does not support processing document links in the image's `target` option.
To deal with this scenario, we inject a custom …
> Validation set cleanup

- sphinxcontrib/confluencebuilder/storage/translator.py
When processing individual documents through a translator, a v2 flag is used to help easily indicate if the page is expected to be rendered in a v1 or v2 editor. While the flag worked based on the global configuration setting the editor, if any page-specific overrides are configured in the meta directive, this could cause the flag to be incorrect set for a document.
This commit moves the helper flag to be configured after processing the metadata for a document, ensuring v2 is set considering both the global configuration value and the page-specific override value.
> translator: correct v2 support tracking for documents

- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/storage/translator.py
- tests/sample-sets/header-links/conf.py
- tests/sample-sets/header-links/index.rst
- tests/sample-sets/header-links/md-v1-first.md
- tests/sample-sets/header-links/md-v1-second.md
- tests/sample-sets/header-links/md-v2-first.md
- tests/sample-sets/header-links/md-v2-second.md
- tests/sample-sets/header-links/rst-v1-first.rst
- tests/sample-sets/header-links/rst-v1-second.rst
- tests/sample-sets/header-links/rst-v2-first.rst
- tests/sample-sets/header-links/rst-v2-second.rst
- tests/sample-sets/header-links/tox.ini
- tests/unit-tests/test_rst_targets.py
The following provides a somewhat major rewrite on the creation of anchors and how pages can link to these anchors. There has been some limitations with linking to anchors when support for the v2 editor was added. Ideally, pages will generate an `ac:link` macro and specify anchors to target. However, testing showed that anchor links would not always work with these macros since the macro expected anchors to be prefixed with a page's name, which is not the case for v2 pages.
This commit attempts to fix these by building compatible anchor links on pages no matter what editor version is configured for a page. This extension now calculates expected targets for each document no matter the editor (with an appropriate target expected for auto-generates identifiers). When anchors are now added to …
> Improve anchor links

- LICENSE-3RD-PARTY
- doc/_templates/index.html
- doc/_templates/indexsidebar.html
- doc/_themes/sphinx13b/layout.html
- doc/_themes/sphinx13b/static/sphinx13b.css
- doc/conf.py
- pyproject.toml
Moves the license text for used Sphinx implementation inside its own license file (`LICENSE-3RD-PARTY`). The goal is to help make it easier to identify third-party-related license information associated to this repository (third-party project name, origin of their license and their license text).
> Separate third party license

- sphinxcontrib/confluencebuilder/cmd/report.py
When users generate a report of their environment/configuration, also include the version of urllib3 used. This can be useful in identifying issues with specific versions of urllib3 that Requests will use.
> report: add urllib3 version to report

- .github/workflows/confluence-publish-check.yml
This commit renames the original "validate/publish" workflow to a Confluence publishing workflow. This is to make it clear that this is specific to publishing test results to a Confluence instance and not related to publishing to PyPI.
> .github: renaming the confluence publish check workflow

- sphinxcontrib/confluencebuilder/builder.py
Before attempting to cleanup any detected legacy pages from a target Confluence instance, the builder will check to see if any unchanged documents exist (pages that did not trigger an update and we not removed from the internal legacy list), and remove them from the legacy pages list if our cache detects it was already published. However, this logic assumes we have populated a legacy pages list ahead of time, which may not have happened if we are not configured for any cleaning.
This commit adjusts the unchanged pages check to only occur if we have populated a legacy pages list to check on.
> builder: avoid unchanged page cache checks if we have legacy pages

- sphinxcontrib/confluencebuilder/exceptions.py
- sphinxcontrib/confluencebuilder/publisher.py
- tests/lib/__init__.py
- tests/unit-tests/test_publisher_api_bind_path.py
- tests/unit-tests/test_publisher_base_id.py
- tests/unit-tests/test_publisher_connect.py
- tests/unit-tests/test_publisher_page.py
The following refactors how the initial connection check is performed. The original design introduced back in v0.6 used the "Get spaces" API endpoint to validate access to a space. As the author of this change, I could not recall the specifics of why it was chosen over "Get space" (either an overlooked API call, possible issues observed when testing initial REST support, etc.). At this time, there is no known reason why a switch to the "Get space" API cannot be done. The new call appears to work find for both Cloud and data server versions. Therefore, this commit is making this change.
The switch to the explicit space API endpoint simplifies the publishers logic. We no longer perform a related space key check (back in the day where users may have added the Confluence name instead of space …
> publisher: simplify initial connection check

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/config/checks.py
- sphinxcontrib/confluencebuilder/config/defaults.py
- sphinxcontrib/confluencebuilder/config/notifications.py
- sphinxcontrib/confluencebuilder/config/validation.py
- sphinxcontrib/confluencebuilder/debug.py
- sphinxcontrib/confluencebuilder/publisher.py
- sphinxcontrib/confluencebuilder/rest.py
- tests/lib/__init__.py
- tests/unit-tests/test_config_env.py
Adjusting the internals for performing session requests inside the Rest helper class. This is to help prepare the implementation for future work which can help debugging using prepared requests, as well as preparing for adjustments for APIv2, which deviates from the "bind path" used in this implementation.
Introduce a configuration check where a value will attempt to map to a specific enumeration type. This is to support future configuration capabilities which will try to map string values to enums.
Updating the `confluence_publish_debug` option to now accept string values, used to make to specific debugging enumeration flags in the implementation. This is to prepare for additional debugging modes that can be enabled when publishing.
The unit test used to debug processing a boolean type …
> Extended publish debugging

- .github/workflows/publish-pypi.yml
Adding a workflow to help automatically generate a release and publish it to PyPI.
> .github-workflows: introduce pypi publisher

- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/config/checks.py
- sphinxcontrib/confluencebuilder/config/validation.py
- sphinxcontrib/confluencebuilder/util.py
- tests/unit-tests/test_config_checks.py
- tests/unit-tests/test_config_header_footer.py
- tests/unit-tests/test_config_publish_list.py
- tests/unit-tests/test_sdoc_genindex.py
- tests/unit-tests/test_sdoc_modindex.py
- tests/unit-tests/test_sdoc_search.py
For various configuration options, sanity checks for path-related options would require values to be string values. If a user defined these values using PathLib, a configuration exception would be thrown (and a user would have to workaround by explicitly str-casting the values). To be flexible for these configurations, ensure all path-related options can accept both `str` or `os.PathLike` typed entries.
> Accept path-like configuration options

- sphinxcontrib/confluencebuilder/__main__.py
- sphinxcontrib/confluencebuilder/assets.py
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/cmd/build.py
- sphinxcontrib/confluencebuilder/cmd/report.py
- sphinxcontrib/confluencebuilder/cmd/wipe.py
- sphinxcontrib/confluencebuilder/config/checks.py
- sphinxcontrib/confluencebuilder/config/defaults.py
- sphinxcontrib/confluencebuilder/env.py
- sphinxcontrib/confluencebuilder/logger.py
- sphinxcontrib/confluencebuilder/storage/index.py
- sphinxcontrib/confluencebuilder/storage/search.py
- sphinxcontrib/confluencebuilder/storage/translator.py
- sphinxcontrib/confluencebuilder/svg.py
- sphinxcontrib/confluencebuilder/translator.py
- sphinxcontrib/confluencebuilder/transmute/ext_sphinx_toolbox.py
- sphinxcontrib/confluencebuilder/util.py
- tests/unit-tests/test_cache.py
- tests/unit-tests/test_legacy_pages.py
- tests/unit-tests/test_translator.py
This is a continuation of effort done by #886. This completes the desired effort at utilizing the pathlib module for various path-related capabilities. This also has the bonus of removing all path-related warnings generated when using ruff (ideally, later to be used by default over other linters).
- adjust mainline args to use pathlib
- logger: manage tracefile using pathlib
- util: update context-supported temp_dir to use pathlib
- translator: adjust doc-path processing (internal links) to use pathlib
- transmute: adjust sphinx-toolbox docname mocking to use pathlib
- adjust search/index page processing to use pathlib
- adjust asset processing to use pathlib
- adjust configuration processing to use pathlib
> Use pathlib (Part 2)

- tests/test_validation.py
This commit increases the connection timeout for validation testing from ten seconds to thirty seconds. It has been observed when testing the Confluence Cloud may take a bit longer to process large requests (e.g. may be busy to delaying interaction), and could trigger a timeout. Using the increased time seems to resolve any issues when testing.
> tests: boost validating testing timeout

- requirements_types.txt
- tox.ini
Provides support to run the Mypy static type checker through tox.
Not in a passing state at this time, so the environment will not be enabled by default just yet.
> tox: introduce a mypy environment

- AUTHORS
- pyproject.toml
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/assets.py
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/compat.py
- sphinxcontrib/confluencebuilder/singlebuilder.py
- AUTHORS: updating authors
- enforce minimum sphinx v6.1 support
- correct comment spelling
- builder: drop legacy builder constructor
- drop legacy progress-msg/status-iterator calls
> Maintenance (2024-02-26)

- sphinxcontrib/confluencebuilder/logger.py
- sphinxcontrib/confluencebuilder/svg.py
- sphinxcontrib/confluencebuilder/translator.py
Remove all legacy cases of handling IOError, since this is no longer required on the Python versions this extension supports.
> drop legacy IOError handling

- tests/lib/__init__.py
When populating an output directory for a unit test, build the path taking into consideration the active tox environment name (if any). If one is set, use the environment name as a sub-folder to place between the output folder and a container/test-method name. This should prevent any issues between various unit tests running, where each environment is separated.
> tests: provide a unique output path to support parallel tox runs

- sphinxcontrib/confluencebuilder/config/validation.py
The enumeration check for a string type can help ensure a provided string matches to a specific enumeration type. However, if a user defines a non-string value, the configuration check will fail with an attribute error. To prevent this exception cause so we can manage our own configuration error, also include `AttributeError` to the exception list to capture.
> config: capture non-str value error for enum check

- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/cmd/report.py
- sphinxcontrib/confluencebuilder/intersphinx.py
- sphinxcontrib/confluencebuilder/rest.py
- sphinxcontrib/confluencebuilder/singlebuilder.py
- sphinxcontrib/confluencebuilder/state.py
- sphinxcontrib/confluencebuilder/storage/translator.py
- sphinxcontrib/confluencebuilder/transmute/__init__.py
- tests/__main__.py
- tests/lib/__init__.py
- tests/test_validation.py
- tests/unit-tests/test_config_postfix_formatting.py
- tests/unit-tests/test_sphinx_image_candidate.py
Updating various implementation to take advantage of f-strings over the use of printf (UP031) and format (UP032). This includes also tweaks to original format calls to use variables for some complex values, as well as even dropping format calls for simple string concatenation.
> utilize f-strings

- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/config/__init__.py
- sphinxcontrib/confluencebuilder/config/validation.py
- sphinxcontrib/confluencebuilder/directives.py
- sphinxcontrib/confluencebuilder/publisher.py
- sphinxcontrib/confluencebuilder/rest.py
- sphinxcontrib/confluencebuilder/state.py
- sphinxcontrib/confluencebuilder/storage/translator.py
- tests/lib/__init__.py
Updating a series of implementation around the handling and raising of exceptions. Specifically, these changes aim to:
- Avoid using raw strings to avoid excessive traceback content (EM101).
- Use exception chaining when possible.
- Remove unneeded parenthesis for no-argument raises.
> update exception usage

- sphinxcontrib/confluencebuilder/config/defaults.py
- tests/unit-tests/test_config_checks.py
When a user sets `confluence_publish_debug` to an empty string, such a configuration state should indicate to not perform any publish debugging. However, with the value set, the configuration handling will result in an unexpected exception. Adjusting the implementation to properly handle this case.
> config: handle empty-str publish-debug

- sphinxcontrib/confluencebuilder/config/validation.py
Cleaning up the instance checking when sanity checking a boolean value. This simplifies an instance check and also removed an unneeded instance check.
> config: cleanup bool cfg validation

- sphinxcontrib/confluencebuilder/config/validation.py
- tests/unit-tests/test_config_checks.py
Adding a series of tests to help improve coverage of configuration-related implementation.
> Adding config coverage

- tests/unit-tests/test_report_builder.py
Defines a simple unit test that requests the creation of a report builder. This is to help ensure that this mocked builder has no issues in loading with the active Sphinx version.
> tests: add unit test to validate report builder initialization

- tests/unit-tests/test_rst_admonitions.py
Adding a series of tests to validation the expected output of admonitions when configured with a v2 editor.
> tests: adding unit tests for v2 admonitions

- tests/unit-tests/datasets/rst/doctest-block/index.rst
- tests/unit-tests/test_rst_doctest_block.py
Adding a series of checks to validation the expected output of reStructuredText's doctest blocks.
> tests: adding rst doctest block tests

- tests/unit-tests/datasets/todo/index.rst
- tests/unit-tests/test_sphinx_todo.py
Adding a test to validate the expected use of Sphinx's todo directives. This includes ensuring they only render when enabled, as well as ensuring an informational block is created when they are enabled.
> tests: adding sphinx-todo extension directives test

- sphinxcontrib/confluencebuilder/exceptions.py
- sphinxcontrib/confluencebuilder/publisher.py
Provide a more helpful message on an initial 404 error message. If the first request fails with a 404, aside from a bad URL, this could also mean a bad/restricted space. Try to convey to the user that this extension is not aware which specific reason the request failed, but give more options to say to check a combination of the server URL, the space ID and authentication options.
> publisher: adding more helpful unknown confluence instance exception

- sphinxcontrib/confluencebuilder/cmd/report.py
After extracting raw configuration information for a report, apply the default/internal configurations before attempting to publish. This will ensure various options are resolved (e.g. debugging options) which are assumed to be properly setup before processing the publish logic.
> report: apply default configuration before publish attempts

- doc/configuration.rst
Adds a warning to documentation, warning users about sharing logs that have publish-debug logs enabled.
> doc: add warning about enabling publish-debug opt and sharing

- doc/conf.py
- doc/features.rst
- doc/guide-confluence-macros.rst
- doc/guides.rst
- doc: bump copyright year
- doc: update features with consideration of v2 editor
- doc: provide guide on custom confluence macros
> Documentation updates (tweaks and macro guide)

- sphinxcontrib/confluencebuilder/storage/translator.py
- tests/sample-sets/next-prev/conf.py
- tests/sample-sets/next-prev/index.rst
- tests/sample-sets/next-prev/page-1.rst
- tests/sample-sets/next-prev/page-2.rst
- tests/sample-sets/next-prev/page-3.rst
- tests/sample-sets/next-prev/tox.ini
A previous maintenance update \[1\] broke a nav-node check used to help
form proper header/footer sections; correcting.
\[1\]: f033d213885a21685af5b67b3b221a81073ac16a
> translator: correct navnode check for reference building

- sphinxcontrib/confluencebuilder/exceptions.py
Switching the unknown-instance exception to wrap `set` values with parenthesis over angle brackets. This is to prevent masking these values if a user attempts to post the output in a GitLab issue without wrapping in a code block.
> exceptions: do not wrap "is-set" with angle brackets

- sphinxcontrib/confluencebuilder/cmd/report.py
- sphinxcontrib/confluencebuilder/rest.py
Updating all REST calls performed to have an `Accept` header using a `application/json; charset=utf-8` value. This extension expects only UTF-8-encoded JSON data, and it is best to provide this feedback to a target Confluence instance or proxy.
Since this extension's REST client has been updated to indicate we only support JSON, a manifest request to Confluence will now return JSON data over XML. Updating to report logic to parse using JSON instead.
> Set Accept header in REST calls

- sphinxcontrib/confluencebuilder/cmd/report.py
- sphinxcontrib/confluencebuilder/publisher.py
- sphinxcontrib/confluencebuilder/rest.py
- tests/unit-tests/test_config_prev_next.py
- tests/validation-sets/sphinx/assets/example.py
- tox.ini
- tests: add leading comment in example
- rest: only close session if it was created
- report: do not wrap url-removed hint with angle brackets
- tox: bump ruff to v0.3.3
- switch to f-strings
> Maintenance (2024-03-16)

- sphinxcontrib/confluencebuilder/builder.py
- tests/unit-tests/datasets/local-toc/index.rst
- tests/unit-tests/datasets/local-toc/rst-v1.rst
- tests/unit-tests/datasets/local-toc/rst-v2.rst
- tests/unit-tests/test_local_toc.py
When a page is configured to render a v2 editor content, instead of stripping out spaces for anchor links, replace spaces with dashes. This appears to be the expected ID generation pattern for v2 editor on Confluence Cloud.
> builder: replace header spaces with dashes with v2 editor

- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/builder.py
When a page is configured to be published with a v2 editor, check if any anchor links contain a parenthesis value. If so, replace the expected target value with a manipulated value which works around an issue (JST-937603) where parenthesis will remove an anchor link.
This change also introduces an internal configuration entry `confluence_adv_disable_confcloud_74698`, which disables this workaround (if the situation arises where Confluence Cloud corrects this issue and this applied workaround breaks user's documentation; a quick method for users of this extension to deal with this until a next release).
See also: https://support.atlassian.com/requests/JST-937603/
> builder: add workaround for v2 parenthesis anchor links

- sphinxcontrib/confluencebuilder/config/notifications.py
- tests/unit-tests/test_config_checks.py
Adding configuration checks that will throw a warning if a password or token value is detected to be wrapped in quotes. This is to help inform users who may be passing in password/token values through shell scripts, environment variables or more; which may have a risk of being nested in quotes by accident.
> config: add auth value quote checks

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/cmd/report.py
- sphinxcontrib/confluencebuilder/config/checks.py
- sphinxcontrib/confluencebuilder/config/defaults.py
- sphinxcontrib/confluencebuilder/config/exceptions.py
- sphinxcontrib/confluencebuilder/config/notifications.py
- sphinxcontrib/confluencebuilder/publisher.py
- sphinxcontrib/confluencebuilder/rest.py
- sphinxcontrib/confluencebuilder/std/confluence.py
- sphinxcontrib/confluencebuilder/util.py
- tests/test_validation.py
- tests/unit-tests/test_config_checks.py
- tests/unit-tests/test_publisher_api_prefix.py
- tests/unit-tests/test_publisher_page.py
Providing support for Confluence Cloud REST v2 APIs.
- This moves the API path prefix logic from a `Rest` class into a `Publisher` class.
- Introduces a new configuration option `confluence_api_mode` to configure which mode to use; otherwise it defaults to using `v2` for Confluence Cloud variants, or `v1` for everything else.
- The option `confluence_publish_disable_api_prefix` has been deprecated over a new option `confluence_publish_override_api_prefix`, allowing API version-specific prefix overrides.
- Updating a series of deprecated API calls with their new v2 compatible calls.
> Support REST v2 API Calls

- sphinxcontrib/confluencebuilder/config/defaults.py
When processing a user-provided global labels list, strip out any empty label identifiers that may have been added to the list. This can help avoid forming bad requests later during publishing which may not be obvious to a user why this may be happening.
> config: remove empty global labels

- sphinxcontrib/confluencebuilder/rest.py
When dumping header debug prints to standard output, flush this output to prevent standard error events from making the resulting output hard to interpret.
> rest: flush header debug prints

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/config/checks.py
- sphinxcontrib/confluencebuilder/config/exceptions.py
- sphinxcontrib/confluencebuilder/storage/templates/domainindex.html
- sphinxcontrib/confluencebuilder/storage/templates/domainindex_v2.html
- sphinxcontrib/confluencebuilder/storage/templates/genindex.html
- sphinxcontrib/confluencebuilder/storage/templates/genindex_v2.html
- sphinxcontrib/confluencebuilder/storage/templates/search.html
- sphinxcontrib/confluencebuilder/storage/translator.py
- tests/unit-tests/test_config_checks.py
Allows a user to configure `confluence_page_generation_notice` with a custom message, which can be used instead of the embedded string for the added "page is generated" message.
> support custom page generation notice

- sphinxcontrib/confluencebuilder/builder.py
Select anchor links for a v2 editor are manipulated when published (e.g. when links contain parenthesis). A workaround for specifically parenthesis was previously added \[1]\, but additional characters exhibit the same issue (https://github.com/sphinx-contrib/confluencebuilder/issues/908). An improved approach appears to work if the entire target is URL encoded.
\[1\]: 41a099e35d7bc91f83b0ca9222b567c2696fdb46
> builder: improve workaround for v2 editor anchor links

- sphinxcontrib/confluencebuilder/util.py
When a URL is defined by a user, this extension will help strip off the API sub-folder path commonly used by Confluence. This is since this extension manages which API version to call (and also allows users to override). While we strip the v1 API post-fix, we do not do the same if an API v2 post-fix was added. Updating the logic to strip both v1 and v2 API path entries.
> util: strip api v2 url

- doc/advanced.rst
- doc/tips.rst
The command for wiping a space is more of an advanced user case then a generic tip. Moving the section into a more appropriate location.
> doc: move space wiping from generic tips into advanced

- sphinxcontrib/confluencebuilder/__init__.py
This extension opted towards not registering directives, nodes and roles into the Sphinx application in order to be flexible for users opting to use directives/roles without `only` directive protection. This could result in exceptions being raised when a translator (such as `html`) could not processing a generated Confluence node type.
However, this also causes issues for unique builders such as Sphinx's linkcheck builder or sphinxcontrib.spelling [1], where warnings are generated for unknown directives/roles, making it hard to know if a build is failing for either a bad-link/spelling versus the use of an unknown directive/role.
In attempts to be even more flexible, this extension will permit the registration for these entities when it detects that an active builder has no translator …
> allow registering entities for non-translating builders

- doc/features.rst
Provides a litter blurb for users to indicate how Markdown is supported, and what limitations exist.
> doc: indicate support for markdown via myst-parser

- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/transform.py
Supports registering hyperlinks for custom Confluence node types such as card links.
> support linkcheck for confluence-specific href nodes

- sphinxcontrib/confluencebuilder/storage/index.py
Index pages should be using a specific template based on whether a version one or version two editor is used. The conditional check to determine this is incorrect, and would always default to `v2` when an editor was configured. Updating to explicit check for the `v2` value.
> correct editor check for index pages

- sphinxcontrib/confluencebuilder/storage/search.py
The search macro generated for a search page should be using the configured space key as the target space to search on. However, when updates to this extension's configuration options were changes to identify the option as a "key" over a "name", the search template was not updated to use this value. This would result in the space value being assigned to `None`; correcting.
> correct space key usage for generated search

- sphinxcontrib/confluencebuilder/storage/search.py
- sphinxcontrib/confluencebuilder/storage/templates/search_v2.html
Adjusts the generated search page template to support center-aligning the search box. This is subjectively a nicer presentation.
> center align generated search page

- doc/features.rst
Dropping the notice of SVG issues when using the v2 editor. Confluence Cloud appears to have updated their implementation to address previously observed rendering issues.
> doc: drop note about svg issues in v2

- README.md
- doc/conf.py
Confluence versions before 7.18 have reached end-of-life and will not be tested in next release cycle system tests; updating to the oldest version supported.
> Bump supported Confluence version

- babel
Adjust the babel helper script to compile fuzzy translations by default. Messages for this extension are not that strict to block, and there appears to be some false-positive flagging of fuzziness in some environments.
> babel: allow fuzzy compiling

- README.md
Some links use a single dash where some uses an em dash; updating all to use em dashes to be consistent.
> README.md: consistent em dashes

- README.md
- requirements_dev.txt
There is no need to explicitly include Sphinx or Requests in the development requirements, since this project (`pyproject.toml`) defines these dependencies.
This extension enforces a Requests v2.25 release. However, the README indicates v2.14; correcting.
> Cleanup requirements

- sphinxcontrib/confluencebuilder/storage/translator.py
- tests/unit-tests/datasets/rst/math/index.rst
- tests/unit-tests/test_rst_math.py
Corrects a regression in anchor links observed with the v1 editor, where links to math labels and autodocs would not build an expected anchor in various paragraphs.
Provides method to help automatically build anchors for a node which define identifiers through an `ids` entry.
When building anchors for a paragraph, use the `ids` entries over `names` since the names list appears to be a subset of the identifier list (not an expert on docutils; ids may be populated partially from the names entries). Building anchors with identifiers helps resolve some missing targets when building documentation with autodocs.
Adds a unit test for checking the creation of math images. Testing also ensures that an expected anchor link is created for labeled directives.
> Restore missing anchor links (autodocs and math)

- sphinxcontrib/confluencebuilder/storage/translator.py
- tests/sample-sets/autodocs/autodocs.rst
- tests/sample-sets/autodocs/autosummary.rst
- tests/sample-sets/autodocs/conf.py
- tests/sample-sets/autodocs/index.rst
- tests/sample-sets/autodocs/src/Hello.py
- tests/sample-sets/autodocs/src/func.py
- tests/sample-sets/autodocs/tox.ini
The following commit simplifies the markup content generated for autodocs related nodes. Attempts to gracefully format with various workarounds (e.g. nesting with panels and layouts) seems to constantly change as Confluence updates its ADF processing. There does not appear to be a perfect way to layout autodocs content -- so we will no longer try (that much). We will rely on panels for now (since it appears the only way to do some level of block indentation of content without borders/colors), and all other field entries will be just added into simple paragraphs. This allows the content to be somewhat readable for users and does not add a lot of tags that makes the viewing experience slow on v2 editors.
We can look at this in the future if there are either alternative ways to render …
> translator: simplify v2 autodocs renderings

- sphinxcontrib/confluencebuilder/storage/translator.py
Ensures when using the v1 editor that an anchor link is created.
> translator: restore math label anchor (v1)

- sphinxcontrib/confluencebuilder/publisher.py
Calls to `get_page_property` should return `None` for non-entries on a page. This was the original intent with the implementation, but final tweaks for initial APIv2 support made the default result a partially populated property instance. This commit cleans up this to restore the original intent to have undefined properties return `None`, as well as updates various locations to use a default property value for each applicable section. Specifically:
- `CB_PROP_KEY` returns a prepared empty value dictionary, since the requests will push up a new property change
- Property fetching for v2 will return a `None` populated value to explicitly indicate that the requests should support this type of metadata, as well as that Confluence has reported no value exists
- Update events will populate with …
> Handle non-defined property updates

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
Cleaning up the placement of various configuration entries. This includes placing some options in "better" categories and corrects the name-order of entries missed over the years.
> Sort configuration entries

- README.md
- doc/_templates/index.html
- doc/conf.py
- doc/configuration.rst
- doc/contents.rst
- doc/install.rst
- doc/introduction.rst
- doc/roles.rst
- doc/tips.rst
- doc/tutorial.rst
- doc: drop mention of setuptools error
- doc: cleanup rst_epilog to use f-string
- doc: add requests version management
- doc: add introduction page for pdfs
- doc: drop references to confluence server
- README.md: drop reference to confluence server
> Documentation updates

- .github/workflows/docs.yml
With a new container prepared to help speed up testing, use it for the document testing workflow.
> .github: switch to doctest container (docs)

- .github/workflows/confluence-publish-check.yml
- tests/test_validation.py
With a new container prepared to help speed up testing, use it for the Confluence publish testing workflow.
> .github: switch to doctest container (conf. publish test)

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/config/checks.py
- sphinxcontrib/confluencebuilder/config/defaults.py
- sphinxcontrib/confluencebuilder/config/notifications.py
- tests/unit-tests/test_config_checks.py
- tests/unit-tests/test_sphinx_codeblock_highlight.py
Instead of using a transform for users to define overrides for certain language types, promote a dictionary instead. This will help ensure the configuration is picklable for a cache state (and also avoid a warning in Sphinx v7.3.x).
(related to https://github.com/sphinx-doc/sphinx/pull/12203)
> Rework literal block language overrides

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/config/notifications.py
- tests/unit-tests/test_config_checks.py
The advanced overrides for tailoring file/link transformations existed since the start of this extension's life, but the options are not entirely useful* for end users. It is unknown if anyone has ever needed to override these options. In addition, setting them make a project's configuration unpicklable.
For now, will mark this options as deprecated. This will give time for users to report if these options are desired before the configuration options are removed from this extension.
> flag file/link transforms as deprecated

- .github/workflows/sphinx-dev-check.yml
Bumping the version of the default Python used for a Sphinx development check to Python v3.12 (to use the newest version by default).
> .github: bump python version for sphinx-dev check

- .github/workflows/build.yml
- tox.ini
Sphinx provides a stable v7.3.x series; adjusting the tox configuration to support the new revision. Following maintenance guidelines, this allows a series of legacy Sphinx revisions to be dropped as well.
In addition, adjusting the automated building to invoke these accordingly.
> Test against Sphinx 7.3.x

- sphinxcontrib/confluencebuilder/publisher.py
Correcting v2 API implementation recently introduced that incorrectly prepared metadata objects when Confluence does not report any metadata information for a page (which in turn results in `AttributeError` exceptions).
> publisher: correct v2 page updates with unset metadata

- sphinxcontrib/confluencebuilder/translator.py
When an unknown node is detected by this extension, attempt to print the document as well as the line number where the issue has occurred. This should provide users a better understanding where the origin of an unknown node occurs.
> translator: print additional unknown-node feedback

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/config/checks.py
- sphinxcontrib/confluencebuilder/config/exceptions.py
- sphinxcontrib/confluencebuilder/publisher.py
- tests/unit-tests/test_config_checks.py
It has been reported in a user environment that they operate a Confluence instance where the `GET /content/` API call is blocked. The following provides an alternative way to fetch specific page information using the `GET /content/search/` call instead.
> introduce an alternative page search option

- doc/advanced-extensions.rst
- doc/advanced-publish-permissions.rst
- doc/advanced-wiping-space.rst
- doc/advanced.rst
Adding a page specific to hint where to find information about extending their documentation, and any hints specific to this extension. At this time, this content is limited, but can be expanded on in the future.
> Add advanced extensions document

- sphinxcontrib/confluencebuilder/publisher.py
- sphinxcontrib/confluencebuilder/rest.py
- sphinxcontrib/confluencebuilder/retry.py
There are undesired scenarios where when publishing documentation to a Confluence instance that a publish event may trigger an interim failed API call. This can be a situation where Confluence is dealing with a transaction rollback (which may take a brief moment) or maybe there was a random failure on a reverse proxy to a Confluence instance. When an error like this (e.g. 5xx errors) occurs, publication immediately stops and a user/job will need to retry again to complete any publication attempt. This can be a bit of a pain for large documentation sets where Confluence may have a 1 in 100/1000 chance of triggering an error.
To help deal with this scenario, this extension will automatically retry API calls in the event that it detects an error which appears to be an interim issue. When …
> support api retry events

- tests/unit-tests/test_config_header_footer.py
- tests/unit-tests/test_rst_attribution.py
- tests/unit-tests/test_rst_citations.py
- tests/unit-tests/test_rst_epigraph.py
- tests/unit-tests/test_rst_figure.py
- tests/unit-tests/test_rst_footnotes.py
- tests/unit-tests/test_rst_highlights.py
- tests/unit-tests/test_rst_pull_quote.py
- tests/unit-tests/test_rst_targets.py
- tests/unit-tests/test_sdoc_genindex.py
- tests/unit-tests/test_sdoc_modindex.py
- tests/unit-tests/test_sdoc_search.py
- tests/unit-tests/test_sphinx_toctree.py
Beautiful Soup had deprecated various next/previous calls for some time. For example, switching from `nextSibling` to `next_sibling`. This commit drops the use of various deprecated calls for new ones.
In addition, there are cases where calls like `find_previous_sibling` appear to have changed between recent versions. These calls will find the next tag or navigable string, although some older use cases look to not detect a navigable string compared to new versions. Updating these calls to be a bit more explicit in tag searching, as well as relying on alternative means to inspect content.
> tests: updating various bs4 calls

- tests/test_validation.py
Updating the validation test environment to allow Sphinx and the extension to be configure into a debugging state. This can be used to help test/inspect the process during validation runs.
> tests: support verbose validation runs

- sphinxcontrib/confluencebuilder/rest.py
When the extension is configured for logging REST headers, it may not be trivial to find where certain GET/POST/etc. calls originate from. To make things easier, inspect the frame stack to determine who originated these REST calls. For the detected frame, add its name into the request debug log.
> rest: log method name in header logs

- doc/advanced-extensions.rst
- doc/conf.py
- doc/configuration.rst
- sphinxcontrib/confluencebuilder/storage/translator.py
Renaming various helpers to no longer have an internal hint. For example, `_start_tag` to `start_tag`. These helpers have been in a good state for some time, and exposing them is desired for some users wanting to use these for their own modifications.
> Expose translator helpers

- sphinxcontrib/confluencebuilder/storage/translator.py
When building title anchors, the title node will look at assigned name references to build anchors. Before building an anchor, the target will be resolved for the case of special targets (e.g. references to headers which use a Confluence-generated anchor target). In some scenarios, a resolved reference may repeat the same target anchor to create. This commit tweaks the process to avoid creating additional anchors of the same name, if an anchor was already created for the title node.
> translator: avoid creating duplicate anchors

- doc/configuration.rst
- doc/guide-ci.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/cmd/conntest.py
- sphinxcontrib/confluencebuilder/cmd/report.py
- sphinxcontrib/confluencebuilder/config/checks.py
- sphinxcontrib/confluencebuilder/config/exceptions.py
- sphinxcontrib/confluencebuilder/config/notifications.py
- sphinxcontrib/confluencebuilder/publisher.py
- sphinxcontrib/confluencebuilder/rest.py
- tests/test_validation.py
- tests/unit-tests/test_config_checks.py
The following introduces the option `confluence_api_token` to this extension. The goal is somewhat of a replacement of the option `confluence_server_pass`. For Confluence Cloud, API tokens are required for authentication. For Confluence Data Center, PATs are preferred although there may be some level of support for passwords.
The option `confluence_server_pass` was one of the original options introduced by this extension. Over the years there has been a transition towards tokens, so a rename may be best. Specifically, there seem to be cases where people place API tokens in the personal access token (PAT) option but should have been under the "pass" option. Having the option explicitly say "API token" should provide some clarify.
Note that `confluence_api_token` should be functionally the …
> Introduce confluence api token option

- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/publisher.py
- sphinxcontrib/confluencebuilder/util.py
- tests/unit-tests/test_util_detect_cloud.py
Refactor the logic related to attempts to detect a Confluence Cloud instance from the configured site URL. Changes improve handling situations if a port was explicitly configured on the instance and also allows Cloud-detection logic to apply to other builds (e.g. the connection test utility).
> Refactor Cloud detection logic

- sphinxcontrib/confluencebuilder/debug.py
- sphinxcontrib/confluencebuilder/rest.py
When a user has configured logging for `headers`, this will print a series of raw headers to the configured standard output stream. This is primarily to help aid in debugging and development scenarios. To help avoid situations where users may want to share the authorization header, force redact the header's value when printing.
This commit also introduces the option `headers_raw` to allow advanced users to dump the raw header value with no redaction, if ever needed.
> redact authorization header in debug bumps

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/debug.py
- sphinxcontrib/confluencebuilder/rest.py
Extend the logging capabilities for publish events to support logging the contents of body data for requests and responses. This adds the `headers_and_data` option to hint to have both headers and their content (if printable content).
> Add support for logging request/response body data

- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/publisher.py
While Cloud detection is handled through an Atlassian-detected site value, adding a hidden option to allow forcing the Cloud mode for a run. This is to be proactive, just in case the check does not operate as expected and users need a workaround for a corner case.
> provide advanced option for cloud mode override

- sphinxcontrib/confluencebuilder/rest.py
When configured to dump request body data, the log attempt may fail when trying to process non-JSON data (e.g. attachments). Adjust the debugging call to verify that the request is JSON data before attempting to print.
> rest: only attempt to json-dump json data

- doc/advanced-publish-permissions.rst
- doc/conf.py
- doc/configuration.rst
- doc/directives.rst
- doc/guide-ci.rst
- doc/guide-class-hints.rst
- doc/guide-math.rst
- doc/roles.rst
- doc/tips.rst
- doc/tutorial.rst
With reStructuredText/Sphinx, there does not appear to be a way to take advantage of the `:ref:` role and apply a literal style processing on select elements. This extension's documentation would handle this by first adding a literal description of an element, followed by a reference named "ref" -- not ideal.
This change adds a custom domain/role to support a `lref` role, the "literal-styled reference" role. For generated references using this role, they will be manipulated/forwarded to Sphinx's standard domain to handle as a normal cross reference. When resolved, the custom domain will then wrap the inner node with a literal node. This allows both having a page-to-page reference that is also styled as a literal.
Updating various links to use this capability. In addition, cleanup other …
> Improve styled configuration references for extension's documentation

- sphinxcontrib/confluencebuilder/rest.py
Adding the cookie header to the list of redacted entries from the standard header-data logging mode.
> rest: redact cookie data for header-data logs

- sphinxcontrib/confluencebuilder/publisher.py
In almost every medium/large documentation sets publishing on Confluence Cloud reports a properties publish error every tens/hundreds of published documents. While retries exist to help publishers, it would be nice to avoid having these situations. To help prevent this error state from occurring, always add a 1/2 second delay on new Confluence Cloud page updates. This appears to help reduce the error state (based on limited testing).
> publisher: force delay on new-page properties update on cloud

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/config/checks.py
- sphinxcontrib/confluencebuilder/config/defaults.py
- sphinxcontrib/confluencebuilder/config/exceptions.py
- sphinxcontrib/confluencebuilder/config/validation.py
Updating the configuration handling of publish debugging options to promote the uses of dashes of underscores (e.g. `headers-and-data` over `headers_and_data`). Both values are still accepted, but the dash variant will be the value shown in documentation.
This commit also adjusts the configuration check to explicitly list supported options. The previous use of populating values from the enumeration does not work for all desired entries. Best to list the explicit values we want to inform a user on.
> cleanup publish debug options (format/presentation)

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/config/defaults.py
As this extension has evolved over the years, the option `confluence_disable_notifications` was introduced to help suppress multiple notifications generated from publishing events. At the time of introduction, the feature was not enabled by default since it did result in changing page requests made and there was not an immediate desire to change the default state of things.
Consider the common application of this extension, most users may not expect notifications to be generated for automated publish events. To make things easier for installations, we are changing the default mode of this extension to suppress page notifications. Users who prefer to have notification events generated are now recommended to explicitly configure the option.
> config: configure notifications to default off

- doc/conf.py
- doc/contents.rst
- doc/events.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/builder.py
- tests/test_validation.py
Adds an event (`confluence-publish-point`) that is triggered when this extension prints the detected Confluence publish point URL in the standard output stream. This can allow documentations to react to the resulting URL to perform any custom post-actions when the publish point is known.
> Adding confluence publish point event

- doc/features.rst
- sphinxcontrib/confluencebuilder/storage/translator.py
Adding some limited support for various sphinx-design capabilities. This commit helps:
- Prevent warnings when processing the `PassthroughTextElement` node.
- Provides partial support for drop-down boxes (using expand macros).
- Basic support for cards, placed into panels. No column support but does handle some header, title and footer logic.
- Partial support for badges.
> Introduce partial sphinx-design support

- sphinxcontrib/confluencebuilder/storage/translator.py
When adding support for sphinx-design card titles, the strong start tag is created but the end tag is not properly added into the context; correcting.
> translator: correct sd card title handling

- doc/_themes/sphinx13b/static/sphinx13b.css
- doc/features.rst
When presenting features, avoid breaking the link to certain features or extensions. This should help avoid select elements from splitting the name of a capability/extension that is best served on a single line.
> doc: avoid link breaks in table links

- sphinxcontrib/confluencebuilder/singlebuilder.py
Add a newline after starting a progress message when in verbose mode. This helps avoid stacking a verbose message after the initial progress message is generated.
> singlebuilder: print newline after progress events in verbose mode

- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/storage/translator.py
When using the `singleconfluence` builder, do not take into consideration document-specific hints to the editor and full-width values. The page-specific hints can mix up content and could adjust the publish editor type depending on what pages are used.
> ignore document overrides in a singleconfluence mode

- requirements_dev.txt
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/singlebuilder.py
- sphinxcontrib/confluencebuilder/state.py
- sphinxcontrib/confluencebuilder/storage/translator.py
- tests/unit-tests/datasets/references/index.rst
- tests/unit-tests/datasets/references/md-v1-first.md
- tests/unit-tests/datasets/references/md-v1-second.md
- tests/unit-tests/datasets/references/md-v2-first.md
- tests/unit-tests/datasets/references/md-v2-second.md
- tests/unit-tests/datasets/references/rst-v1-first.rst
- tests/unit-tests/datasets/references/rst-v1-second.rst
- tests/unit-tests/datasets/references/rst-v2-first.rst
- tests/unit-tests/datasets/references/rst-v2-second.rst
- tests/unit-tests/test_references_confluence.py
This performs another rework of tracking targets for references in this extension. It is another attempt to improve the state of building proper links no matter what builder type is selected. This update was primarily driven some limitations observed when using the `singleconfluence` builder. In some scenarios, links to headers would not point to proper anchor points in both editor versions. In addition, special anchor processing in v2 only worked for a subset of links.
We moved all target registration into the main builder and added conditions for when using different builder types. This has helped remove some duplication related to building anchors. Corrections towards tracking duplicate headers addressed some broken links observed in a singleconfluence mode. In addition, this also …
> Improve reference tracking

- sphinxcontrib/confluencebuilder/rest.py
Include the version of this extension in the `User-Agent` field in REST calls. This is to allow Confluence instances and reverse proxies to manage requests from this extension based on the version, if ever needed.
> rest: include extension version in user agent

- .github/workflows/build.yml
- mypy.ini
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/assets.py
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/state.py
- sphinxcontrib/confluencebuilder/storage/translator.py
- sphinxcontrib/confluencebuilder/transmute/__init__.py
- sphinxcontrib/confluencebuilder/transmute/ext_sphinx_diagrams.py
- sphinxcontrib/confluencebuilder/transmute/ext_sphinx_gallery.py
- sphinxcontrib/confluencebuilder/transmute/ext_sphinx_toolbox.py
- sphinxcontrib/confluencebuilder/transmute/ext_sphinxcontrib_mermaid.py
- sphinxcontrib/confluencebuilder/util.py
- sphinxcontrib/confluencebuilder/writer.py
- tox.ini
- adjust various module-check flags
- drop supported image types class
- add type hints
- tox: default run mypy
- workflows: add an mypy environment run
> Improve static typing

- sphinxcontrib/confluencebuilder/storage/translator.py
Sphinx environment's `doc2path` call now returns a Path \[1\]; updating the source-link logic to handle a string conversion before extracting the suffix.
\[1\]: https://github.com/sphinx-doc/sphinx/commit/de15d61a46daaaa2b0a0e341cdb4e0abe107e012
> translator: handle new pathlib usage in sphinx-env

- .github/workflows/build.yml
- README.md
- check
- doc/conf.py
- sphinxcontrib/confluencebuilder/__init__.py
- tox.ini
Updates the tox environment, GitHub actions and other tweaks to include Sphinx v8 series into this repository.
> Update development scripts/testing to include Sphinx v8.x

- sphinxcontrib/confluencebuilder/std/confluence.py
Updating the code maps to include newer code formats supported by Confluence Cloud, as well as updating supported values based on Pygments-listed languages.
> std: update supported code styles

- doc/configuration.rst
- doc/directives.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/config/checks.py
- sphinxcontrib/confluencebuilder/directives.py
- sphinxcontrib/confluencebuilder/nodes.py
- sphinxcontrib/confluencebuilder/storage/translator.py
- tests/unit-tests/datasets/html/index.rst
- tests/unit-tests/test_config_checks.py
- tests/unit-tests/test_confluence_html.py
Adds support for a `confluence_html_macro` directive for Confluence instances that have the `html` macro enabled.
> Add the html confluence directive

- tests/test_sandbox.py
Provides support for configuring the page's editor when running a sandbox environment.
> tests: add editor support for sandbox

- sphinxcontrib/confluencebuilder/storage/translator.py
- tests/validation-sets/restructuredtext/images.rst
When no explicit alignment is configured for an image, apply an inline flag for an image. Confluence Cloud recently added support for inline images (CONFCLOUD-68501) and configuring these images as inlined by default should provide a consistent viewing experience between v1/v2 editors and similar rendering styles in other builders.
> translator: support inlined images in v2 editor

- sphinxcontrib/confluencebuilder/transmute/ext_sphinx_toolbox.py
An update \[1\] has been made to sphinx-toolbox's CollapseNode. Adjusting the transmute logic to support the variant label approaches.
\[1\]: https://github.com/sphinx-toolbox/sphinx-toolbox/commit/ae0ae836268a8e77e36ce58e534131e9ac42a75d
> transmute: support sphinx-toolbox collapse node label change

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/config/env.py
- tests/unit-tests/test_config_env.py
Introducing a new option `confluence_disable_env_conf` which allows a user to ignore environment options for unset configuration options.
> Provide means to disable env options

- sphinxcontrib/confluencebuilder/config/notifications.py
When reporting conflicting authentication options, note which specific configuration options are the cause.
> config: detail conflicting auth options

- doc/configuration.rst
- doc/features.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/transmute/ext_sphinxcontrib_mermaid.py
Provide support to allow a user to configure this extension to wrap raw Mermaid diagrams into an HTML macro block, instead of forcing to use either `png` or `svg` formats.
This is only support for Confluence instances that support an HTML macro.
> Allow users to feed mermaid diagrams into html-macros

- sphinxcontrib/confluencebuilder/writer.py
Updating the writer's `settings_defaults` attribute to match the most recent docutils typing.
> writer: update settings-defaults typing

- sphinxcontrib/confluencebuilder/logger.py
- sphinxcontrib/confluencebuilder/publisher.py
- sphinxcontrib/confluencebuilder/rest.py
- tests/lib/__init__.py
- tests/unit-tests/test_config_checks.py
- tests/unit-tests/test_sphinx_codeblock_highlight.py
- tests/unit-tests/test_titles.py
- tests/unit-tests/test_unknown_node.py
A series of retry events when publishing can report certain events as warnings. The prospect Sphinx v8.1.x release reworks how warnings can trigger a fail state and `skip_warningiserror` becomes deprecated with these changes. This can cause issues for users who wish to run with warnings-as-failure but may experience publishing issues that can be recovered on during a run. To prevent issues, updating a series of warning messages to be informational messages.
Sphinx has also updated it's implementation to no longer generate exceptions on an immediate warning by default \[1\]. This is desired for this extension's tests so the Sphinx application will enable this capability. The `skip_warningiserror` call is obsolete. With exception-on-warning enabled, a series of tests need to be updated to …
> Support upcoming Sphinx warning-error changes

- doc/features.rst
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/singlebuilder.py
- tests/sample-sets/linkcode/conf.py
- tests/sample-sets/linkcode/index.rst
- tests/sample-sets/linkcode/tox.ini
- tests/test_validation.py
- tests/validation-sets/extensions/index.rst
- tests/validation-sets/extensions/linkcode.rst
Updating the `confluence` and `singleconfluence` builders to use their explicit names to be used for linkcode support. The original support used a value of `True` which appeared to work; however, now appears to generate a warning. Using explicit names prevents this.
Additional documentation and validation changes as well.
> `sphinx.ext.linkcode` Improvements

- pyproject.toml
- tox.ini
Updating the default tox configuration to test with Python v3.13.
Not yet included in CI as the latest images do not yet include support yet.
> Initial Python 3.13 support

- .github/workflows/docs.yml
Store the artifacts for the raw tx/log files from a PDF run. This can be useful for inspection if there are issues with the request to generate a PDF.
> workflows: capture output of pdf runs

- sphinxcontrib/confluencebuilder/singlebuilder.py
Sphinx's builder implementation has added a final hint on the `write` call and introduced a `write_documents` as a more appropriate hook for processing documents \[1\]. This commit updates `SingleConfluenceBuilder` to no longer use `write`, except for supporting legacy versions of Sphinx that this extension still supports.
\[1\]: https://github.com/sphinx-doc/sphinx/pull/12767
> singlebuilder: switch to using write_documents call

- sphinxcontrib/confluencebuilder/builder.py
When processing doctree targets to track titles across multiple documents, the check for the database would fail to function if the database did not any initial entries. This would properly prevent tracking conflicting title documents when running with a `singleconfluence` builder. Adjusting the check to ignore/suppress if the provided database entry is `None`.
> builder: correct title track database check

- sphinxcontrib/confluencebuilder/compat.py
- sphinxcontrib/confluencebuilder/singlebuilder.py
- tests/sample-sets/single-confluence-refs/conf.py
- tests/sample-sets/single-confluence-refs/index.rst
- tests/sample-sets/single-confluence-refs/page-a.rst
- tests/sample-sets/single-confluence-refs/page-b.rst
- tests/sample-sets/single-confluence-refs/page-c.rst
- tests/sample-sets/single-confluence-refs/tox.ini
- tests/test_validation.py
- tests/unit-tests/datasets/rst/contents-multipage/index.rst
- tests/unit-tests/datasets/rst/contents-multipage/page-a.rst
- tests/unit-tests/datasets/rst/contents-multipage/page-b.rst
- tests/unit-tests/test_singlepage_unique_refs.py
When merging multiple doctrees into a single one, elements may have conflicting reference identifiers. This can lead to conflicting raw anchors as well as other logic in translators to create unexpected links when running the `singleconfluence` builder.
This commit updates the merging process to replace the identifiers of each doctree element when a conflict is detected. Elements will be given a new identifier value, as well as elements referencing other elements will have their reference identifiers updated as well.
> singlebuilder: unique identifiers for merged doctree

- tests/test_validation.py
For validation runs, support for checking linkcode support added the extension in the primary configuration for all validation tests. This is not required and only needs to be in the extension-specific test; updating its location.
> tests: moving the linkcode extension registration in validation

- .github/workflows/test-docker-publish.yml
- support/docker/Dockerfile
Sphinx's documentation promotes the use of additional LaTeX packages not included in this extension's doc-helper image. Adding the missing packages for the best experience.
> support: adding more latex packages to documentation container

- doc/advanced-extensions.rst
- doc/conf.py
- doc/configuration.rst
- doc/events.rst
- doc/features.rst
- doc/guide-ci.rst
- doc/guide-confluence-macros.rst
- doc/install-virtualenv.rst
- doc/install.rst
- doc/roles.rst
- doc/tips.rst
- rework page breaks for pdf
- add explicit verbatim spacing for pdf
- minimize spacing between admonitions
- generic grammar, formatting, etc.
- replace various literal/replace tricks with lref roles
> Cleanup documentation

- doc/configuration.rst
- doc/guide-highlight-default.rst
- doc/guide-sso.rst
- doc/guides.rst
- doc/tips.rst
- doc: adding guide on sso/oauth usage
- doc: adding guide on default highlighting
> Add more guides into the documentation

- .github/workflows/build.yml
- .github/workflows/lint.yml
- doc/conf.py
The ruff lint environment was put in a non-passed state since it was run on a previous change set. This is since a change in `doc/conf.py` resulted in a failure and a change on this file only triggered the documentation workflow to run. An update to the workflow trigger events is needed to ensure `doc/conf.py` trigger a lint check. Although, we do not want to force an entire build if the documentation's configuration has just changed. Moving linting into its own workflow handle these scenarios.
> .github: move linting jobs into their own workflow

- doc/_themes/sphinx13b/static/sphinx13b.css
When presenting various directives, roles and more; it can a bit hard to make a distinction between each content-section when reading documentation. This help improve the experience, adding a slight border hint at the top of each content-section.
> doc: add border style to content entries

- sphinxcontrib/confluencebuilder/storage/translator.py
When attempting to determine the anchor target for a named title entry, replace any spaces found in a named entry to ensure it can map to an appropriate anchor value (since anchors have no spaces). This should ensure the sanity check for a target lookup help finds the title has a valid target to ensure the anchor is created.
> translator: replace spaces with dashes when resolving title anchors

- sphinxcontrib/confluencebuilder/assets.py
When forcing assets in standalone (e.g. images that are dynamically generated after the pre-processing stage), it will assume a found asset entry is an indication that the asset was generated by another dynamic image on the same document. However, this not guaranteed to be the case. For example, "page a" may generate a standalone image and register it into the asset manager. A few moments later, "page b" may generate its own standalone image instance that results in the same physical file, but the asset message indicates its origin is "page a". With the original implementation, this would generate an assert.
Since the assert is wrong in this case, instead of asserting the document name maps in the asset name, if it does not map, do not consider the cached asset as the asset to use. …
> assets: ensure forced-standalone handles new-and-matches images

- sphinxcontrib/confluencebuilder/assets.py
- sphinxcontrib/confluencebuilder/svg.py
Paths pushed into `guess_mimetype` were casted to strings to support Sphinx-6.1 and older versions. Since we no longer support these versions, dropping these casts.
> drop str-casts for mimetype requests

- tests/unit-tests/test_util.py
- tox.ini
Update the fixed ruff version to its most recent.
In addition, correct new linter warnings.
> lint: update ruff to v0.8.1

- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/storage/translator.py
Recent changes to Confluence's v2 editor restricted inlined images to a line-height. This is undesired for a default configuration. To avoid this, v2 images will no longer be configured with an inline hint.
> disable use of inline images in v2 editor

- sphinxcontrib/confluencebuilder/util.py
- tox.ini
- lint: update ruff to v0.9.2
- lint: update pylint to v3.3.3
- lint: fix mypy to v1.14.1
- util: update suffix logic to modern calls
> Lint updates

- doc/configuration.rst
- doc/guide-math.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/nodes.py
- sphinxcontrib/confluencebuilder/storage/translator.py
- sphinxcontrib/confluencebuilder/transmute/__init__.py
Introduce support for this extension to generate math content into a format that a MathJax JavaScript engine can process. This change only helps produce/publish content that includes raw content that MathJax can process.
> Introduce raw mathjax support

- .github/workflows/build.yml
While Python 3.13.x has been enabled in the tox configuration, the build workflow was never updated to test this interpreter version; updating.
> workflows: test against python 3.13

- sphinxcontrib/confluencebuilder/builder.py
Updating the internal overwrite of the imgmath temporary directory to use the pathlib module. Upstream version of Sphinx has updated its implementation to use pathlib, and using a str causes issues when running the imgmath extension.
Using `Path` should be fine for existing/older versions of Sphinx, as its value used with `os.path.join` handles `Path` objects.
> builder: use pathlib for internal imgmath override

- tests/unit-tests/test_legacy_pages.py
When attempting to sanity check the handling of legacy pages (for cleanup), the mocked publisher does not aim to support asset-related content. Since intersphinx database can be published by default, the logic an attempt to retrieve page information for the intersphinx database to publish. To avoid this, explicitly disable intersphinx processing for this test.
> tests: avoid intersphinx processing in legacy pages test

- sphinxcontrib/confluencebuilder/env.py
When a cache is kept for tracking previously published pages and their identifiers, if a processing event results in pages not needing to be updated, unchanged pages can cause their page identifiers to be removed from the active list. This can result in a following pass to cleanup legacy-flagged pages for pages that are still considered unchanged.
The cache implementation should be maintaining the assumed cached identifier for pages if they remain changed for a run. Updating the implementation to always populate the cached page identifiers before replacing them with new active page identifiers (if any).
> env: maintain tracked page identifier cache between builds

- sphinxcontrib/confluencebuilder/util.py
When operating in a MinGW terminal without invoking `winpty`, getpass does not function as expected. This extension included a workaround by using `stty`; however, it has been observed in recent environments that stty may fail to run. This would result in an exception and break a user's attempt to perform a publish request.
First, this commit improves the handling when stty fails to invoke as expected (instead of throwing exceptions a user may not understand). Second, if stty, instead of falling back to trying `getpass` (which seems to always never work in this environment), just stop and report the issue. Users can should always be able to run with `winpty` to prevent issues when using the ask-password capability.
> util: handle stty failures under mingw for getpass workaround

- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/publisher.py
When attempting to update page properties, an internal delay was added for new pages to help reduce the chance for errors such as conflicts observed. This commit extends the small wait for page updates as well, to help ensure page update scenarios can avoid conflicts/issues when immediately trying to update properties after a page update.
Related to this, we also introduce an internal configuration option `confluence_adv_disable_cloud_prop_delay`, allowing advanced users the means to opt-out of any delay.
> internal delay all cloud property update events

- sphinxcontrib/confluencebuilder/publisher.py
- tests/unit-tests/test_publisher_page.py
This extension will update page properties under a get-then-update process, where a retry attempt will be made to help deal with conflict scenarios. This only applied to Confluence-specific properties and not this extension's custom property (e.g. used for page hash tracking).
This commit is updated the implementation to perform the get-then-update with retries for all property submissions, in attempt to prevent odd publish scenarios for users.
> support property retry events for extension-specific properties

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/config/checks.py
- sphinxcontrib/confluencebuilder/rest.py
- tests/unit-tests/test_config_checks.py
There are select scenarios where this extension may retry a failed API event when publishing. The original implementation included a fixed retry attempt (max three attempts) and a retry duration of four seconds.
To make things more flexible for users, these options are now configurable from the project configuration.
> support user overrides of api retry failure attempts/duration

- sphinxcontrib/confluencebuilder/transmute/__init__.py
Old `render_dot` returned a `str` but Sphinx v8.2 comes with a wrapper to prepare for the type changing to a `Path` type. Sphinx's usage of `render_dot` will generate a file type and use it in the translator, but this extension replaces the node here with a compatible `nodes.image` type ahead of time (e.g. for asset processing). The `nodes.image` type expects a `str` type, so convert ensure any new Path-like type is converted back to a `str` to prevent issues.
> transmute: enforce `render_dot` file to `str` type

- sphinxcontrib/confluencebuilder/rest.py
The curl documentation gives a good capture of transient errors and what it's `--retry` call supports a retry on. Instead of having this extension retry on all 500 errors, narrow down the scope to specific errors more so valid for a retry. We also extend the retry events on select timeout-related events.
> rest: adjust publish retry events based on transient errors

- sphinxcontrib/confluencebuilder/transmute/__init__.py
In Sphinx v8.2, math directives now promote the use of `no-wrap` over `nowrap`. Adjust the implementation to support both for now.
> transmute: support new no-wrap flag for math directives

- sphinxcontrib/confluencebuilder/storage/translator.py
In Sphinx v8.2, production entries appear to provide a newline entry for us. While this means we do not have to append on ourselves, we still want to support some older versions of Sphinx. For now, strip any trailing newline and still append our own.
> translator: support new production node newline

- sphinxcontrib/confluencebuilder/storage/translator.py
The following attempts to provide support for Sphinx v8.2's new `collapsible` option for admonitions. This implementation wraps the contents of an admonition block into an expand macro to handle this hint.
However, this is not pretty on Confluence (v1 and v2 editors). Not much we can do for styling approaches as we cannot manipulate macro-generated content.
> translator: support for collapsible admonitions

- sphinxcontrib/confluencebuilder/storage/translator.py
Updating the v2 editor support to include some level of collapsing code block macros, by taking advantage of the expand macro.
> translator: support collapsed code blocks in v2

- sphinxcontrib/confluencebuilder/rest.py
When configured to log request data to the standard output stream, the check used to consider printing JSON data checked if the content type was marked as `application/json;charset=utf-8`. However, it has been observed in recent testing that content type used for JSON-related requests was set to `application/json`.
Adjusting to check to just look for `application/json` in the content type before attempting to parse/output JSON content in a debug mode.
> rest: relax content-type check for dumping request data

- sphinxcontrib/confluencebuilder/publisher.py
When refactoring the retry REST call implementation \[1\], this change undesirably suppressed API errors on page update events. We should always be raising the `ConfluenceBadApiError` exception if we do not have a specific override exception to replace it with.
\[1\]: 6a1f9badd4716234271b75ac79dfe097ee6c3287
> publisher: restore raising of an api error

- sphinxcontrib/confluencebuilder/debug.py
- sphinxcontrib/confluencebuilder/rest.py
Updated the set of headers to automatically filter during debug logging. We now ensure filtering runs on both outgoing and incoming events.
> rest: update/correct filtering of headers for debug logging

- sphinxcontrib/confluencebuilder/publisher.py
In theory, there should only be a mapping of one property per key on a page. It has been reported in some scenarios that duplicate keys may exist on a Confluence database, which appears to be an undesired state. To help with debugging, if multiple results are detected, report this as a warning.
When attempting to update a property, the implementation can try at least two times when dealing with a conflict scenario (typically, for new page update events). While the retries are performed, the logic should have been always raising an error if the final retry failed; correcting.
Users have reported scenarios where a property update may fail due to a duplicate property entry registered in Confluence's db. In this scenario, Confluence can report a 400 error. To try to help push the database …
> Improve property duplication detection and handling

- doc/install-virtualenv.rst
- doc/install.rst
CentOS is a discounted distribution. Dropping its help from the installation documentation.
> doc: drop centos install nodes

- sphinxcontrib/confluencebuilder/__init__.py
Sphinx may process nodes through a content filter at various stages, either from its internal implementation or external extensions. These nodes may include directives/roles that may references nodes that have not been registered into Sphinx.
To prevent issues of missing node types for nodes managed by this extension, ensure all nodes are registered on setup.
> explicitly register all extension nodes

- sphinxcontrib/confluencebuilder/transmute/__init__.py
The development version of Sphinx has tweaked its `render_math` call to now accept a configuration option. To support this, we will adjust the use of this call to forward the configuration in. If a TypeError is generated, we will assume this is an older version of Sphinx and try the original signature call.
See also: https://github.com/sphinx-doc/sphinx/pull/13626
> transmute: handle prospect render_math signature changes

- sphinxcontrib/confluencebuilder/singlebuilder.py
Sphinx had added a requirement \[1\] for a tag parameter on its `get_and_resolve_doctree` call. If the method appears to support a tags parameter, forward the tags from the builder in.
\[1\]: https://github.com/sphinx-doc/sphinx/pull/13631
> singlebuilder: provide tags into get_and_resolve_doctree call

- doc/configuration.rst
- doc/features.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/config/checks.py
- sphinxcontrib/confluencebuilder/config/exceptions.py
- sphinxcontrib/confluencebuilder/storage/translator.py
- sphinxcontrib/confluencebuilder/translator.py
- tests/sample-sets/sphinx-inline-tabs/README.md
- tests/sample-sets/sphinx-inline-tabs/conf.py
- tests/sample-sets/sphinx-inline-tabs/index.rst
- tests/sample-sets/sphinx-inline-tabs/tox.ini
- tests/sample-sets/sphinx-tabs/README.md
- tests/sample-sets/sphinx-tabs/conf.py
- tests/sample-sets/sphinx-tabs/index.rst
- tests/sample-sets/sphinx-tabs/tox.ini
- tests/unit-tests/test_config_checks.py
Attempt to support inlined tabs for both the sphinx-inline-tabs and sphinx-tabs extensions. Either requires the use of a third-party macro.
> Introduce inline tab support

- doc/directives.rst
Adding a reference to the sphinx-confluencebuilder-bridge extension for an alternative way of handling Confluence directives/etc. in other builders.
> doc: add sphinx-confluencebuilder-bridge reference

- sphinxcontrib/confluencebuilder/storage/translator.py
- tests/unit-tests/test_rst_contents.py
- tests/unit-tests/test_rst_headings.py
- tests/unit-tests/test_rst_references.py
- tests/unit-tests/test_singlepage_toctree.py
To help ensure anchor links to section work across all editor types and on all Confluence variants, ensure we always inject section anchors.
Historically, this extension would only create anchors if required. Sections should have their own identifiers pre-made by Confluence. However, the identifiers are not consistent between different variations of Confluence and certain features (e.g. ac:links to anchors) expect certain anchor names. Over time we duplicated some anchors to help make things smooth when the new Confluence editor was made. Unfortunately, recent testing still showed not all links would function as expected. This commit tries to cover all anchor cases by always forcefully creating anchors in sections (and compatibility anchors), no matter what the editor is. When testing on …
> translator: register section anchors for all editors

- sphinxcontrib/confluencebuilder/storage/translator.py
- tests/unit-tests/test_references_confluence.py
- tests/validation-sets/restructuredtext/references.rst
Expands the populated anchor set to include anchors for other reference identifier not processed. To support these anchor points, we populate known anchors to be added at a point of time where they can be added into the page. If we do not, it will generate anchors in locations where Confluence will render newlines. For example, adding an anchor before a paragraph, Confluence styling will ensure the paragraph starts on a new block leaving a less than ideal rendering. Instead, we populate anchors as we process and then jump them into the first block we can.
> translator: delayed anchor injection for other refids

- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/builder.py
- sphinxcontrib/confluencebuilder/transform.py
- sphinxcontrib/confluencebuilder/util.py
- tests/sample-sets/header-links/rst-v1-first.rst
- tests/sample-sets/header-links/rst-v2-first.rst
- tests/unit-tests/test_references_confluence.py
This extension has tried to utilizing Confluence-generated anchor targets for sections over the years. However, there have been a lot of inconsistent target values with Confluence Cloud/v2 when sections have some characters (e.g. parenthesis). Confluence may inject `[inlineExtension]` prefixes in header identifiers or completely ignore anchor values that have these characters. While we attempted to account for these unique situations, issues keep arising as both Confluence and this extension evolves.
To try to avoid any more issues, we will no longer attempt to map directly to pre-made section identifiers when these characters are detected. Since a recent change \[1\] now force-adds all docutils anchor entries for sections, when an issued section target is detected, we will instead use …
> Replace special anchor handling

- doc/advanced-publish-permissions.rst
- doc/configuration.rst
- doc/guide-scope-token.rst
- doc/guides.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/cmd/conntest.py
- sphinxcontrib/confluencebuilder/cmd/report.py
- sphinxcontrib/confluencebuilder/config/defaults.py
- sphinxcontrib/confluencebuilder/publisher.py
- sphinxcontrib/confluencebuilder/rest.py
- sphinxcontrib/confluencebuilder/std/confluence.py
- sphinxcontrib/confluencebuilder/util.py
Providing support for API tokens which have scopes applied to them.
Confluence requires scoped API tokens to utilize a new API endpoint.
The changes introduced in this commit help a user to automatically
handle this endpoint change if a scoped API token is hinted.
Alternatively, users can still set the server URL to the modern
Confluence API endpoint URL. Before this change, this worked in
combination of forcing `confluence_api_mode = "v2"` to ensure v2 API 
calls are made (required since some v1 API calls do not function with
scoped APIs). Explicitly configuring a v2 API mode is no longer required
since this extension uses the scoped API-related configurations to hint
at using v2 API by default.
> Improved support for scoped API tokens

- doc/configuration.rst
- sphinxcontrib/confluencebuilder/__init__.py
- sphinxcontrib/confluencebuilder/config/checks.py
- sphinxcontrib/confluencebuilder/config/defaults.py
- sphinxcontrib/confluencebuilder/config/exceptions.py
- sphinxcontrib/confluencebuilder/std/confluence.py
- sphinxcontrib/confluencebuilder/storage/translator.py
- tests/unit-tests/test_config_checks.py
- tests/unit-tests/test_util_extract_length.py
Default table width for editor v2 with 'widths' set is currently 760 and can not be changed.
If one has a lot of columns than 760 is just way to narrow. 
Confluence seems to be able to handle bigger width values quiet well and users might want to experiment with this value to have nicer tables.
> Add option confluence_table_width
