sphinx-contrib/confluencebuilder

AUTHORS, CHANGES.rst, README.rst, requirements_dev.txt, setup.py, sphinxcontrib/confluencebuilder/__init__.py, sphinxcontrib/confluencebuilder/__main__.py, sphinxcontrib/confluencebuilder/builder.py, sphinxcontrib/confluencebuilder/exceptions.py, sphinxcontrib/confluencebuilder/publisher.py, sphinxcontrib/confluencebuilder/rest.py, sphinxcontrib/confluencebuilder/writer.py, test/test_builder.py, tox.ini
The following holds a series of development changes to help improve the `sphinxcontrib-confluencebuilder` extension. Most notable changes include:
- REST API Support (8a39c9d5448b7cca6392a6a167877c0d74b28229)
- Page-prefix Support (1e525b7ac9dc1927915b9604e31e9c4a900a1735)
- Proxy Support (ced564581ab6640f5a29cc23b8b0e9a4acd606c6)
Along with a series of several minor features and cleanup.
=> development cycle | rest api, cleanup and more

CHANGES.rst, sphinxcontrib/confluencebuilder/builder.py, sphinxcontrib/confluencebuilder/publisher.py, sphinxcontrib/confluencebuilder/rest.py
Includes minor usability improvements recommended for the v0.6 release (#18).
=> usability improvements

sphinxcontrib/confluencebuilder/__init__.py, sphinxcontrib/confluencebuilder/builder.py, sphinxcontrib/confluencebuilder/publisher.py
Provides a series of minor improvements to purging capabilities:
- Searched descendants will use a higher fetch limit (to minimize number of REST calls needed).
- Allow option for advanced users to enable an aggressive descendants search.
- Documentation and other minor code cleanups.
=> purge improvements

AUTHORS, CHANGES.rst, README.rst, doc/conf.py
- AUTHORS: adding new authors 
- CHANGES.rst: adding feature/fix updates
- sync eol confluence versions
=> recommended pre release cleanup

sphinxcontrib/confluencebuilder/translator.py
In order for links to classes and functions to work properly it is recommended to add appropriate anchors for them.
=> Add anchor for class and function

AUTHORS, CHANGES.rst, LICENSE
A series of repository maintenance before a release:
- Authors updates.
- Changes updates.
- License year update.
=> pre-release updates

sphinxcontrib/confluencebuilder/translator.py, test/unit-tests/common/test_translator.py
Fixes #200
Signed-off-by: James Bungard <jmbungard@gmail.com>
=> Fix docname logic to work with Windows paths

CHANGES.rst, sphinxcontrib/confluencebuilder/translator.py, test/unit-tests/literal-markup/dataset/literal_includes.rst, test/unit-tests/literal-markup/expected/literal_includes.conf
Support 'firstline' parameter in the code block macro.
https://confluence.atlassian.com/doc/code-block-macro-139390.html
=>  Number of the first line of code can be >1

CHANGES.rst, README.rst, doc/conf.py, doc/configuration.rst, doc/documentation.rst, doc/index.rst, doc/install.rst, doc/markup.rst, doc/tips.rst, sphinxcontrib/confluencebuilder/__init__.py, sphinxcontrib/confluencebuilder/publisher.py, sphinxcontrib/confluencebuilder/translator.py
Performing a series of maintenance related changes to the sources and documentation to deal with recent pull requests, URL changes and more.
=> august maintenance

test/test_sandbox.py, test/test_validation.py, test/unit-tests/literal-markup/test_literal_markup.py, test/validation-sets/common/images.rst
Performing a series of minor changes to test-related options. This includes:
- force first figure example as left-aligned as sphinx may default center
- update default test user for validation tests
- introduce raw publish support
- adjust code block check versions to re-test in sphinx 2.x
More details provided in each individual commit.
=> test maintenance work

.travis.yml, setup.py, tox.ini
Making a series adjustments to classifiers and tests to help verify this extension's support for Python 3.8.
=> python 3.8 support

.travis.yml, tox.ini
Making a series adjustments to tests to help verify this extension's support for Sphinx 2.2.
=> sphinx 2.2 support

test/sphinxcontrib_confluencebuilder_util.py, test/test_validation.py, test/validation-sets/autodocs/automodule.rst
Corrects a series of issues related to strict Sphinx warning checks added to test utility calls and the validation test environment.
=> permit validation request

AUTHORS, CHANGES.rst, README.rst, doc/conf.py, doc/tutorial.rst, setup.py, sphinxcontrib/confluencebuilder/__init__.py, sphinxcontrib/confluencebuilder/exceptions.py, sphinxcontrib/confluencebuilder/rest.py
Perform a series of trivial maintenance-related changes to this extension's implementation. This includes updating minor comments in documents, dealing with planned deprecation checks, etc.
=> maintenance 2019-11

CHANGES.rst, CONTRIBUTING.rst, README.rst, doc/configuration.rst, doc/tips.rst, test/test_sandbox.py, test/validation-sets/common/images.rst
* prevents warnings from causing a sandbox environment to full-stop
* tweaks/cleanup to the contributing guide
=> maintenance 2019-11-30

README.rst, doc/conf.py, doc/configuration.rst, doc/tutorial.rst, sphinxcontrib/confluencebuilder/__init__.py
Various maintenance changes inside the repository to cleanup documentation, warnings, etc. before the upcoming release.
=> maintenance -- 2019-12-27

AUTHORS, CHANGES.rst, CONTRIBUTING.rst, MAINTAINERS.rst, README.rst, setup.cfg, setup.py, test/test_sandbox.py
A series of repository maintenance work. Notables include:
- AUTHORS: adding new author
- CONTRIBUTING.rst: rework submitting changes notes
- MAINTAINERS.rst: new document
- README.rst: point to stable documentation
- setup.py: default universal wheel
- setup.py: extend clean resources
- test: support custom builder in sandbox
=> maintenance 2020-02-19

.travis.yml, README.rst, doc/conf.py, doc/install.rst, tox.ini
The following is a synchronization of supported revisions of Confluence, Python and Sphinx. This includes adding support for new revisions for these tools and dropping older revisions based on the goals outlined in [CONTRIBUTING.rst](https://github.com/sphinx-contrib/confluencebuilder/blob/master/CONTRIBUTING.rst).
=> end-of-life maintenance

sphinxcontrib/confluencebuilder/translator/storage.py
When captions are detected for various features (figures, literals, etc.), a caption paragraph is injected appropriately before or after the entity being captioned. When a literal results in the creation of a code macro block, the caption value can be better rendered inside the macro's `title` option.
=> storage: support code captions in a code macro

sphinxcontrib/confluencebuilder/publisher.py
Confluence space names and page names are case-insensitive, but the REST API is not. This causes issues when a page name is believed to be a new page and can result in a "title already exists" error when attempting to published.
A workaround is being introduced when this extension believes it has detected a case mismatch. In this event, a CQL search is made for page names with similar names (via the `~` hint). In the event a title match is detected, it will replace the assumed new page creation to a new page update.
See also [CONFSERVER-40303](https://jira.atlassian.com/browse/CONFSERVER-40303).
=> publisher: handle case-insensitive page names

.github/workflows/validate.yml
Introduce a workflow with the intent to provide a manual workflow which can perform a validation run and publish it to this extension's demonstration development space.
=> workflows: introduce validator workflow

.github/workflows/validate.yml
Adding dependencies to include latex (for math) and dot (for graphviz).
=> workflows: add dependencies for validator workflow (part two)

.github/workflows/validate.yml
Adding dependencies to include additional latex packages (e.g. `anyfontsize`).
=> workflows: add additional dependencies for validator workflow

AUTHORS, CHANGES.rst, doc/make.bat, setup.py, sphinxcontrib/confluencebuilder/std/__init__.py, tox.ini
This pull request contains a series of minor changes from maintenance work before a release:
- AUTHORS: adding new authors
- remove namespace declaration on non-namespace
- doc: setlocal for batch helper
- tox: correct sandbox requirements location
- setup.py: adding python 3.9 classifier
=> Maintenance 2020 12 20

doc/_themes/sphinx13b/layout.html, doc/_themes/sphinx13b/static/sphinx13b.css, doc/configuration.rst, doc/install.rst, doc/tips.rst, doc/tutorial.rst
- doc: provide information on new force standalone assets capabilities
- doc: provide information on new custom mime types capabilities 
- doc: correct shell block alignments 
- doc: correct separator in html output 
- doc: improve mobile viewing
- doc: add versionadded for recently added configurations
- doc: adding report information for issues
=> documentation improvements

CHANGES.rst, sphinxcontrib/confluencebuilder/builder.py, sphinxcontrib/confluencebuilder/publisher.py
Some maintenance work to ready the repository before a release.
- cleanup unused configuration caches
=> maintenance 2020-12-30

sphinxcontrib/confluencebuilder/translator/storage.py, tests/test_validation.py
A series of tweaks observed when performing validation testing for #362.
- tests: do not attempt to force homepage on personal space-
- tests: populate manpage url in validation test
- tests: default math images as svg in validation test
- storage: do not generate header links if anchor support is disabled 
- storage: remove bottom border on hlist
=> validation corrections

sphinxcontrib/confluencebuilder/assets.py
In the event that a file/image node cannot be pre-processed, visiting a file/image node in the writer will fail since there is no asset to build a reference to. This primarily can happen with third-party extensions which may convert a node type to an image during the writer phase.
To provide flexibility for these extensions, if an asset is not tracked when attempting to fetch from the asset management, attempt to process the node to track a standalone asset.
=> assets: support late processing file/image nodes

.github/workflows/build.yml, tox.ini
Adjusting the tox configuration to test for the more recent releases of Sphinx.
=> manage supported sphinx versions (sphinx 3.4.x)

.github/workflows/build.yml, tox.ini
Adjusting the tox configuration and automated tests to test for the most recent release of Sphinx.
=> manage supported sphinx versions (sphinx 3.5.x)

.github/workflows/build.yml, tox.ini
Sphinx provides a stable v4.0.x series; adjusting the tox configuration and workflows to support the new revision.
=> synchronize python and sphinx releases

README.rst
Perform a series of minor tweaks to the README.
=> readme tweaks

sphinxcontrib/confluencebuilder/storage/translator.py
Add a series of styling hints for users generating content with the third-party sphinxcontrib-needs extension.
=> provide styling hints for sphinxcontrib-needs

CHANGES.rst, doc/features.rst
Update the `CHANGES.rst` and features documentation based on recent changes added to this repository.
=> maintenance (2021-11-07)

doc/features.rst, sphinxcontrib/confluencebuilder/builder.py, sphinxcontrib/confluencebuilder/compat.py, sphinxcontrib/confluencebuilder/config/notifications.py, sphinxcontrib/confluencebuilder/intersphinx.py, sphinxcontrib/confluencebuilder/publisher.py, sphinxcontrib/confluencebuilder/singlebuilder.py, sphinxcontrib/confluencebuilder/state.py, sphinxcontrib/confluencebuilder/std/confluence.py, sphinxcontrib/confluencebuilder/storage/translator.py, sphinxcontrib/confluencebuilder/translator.py
- refactor logging
- refactor state
- translator: rework code language warning
- std: move max title option into std
- doc: correct link to sphinx ext repository
=> maintenance (2021-11-09)

.github/workflows/build.yml, tox.ini
- tox: adjust for new sphinx versions (v4.3.x)
- workflows: adjust for new sphinx versions (v4.3.x)
=> test against sphinx 4.3.x

sphinxcontrib/confluencebuilder/storage/translator.py
Provide support for processing sphinxcontrib-youtube nodes when using the Confluence builder.
=> add support for sphinxcontrib-youtube

CHANGES.rst, doc/features.rst
- doc: updating information/state about supported extensions
=> maintenance (2021-11-11)

doc/features.rst, doc/install-virtualenv.rst, doc/install.rst, doc/tips.rst
- doc: updating information/state about supported extensions
- doc: do not use source in windows virtualenv activation
- doc: single line bleeding edge pip installation
- doc: add upgrade flag for installation commands
- doc: adding information on the wipe command
=> documentation updates (2021-11-13)

doc/configuration.rst, doc/directives.rst, doc/tips.rst, sphinxcontrib/confluencebuilder/config/checks.py, sphinxcontrib/confluencebuilder/config/validation.py, tests/unit-tests/test_config_checks.py
A series of minor tweaks to the implementation:
- config: adding configuration checks for various options
- cleanup grammar
- tests: add checks for domain indices
- doc: updating jira casing
- doc: adding additional indices
=> maintenance (2021-11-16)

sphinxcontrib/confluencebuilder/builder.py
When generating navigational bars, do not include any placeholders used for special pages. Special pages do not support navigation at this time (if ever).
=> do not consider placeholders for special pages for navigation

doc/contents.rst, doc/directives.rst, doc/roles.rst, sphinxcontrib/confluencebuilder/__init__.py, sphinxcontrib/confluencebuilder/roles.py, tests/unit-tests/datasets/jira/valid-role/index.rst, tests/unit-tests/test_confluence_jira.py
Add a new Jira role to compliment the existing Jira directive.
=> add jira role

tests/lib/__init__.py, tests/test_validation.py
Adding an "edit source" link to the validation's configuration.
=> tests-validation: include source link

tests/test_validation.py, tests/validation-sets/header-footer/header.tpl
Enabling the page generation notice in the validation testing.
=> tests-validation: add page generation notice

doc/features.rst, sphinxcontrib/confluencebuilder/transmute.py
Provide support for processing sphinx-diagrams nodes when using the Confluence builder.
=> add support for sphinx-diagrams

.github/workflows/docs.yml, .readthedocs.yaml
Adding the configuration options for Read the Docs inside the repository (instead of managing them inside the web interface).
=> adding readthedocs configuration

CHANGES.rst, doc/guide-math.rst, sphinxcontrib/confluencebuilder/exceptions.py, sphinxcontrib/confluencebuilder/storage/translator.py, sphinxcontrib/confluencebuilder/translator.py, sphinxcontrib/confluencebuilder/transmute/__init__.py
- translator: refactor image processing
- translator: refactor alignment detection
- exceptions: remove extra newline
- transmute: provide advanced users ways to opt-out of modifications
- Documentation: reword math subsection
=> maintenance (2022-02-27)

sphinxcontrib/confluencebuilder/rest.py
Rate-limiting changes \[1\] attempted to properly track the `Retry-After` header value to apply to any request made, instead of relying on the self-managed exponential back-off implementation. The issue with this first implementation is that is did not properly handle the possible value types of the value -- specifically, not properly handling the string value to an integer seconds value, and also failing to handle a possible string DateTime value \[2\].
This commit attempts to handle all possible `Retry-After` values and properly prepare a seconds delay value to apply to a next request.
\[1\]: d663b0f69506f631b3c02a3fec0f1811e43e9872
\[2\]: https://datatracker.ietf.org/doc/html/rfc2616.html#section-14.37
=> rest: parse expected retry-after values

.github/workflows/build.yml, AUTHORS, CHANGES.rst, README.rst, doc/conf.py, setup.py, sphinxcontrib/confluencebuilder/locale/sphinxcontrib.confluencebuilder.pot, tox.ini
Perform a series of maintenance updates in preparation for a new extension release.
- i8n: updating message list
- AUTHORS: adding new authors
- README.rst: sync eol confluence versions
- doc: sync eol confluence versions
- setup.py: configure py27 environments to force older docutils
- setup.py: specify utf-8 encoding when reading readme
- tox: adjust for new sphinx versions (v4.5.x)
- workflows: adjust for new sphinx versions (v4.5.x)
- README.rst: sync supported sphinx versions (v4.5.x)
- doc: sync supported sphinx versions (v4.5.x)
=> maintenance (2022-03-27)

CHANGES.rst, doc/advanced.rst, doc/contents.rst, sphinxcontrib/confluencebuilder/nodes.py, sphinxcontrib/confluencebuilder/publisher.py
Various maintenance tweaks to the implementation:
- correct comment
- publisher: add debug warning on failed space key fetch
- doc: adding advanced document
=> maintenance (2022-05-29)

CHANGES.rst, doc/configuration.rst, sphinxcontrib/confluencebuilder/assets.py, sphinxcontrib/confluencebuilder/svg.py, tests/lib/__init__.py, tests/unit-tests/test_publisher_base_id.py, tests/unit-tests/test_publisher_page.py
- tests: adjust publisher requests check to throw exception
- add verbose messaging
- doc: reflect confluence_parent_page's change information
=> maintenance (2022-06-04)

CHANGES.rst, doc/features.rst, doc/guide-ci.rst
- doc: add tip on environment-cfg options for ci guide
- doc: cleanup wording
=> maintenance (2022-07-23)

.github/workflows/build.yml, .github/workflows/docs.yml, .github/workflows/validate.yml
- workflows: renaming actions
- workflows: document actions
=> GitHub actions cleanup

CHANGES.rst, MAINTAINERS.rst, README.rst
- CHANGES.rst: adjust casing for change entries
- MAINTAINERS.rst: add twine check command
- README.rst: use proper badge image/url
=> maintenance on various repository documents

sphinxcontrib/confluencebuilder/publisher.py
If a publish event attempts to upload a page with a same name of an archived page, the publish attempt will fail (due to conflict). There currently is no way to unarchive a page through the REST API interface at this time. To help deal with these scenarios, attempt to remove the page and then upload the new page contents.
This will not work for users who do not have delete support; however, users in this scenario would still fail to publish due to a page being archived. At this time, the only workaround is to manually unarchive the conflicting page(s).
=> publisher: remove archived page on re-introduction

CHANGES.rst
Adding changes during development window.
=> CHANGES.rst: adding features/changes

.github/workflows/build.yml, .github/workflows/docs.yml, README.rst, doc/conf.py, tox.ini
Update the repository to test against the most recent version of Sphinx.
In addition, update the supported Sphinx and Confluence versions in the README/documentation.
=> sync. sphinx confluence versions

.github/workflows/build.yml, .github/workflows/docs.yml, .github/workflows/sphinx-dev-check.yml, .github/workflows/validate.yml, pyproject.toml, tox.ini
Adding a classifier to indicate this extension supports Python 3.11.x, as well as updating testing to test against the new interpreter.
=> python 3.11 support

doc/build
Adds a helper shell-script to help quickly build HTML documentation from a shell.
=> doc: adding build helper script

doc/directives.rst, sphinxcontrib/confluencebuilder/__init__.py, sphinxcontrib/confluencebuilder/directives.py, sphinxcontrib/confluencebuilder/nodes.py, sphinxcontrib/confluencebuilder/storage/translator.py, tests/unit-tests/datasets/excerpt/index.rst, tests/unit-tests/datasets/excerpt/second.rst, tests/unit-tests/test_confluence_excerpt.py
I just implemented the confluence_excerpt directive closely following the confluence_expand directive. I will implement the confluence_excerpt_include directive later.
=> Add confluence_excerpt macro

AUTHORS, LICENSE, doc/conf.py
- AUTHORS: updating authors
- LICENSE: bump copyright year
- doc: sync supported sphinx versions (v6.x)
=> maintenance work (early January, part2)

CONTRIBUTING.rst, doc/features.rst, doc/roles.rst, sphinxcontrib/confluencebuilder/assets.py, tox.ini
Cleanup a series of comments, documentation and configurations based off changes over the development cycle. Specific commits may provide more details for various maintenance actions.
=> maintenance 2023-03-04

tests/lib/__init__.py, tests/test_sandbox.py
- tests: automatically find test container output name
- tests: accept debug argument in sandbox arguments
=> testing maintenance

sphinxcontrib/confluencebuilder/publisher.py
It has been observed on Confluence Cloud that in some cases when a user publishes a new attachment to a page (and maybe specifically attached to a newly created page), Confluence may report a 503 error. The behaviour is odd since Confluence does partially process the new attachment (a viewable entry on the page's list of attachments), but the data for the attachment entry is corrupted. And in a next publish attempt, since the comment hash is unchanged, this extension will not attempt to re-upload. To help prevent this case, if a 503 error state is detected, check to see if the attachment entry was created with corrupted data (i.e. can we query for an existing attachment). If we find it, re-attempt to publish the attachment.
=> publisher: retry attachment upload on 503 error

sphinxcontrib/confluencebuilder/publisher.py
For environments using the marketplace extension Akeles Consulting's "Attachment Checker for Confluence", certain files will be not permitted as attachments for a documentation's publish event. While common file types may work, most of these environments will probably not be configured to accept Sphinx's Intersphinx file. This will result in publication always failing (unless `confluence_publish_intersphinx` is configured).
In order to be flexible for such environments, we will take a relaxed approach for restricted files. In the event that an attachment fails due to this "Attachment Checker" addon, we will generate a warning instead of failing.
Note that this is only a crude tweak to this extension. The check for this error case relies on the default error message for the addon. For …
=> publisher: generate warning on restricted attachment types

sphinxcontrib/confluencebuilder/storage/translator.py
Instead of defining internal page links using a `ac:link` macro, it appears that in Confluence's v2 editor, it is expected to use plain `a` tags to point to these anchors. This is in part due to anchor macros added to a page will use the raw anchor value given, instead of prefixing the anchors with page prefixes.
=> translator: support anchor links in v2 editor

doc/configuration.rst, sphinxcontrib/confluencebuilder/builder.py, sphinxcontrib/confluencebuilder/config/checks.py
Provides a helper configuration for Codeberg hosted sources.
=> provide codeberg helper for source link configuration

tests/sample-sets/sphinx-toolbox/assets/hello_world.txt, tests/sample-sets/sphinx-toolbox/conf.py, tests/sample-sets/sphinx-toolbox/index.rst, tests/sample-sets/sphinx-toolbox/tox.ini
Ported over the sandbox tests used to help sanity check sphinx-toolbox capabilities.
=> tests-sample-sphinx-toolbox: adding sample set

CHANGES.rst, doc/_themes/sphinx13b/static/sphinx13b.css
- doc: improve look of code blocks inside admonitions
=> maintenance (2023-05-13)

doc/configuration.rst, sphinxcontrib/confluencebuilder/__init__.py, sphinxcontrib/confluencebuilder/config/checks.py, sphinxcontrib/confluencebuilder/config/notifications.py, sphinxcontrib/confluencebuilder/std/confluence.py, sphinxcontrib/confluencebuilder/storage/translator.py, tests/unit-tests/test_config_checks.py, tests/unit-tests/test_sphinx_codeblock.py
=> Support `Theme` attribute in `Code Block` macro

CHANGES.rst, doc/configuration.rst, sphinxcontrib/confluencebuilder/__init__.py, sphinxcontrib/confluencebuilder/config/notifications.py
A series of maintenance work:
- adjust configurations to flag confluence-rebuilds
- cleanup imports
- doc: cleanup
=> Maintenance (2023-06-10)

tests/validation-sets/base/index.rst
Improve the layout of the landing page for the validation set, avoiding the odd image placement with bullets on large screens.
=> tests: improve validation set landing page

doc/configuration.rst, doc/guide-class-hints.rst, doc/guide-collapse.rst
- doc: expand class hints guide
- doc: improve description of parent overrides transform
=> documentation updates

sphinxcontrib/confluencebuilder/storage/translator.py
Provides a minimal/initial implementation to support documentation which uses the sphinx-data-viewer extension.
=> support sphinx-data-viewer extension

doc/conf.py, doc/features.rst, doc/guide-ci.rst, doc/roles.rst, sphinxcontrib/confluencebuilder/locale/sphinxcontrib.confluencebuilder.pot
A series of maintenance changes:
- locale: update catalog
- doc: remove strike role example in roles document
- doc: add page break for latex/pdf
- doc: remove italics from links for latex/pdf
- doc: adding feature note for sphinx-data-viewer
=> Maintenance updates (2023-07-16)

tests/unit-tests/test_publisher_connect.py
Cleanup a linter warning for newer versions of flake8.
=> tests: cleanup linting

sphinxcontrib/confluencebuilder/builder.py
Refers to #841. Adds missing PARAM helper functions.
=> Add missing PARAM helper function

.github/workflows/build.yml, pyproject.toml, tox.ini
Updates classifiers (assuming tests pass)
=> Test Python 3.12

sphinxcontrib/confluencebuilder/storage/translator.py
For the v2 editor, we currently nest header anchors inside header blocks to prevent the styling of the v2 editor for adding large spacing between a leading anchor and the header.
When injecting anchors for paragraphs, the same spacing occurs. To avoid this, we now also forward anchor creation to the start of a paragraph.
=> translator: nest v2 anchors inside paragraphs

.github/workflows/build.yml, .github/workflows/docs.yml, .github/workflows/sphinx-dev-check.yml, .github/workflows/validate.yml
Increase the versions of various action packages used to their latest versions.
=> .github: bump various ci action versions

CHANGES.rst, sphinxcontrib/confluencebuilder/exceptions.py, sphinxcontrib/confluencebuilder/rest.py
- cleanup whitespaces
- cleanup grammar
=> maintenance (2024-02-25)

doc/_themes/sphinx13b/static/sphinx13b.css, doc/guide-confluence-macros.rst
- doc: updates to confluence macro guide (index and content)
- doc: tweak rtd badge icon for an improved alignment
=> Documentation updates (part 2)

sphinxcontrib/confluencebuilder/builder.py
The translator will add appropriate wrapping tags on documents to emulate v2's narrow page width capability for v1 editors. However, this logic does not get applied for special documents such as a generated index or search page. Updating the builder logic to apply the same wrapping tags based on the user's configuration.
=> builder: fix narrow page width for v1 editor for search/index pages

doc/tips.rst, sphinxcontrib/confluencebuilder/__main__.py, sphinxcontrib/confluencebuilder/cmd/conntest.py
Provide an initial implementation of a connection-test helper, an operating mode which may help users test configuration and connection with a Confluence instance.
=> Introduce connection test

doc/advanced.rst, doc/guide-ci.rst, doc/guide-math.rst
- doc: correct grammar
- doc: tweak page break in latex to improve readability in pdfs
- doc: rewrite ci guide
=> Documentation updates (CI guide and other tweaks)

sphinxcontrib/confluencebuilder/locale/sphinxcontrib.confluencebuilder.pot, sphinxcontrib/confluencebuilder/storage/translator.py
- translator: wrap locale on page-gen-notice message
- locale: synchronize translation files
=> update locale files

check, sphinxcontrib/confluencebuilder/publisher.py, sphinxcontrib/confluencebuilder/rest.py
- rest: cleanup import ordering
- publisher: add note on err case with 'search' page search mode
- rest: column wrap comment
- rest: skip-warning wrap rate limit warnings
- adding check utility
=> Maintenance (2024-06-22)

doc/_themes/sphinx13b/static/sphinx13b.css
- doc: increase caution/warning border
- doc: add styling for tips
=> Improve documentation admonitions

sphinxcontrib/confluencebuilder/builder.py
Updating a series of logs generated from the builder to improve a user's experience. This includes:
- Ensure trailing `done` prints only occur in a non-verbose mode.
- Adding a note-print when performing cleanup descendants population.
- Add a progress status when performing cleaning attachment population.
=> builder: improve output experience for various logs

sphinxcontrib/confluencebuilder/publisher.py
Confluence Cloud has dropped the use of its older pagination support since 2020-07-15 \[1\] which has prevented this extension from properly processing cleanup operations if the target environment has over 249 descendants/attachments. This commit updates the search calls to use Confluence Cloud's link hints to acquire an appropriate cursor hint.
\[1\]: https://developer.atlassian.com/cloud/confluence/change-notice-moderize-search-rest-apis/
=> publisher: support confluence cloud's modernized search

doc/configuration.rst, sphinxcontrib/confluencebuilder/__init__.py, sphinxcontrib/confluencebuilder/builder.py, sphinxcontrib/confluencebuilder/config/checks.py, sphinxcontrib/confluencebuilder/config/notifications.py, tests/unit-tests/test_config_checks.py
- drop confluence_file_transform
- drop confluence_link_transform
=> Drop unused transforms

.github/workflows/build.yml, README.md, check, tests/unit-tests/test_config_postfix_formatting.py, tox.ini
Updating the tox configuration and GitHub actions to test against the most recent Sphinx series.
A tweak to testing is included as well as some related script/document updates.
=> Test against Sphinx 7.4.x

sphinxcontrib/confluencebuilder/cmd/report.py
When presenting various configuration items in a report, add a hint to which options have been provided from the environment.
=> report: hint on environment-provided options

doc/configuration.rst, sphinxcontrib/confluencebuilder/__init__.py, sphinxcontrib/confluencebuilder/builder.py, sphinxcontrib/confluencebuilder/manifest.py
This commit introduces a manifest file generated after a build event. A manifest file can be used for either informational purposes for a user, but also used by additional tooling which may with to perform its own post-publishing using an alternative means.
<details><summary>An example output of a <code>scb-manifest.json</code> file.</summary>
```
{
"type": "SphinxConfluenceBuilder/Manifest",
"spec": 1,
"language": "en",
"pages": [
{
"id": "admonitions",
"title": "Admonitions",
"parentId": "index",
"parentTitle": "reStructuredText",
"hash": {
"sha256": "28d3e0e53831603e93b42d5700b5e504eb0ae11f612c5d3d3bcc1ed3873e0bb2"
},
"path": "admonitions.conf"
},
{
"id": "bibliographic",
"title": "Bibliographic fields",
"parentId": "index",
"parentTitle": "reStructuredText",
"hash": {
"sha256": …
```
=> manifest: introduction of a manifest file

sphinxcontrib/confluencebuilder/nodes.py
Moving nodes around to order by name; no functional changes.
=> sort nodes by name

sphinxcontrib/confluencebuilder/builder.py
We originally encoded specific characters to prevent Confluence from suppressing anchors for select characters, but it is unknown the extensive list of characters Confluence was not happy with. We then switch to `quote` which worked for the most part, but when users used Emoji's, these characters would become encoded and generate anchor targets with incorrect values. Now, we do a partial quote in an attempt to be flexible -- we quote the standard ASCII range using Python default safe sets and anything beyond it, we will just leave as is.
=> builder: do not encode emoji/unicode characters for anchor targets

doc/directives.rst, sphinxcontrib/confluencebuilder/__init__.py, sphinxcontrib/confluencebuilder/directives.py, sphinxcontrib/confluencebuilder/nodes.py, sphinxcontrib/confluencebuilder/storage/translator.py, tests/unit-tests/datasets/panel-missing-title-with-title-bg-color/index.rst, tests/unit-tests/datasets/panel-missing-title-with-title-color/index.rst, tests/unit-tests/datasets/panel/index.rst, tests/unit-tests/test_confluence_panel.py
Provide a directive to help create a Confluence Panel macro on a given document.
=> introduce confluence panel directive support

doc/directives.rst, sphinxcontrib/confluencebuilder/__init__.py, sphinxcontrib/confluencebuilder/directives.py, sphinxcontrib/confluencebuilder/nodes.py, sphinxcontrib/confluencebuilder/storage/translator.py
Provide a directive to help create a Confluence PDF macro on a given document.
=> introduce confluence viewpdf directive support
